### ISSUE TITLE
The uri used to create an annotation conflicts with the uri used to determine group scope

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1005]
The annotator portion of the client and the sidebar portion of the client use different uri's when the page contains metadata that overrides the uri in the url bar.

The annotator uses  https://github.com/hypothesis/client/blob/823ce81666bfb77de91cb739f2030a2d3773c476/src/annotator/guest.coffee#L113 to get the uri, while the sidebar in group services uses https://github.com/hypothesis/client/blob/823ce81666bfb77de91cb739f2030a2d3773c476/src/sidebar/store/modules/frames.js#L74 to determine whether a group is scoped to the page. 
This can lead to unexpected errors where a group is scoped to the page and shows up but when the user tries to create an annotation it will throw a 404 error because the target uri sent in the api request is not the same as the uri used to determine the group scope. It can also lead to scope enforced groups unexpectedly not showing up on pages that they are scoped to if the uri used to scope the group is the uri contained in the page's metadata as opposed to the uri in the url bar.

**Comment by robertknight** [comment]
I've moved this here so I can apply the same label as the other issues related to this project.

**Comment by robertknight** [comment]
@hmstepanek - was there a specific example you encountered which prompted this issue to be filed? I'm sure we can figure one out, but if you already had one in mind it would be useful to know.

**Comment by hmstepanek** [comment]
@robertknight I ran into this issue while testing. Here is the slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1556299381066700.

**Comment by robertknight** [comment]
After doing some investigation into this and reading of the relevant code, I believe that the issue relates to pages that have annotation-enabled iframes on them ([Slack discussion](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1561467578107000)). Specifically, problems can happen when:

1. A user visits a page at https://foo.com/bar, which embeds an iframe from https://foo.com/meep, and the iframe is [configured to support annotation](https://h-client.readthedocs.io/en/latest/publishers/embedding/#enabling-annotation-of-iframed-content)
2. There is a group G with an enforced scope of https://foo.com/bar
3. The user activates Hypotheiss, selects the group G in the Hypothesis client and then attempts to annotate in the iframe hosted at https://foo.com/meep

When they attempt to post the annotation, this will fail because the annotation's URL (https://foo.com/meep) does not match the group's scope (https://foo.com/bar).

Since the publisher has to opt-in to making iframes annotatable, and we can always add additional URIs as group scopes, I think we can avoid doing anything about this for now. I did encounter an issue with the code which was not clear about which URL gets used for searching for groups, and opened a PR to resolve that.

**Comment by robertknight** [comment]
We did do some refactoring related to this in https://github.com/hypothesis/client/pull/1196 to clarify what the current behaviour is and reduce the risk of it changing unexpectedly in future. Otherwise we’re going to say that this is a known limitation with group scopes and pages that have annotation-enabled iframes.
