### ISSUE TITLE
Community groups clean-up

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1016]
- [x] Refactor the `load` method of the groups service to reduce its overall complexity following the addition of new functionality
- [x]  Remove unnecessary group logic from the loading annotations portion of the sidebar-content (see slack thread [here](https://hypothes-is.slack.com/archives/C1M8NH76X/p1556760933032800)) [PR](https://github.com/hypothesis/client/pull/1211)
- [x] Turn the `community_groups` feature flag on for everyone
- [x] Remove checks in the client for the `community_groups` feature flag, keeping only the "on" code path (https://github.com/hypothesis/client/pull/1195)
- [x] Remove the "community_groups" feature flag from h (https://github.com/hypothesis/h/pull/5648)
- [x] Remove any unused code for the old groups menu (https://github.com/hypothesis/client/pull/1195)
- [x] Remove any unused code that exists to support the old drop-down menus (https://github.com/hypothesis/client/pull/1180, https://github.com/hypothesis/client/pull/1195)
- [x] Rename `groups-list-v2.{js,scss}` => `groups-list.{js,scss}` and update CSS class names (https://github.com/hypothesis/client/pull/1199)

**Comment by robertknight** [comment]
The issue description here previously had a mixture of:

1. Direct clean-up tasks related to the work on this project (removing feature flag and dead code)
2. Refactoring to address places where significant complexity was added (the groups service)
3. Some slightly open-ended plans about refactoring of existing modules that were touched during this work

In order to constrain and clarify the scope, I've updated the description to keep only sub-tasks in buckets (1) and (2). We will need to come back to the items in bucket (3) though as part of converting `<sidebar-content>` and other components from Angular => (P)react. Please do feel free to open separate tasks for those @hmstepanek. GitHub now keeps previous versions of issue descriptions so you can get the details from there.

**Comment by lyzadanger** [comment]
Looking at this list, I wonder if it's duplicating some of what we're after with https://github.com/hypothesis/product-backlog/issues/1014

The other menu conversions haven't required maintaining two code paths while developing (i.e. no feature flag dependencies), so I believe we've been cleaning up after ourselves as we go.

However, it does seem useful to, at the end of the conversions, look at the list of remaining components, templates, CSS and tests to make sure we haven't left any cruft behind!

**Comment by hmstepanek** [comment]
Moved the refactoring to https://github.com/hypothesis/product-backlog/issues/1028.

**Comment by robertknight** [comment]
@hmstepanek - Can you add issue links in the description for the "Remove unnecessary group logic from the loading annotations portion of the sidebar-content" checklist item?
