### ISSUE TITLE
Fix Jenkins build failures when many builds are triggered at once (eg. by Dependabot)

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#1025]
body

**Comment by seanh** [comment]
Decisions from DevOps sync today:

* We're removing this from the current sprint. Intention is to do it next sprint
* It sounds like setting up Jenkins slave nodes (so that concurrent jobs don't compete with each other for resources) may be easy to do and the best result, so look into that first
* If multiple simultaneous Dependabot PRs are still a problem we can configure Dependabot to send fewer PRs at once

**Comment by robertknight** [comment]
This issue is no longer relevant since deployments have been moved over to GitHub Actions.
