### ISSUE TITLE
Spike: Add Creation time to user admin screen

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1027]
### Problem you are trying to address with this feature

Currently our admin screen for users only shows the time that their account was "registered".  However, in order to monitor the time difference between creation and registration, it would be helpful to see the account creation time as well.

### Your solution

Also show "Creation" above "Registration".  Then compute the time difference, and after the registration time show the time difference.  (e.g. "5 minutes 23 seconds after creation") so that it's easy to see at a glance what the delay was.

I'd also suggest we harmonize our language.  If the "registration" field is measuring "activation" then it should be labeled "Activation", at least so that someone looking at this screen can see that the "Activated" check mark relates to the time of "Activation".  

Also, I'll note on the page relating to the successful account "registration" that we're using a term which also may be confusing.  In other words, we mean that the account has been "Created", but not yet "Activated".  https://github.com/hypothesis/h/pull/5628

One wonders whether we should avoid use of the term "Registration" at all if it doesn't have a unique and differentiated meaning within our system.  At the least we should be consistent throughout.

**Comment by seanh** [comment]
This isn't an ops issue (requires editing h code hence it's a dev issue)

**Comment by lyzadanger** [comment]
An update...I took a look at what we store on the `User` table today, and believe we will need to make functional changes to be able to have the data we need to discern what we're trying find here—that is, the ability to see the time delta between a user signup and the activation of that record. That is, we can't display any additional information on the admin-user page, as there's no additional information to show unless we make changes.

Here's why:

* The `User` table does not use the `Timestamps` mixins that other tables use. I do not know why this is the case. Perhaps it pre-dates that mixin, or there's something special about the `User` table that makes using that mixin inappropriate. The `Timestamps` mixin is what gives tables both the `created` and `updated` columns. The `User` table does not have those columns.
* The `User` table has two date-time columns, both of which are already being displayed on the admin-user page. These are `registered_date` and `last_login_date`.
* `registered_date` has a default value of "now" and is set when the record is created—i.e. on signup—and AFAICT never touched again. It is roughly analogous to `created` on other tables.
* `last_login_date` also has a default value of "now" and is set when the record is created (note this: it is set, even though the user has never logged in).
* Both `registered_date` and `last_login_date` have "NOT NULL" enforcement
* `last_login_date` is updated by `h.views.accounts` on login
* When a user activates their account, the activation record associated with the account is deleted. No timestamps are updated. That means that, at present, unless I'm missing something, we _do not record account activation times or metadata_.

Thus, it's not possible to show more info on the admin-user page as there is no additional information to show.

This situation should be rectified but requires changes to the `User` model/table and/or functional changes.

One approach could be to add a new column to the `User` table, `activation_date`, a NULL-able datetime field that could get set by the `h.models.User.activate` method (note: in our more modern code conventions, this would typically be handled by a service, but anyway). Additionally, we might consider making `last_login_date` nullable and not populating it until the user logs in for the first time, as it's misleading otherwise.

**Comment by klemay** [comment]
@lyzadanger Thank you for looking into this!

@dwhly, at present there is no more info to display on the user admin page. We need to make changes to the `User` table first. 

Lyza, seems like a good next step is for me to create 3 tickets:
- Add `activation_date` column to `User` table
- Show `activation_date` on user admin page
- Don't populate `last_login_date` until user logs in for the first time

The 3rd one is a "nice-to-have;" the 1st 2 meet the requirements for this Spike. 

If we agree, I'll create those tickets & close this spike.

**Comment by dwhly** [comment]
So, "created" is equivalent to "registered".  Then "activated" comes later, when the account is activated.  And then after that would be "last login date" at first login.  I can update the terms used here on this issue to reflect.

**Comment by klemay** [comment]
Currently, "last login" is updated when the account is created (even though creation =/= logging in), and we don't keep a separate "activated" record. Lyza has proposed adding one. Once that happens, yes, it will be:

- registered_date  is set when the record is created—i.e. on signup
- activation_date will be set when user's account is activated 
- last_login won't be set until the user actually logs in for the first time

**Comment by lyzadanger** [comment]
@klemay Agreed on your plan! Please close this and open issues for identified items.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/1033, https://github.com/hypothesis/product-backlog/issues/1034, and https://github.com/hypothesis/product-backlog/issues/1035.
