### ISSUE TITLE
Spike: Enhancements to share links now that scoping to groups is possible

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#1030]
Problem: Now that we've implemented the scoped groups to bouncer, we need to evaluate the enhancements that are now possible, and the changes we should make to ensure seamless UX for all share functions in our app. This also echoes some thoughts that @robertknight brought up in the last demo. 

In this spike we'll investigate the features that need to be updated/introduced. 

Some ideas: 
1. Share link at the top of the sidebar - maybe we should include language that tells users that the share link will take users to annotations from a specific group. 
2. See annotations in context link in activity pages
3. https://github.com/hypothesis/product-backlog/issues/713
4. https://github.com/hypothesis/product-backlog/issues/855

**Comment by lyzadanger** [comment]
There are two major sharing options in the client:

* Share "this page's" annotations (share a collection of annotations): accessible through a share icon in the top bar
* Share an individual annotation: accessible through a share icon on annotation cards

I'm going to talk about the first one now. Currently it looks like this:

![image](https://user-images.githubusercontent.com/439947/60125402-bd943100-9759-11e9-9c85-2a4789aa94b0.png)

It doesn't actually do what it says it does at present because if a user has a particular group focused and uses the provided share link, another user will quite likely have a different group focused. No good!

Some immediately-obvious other things:

* The styling of the header in this panel seems inconsistent
* For some inexplicable reason, the text in the heading "Share" is linked...to nothing.
* We should use the "copy-to-clipboard" tool and icon here
* The description text is inaccurate on all counts, as this link doesn't serve as an invite link for private groups and "invitation" is irrelevant for open and restricted groups
* There's no indication that private annotations wouldn't show up
* ultra-light font weight is hard on readability (IMO)

### Some Ideas

#### Share scoped-to-group by default

This is the big change I'd suggest: this link should be formatted such that it scopes to the currently-focused group in all cases. I believe that this is the most intuitive behavior. DISCUSS! :)

#### Very lo-fi mockup of possible behavior

**(Please ignore font styling, alignment, spacing, etc.):**

Restricted and open groups:

![image](https://user-images.githubusercontent.com/439947/60128891-bd982f00-9761-11e9-9408-59e6ee5d0260.png)

Private groups:

![image](https://user-images.githubusercontent.com/439947/60128156-fc2cea00-975f-11e9-8eca-3978f9dac9db.png)

### Things to Consider (Questions to discuss)

* Are we still committed to having Facebook and Twitter share buttons in our app? Just checking.

**Comment by klemay** [comment]
I really like the addition of who can see annotations (including an explanation of permissions on "only me" annotations). 

Agreed on all other points re: 
- ultra lightweight font
- styling inconsistency
- copy-to-clipboard icon

Small suggestion about the copy:
- Rather than "Share Finagle a Bagle's Annotations" I'd say "Share Annotations in Finagle a Bagle" - the current format makes it seems like Finagle a Bagel is a single user, but it's a group

**Comment by hmstepanek** [comment]
I agree with this general direction and with what @klemay said in her last bullet point.

> Rather than "Share Finagle a Bagle's Annotations" I'd say "Share Annotations in Finagle a Bagle" - the current format makes it seems like Finagle a Bagel is a single user, but it's a group

Thoughts on twitter and facebook I'd be curious if anyone uses those-data might be available via google analytics.

**Comment by seanh** [comment]
Does sharing one of these links to a private group's annotations reveal the group's pubid, so that anyone with the link can join the group?

**Comment by dwhly** [comment]
> Does sharing one of these links to a private group's annotations reveal the group's pubid, so that anyone with the link can join the group?

Yep, I think so.  But I think that's ok.  This was always "security by obscurity" and if you choose to use this feature to share, then it's on you.  *Possibly* there could be some fine print that would explain that.  But it could be too much detail too.

**Comment by lyzadanger** [comment]
> Does sharing one of these links to a private group's annotations reveal the group's pubid, so that anyone with the link can join the group?

Just to be extra clear, you'd have to take the pubid exposed in the share link and reconstruct it into an invite/activity link (not that that's hard! But it's not like you can use the share link directly).

I toyed with adding some text around this but, as Dan noted, it felt too long.

**Comment by jaredpdesigns** [comment]
Here’s a couple variations of the share card based on feedback.

### Notes
- I’m presenting a few variations of the `copy` icon to see what lands best with others.
- I tried emphasizing the close button by changing it’s shape and background color. The position of the button feels appropriate but agree it’s low-visibility may cause some issues.

### Preview
![share-open](https://user-images.githubusercontent.com/6108048/60222377-d1529c80-9818-11e9-8186-2b3199bf1102.png)
![share-private](https://user-images.githubusercontent.com/6108048/60222378-d1eb3300-9818-11e9-9fa2-178cbee1139f.png)

**Comment by seanh** [comment]
> > Does sharing one of these links to a private group's annotations reveal the group's pubid, so that anyone with the link can join the group?
> 
> Yep, I think so.  But I think that's ok.  This was always "security by obscurity" and if you choose to use this feature to share, then it's on you.  *Possibly* there could be some fine print that would explain that.  But it could be too much detail too.
> 
> Just to be extra clear, you'd have to take the pubid exposed in the share link and reconstruct it into an invite/activity link (not that that's hard! But it's not like you can use the share link directly).
> 
> I toyed with adding some text around this but, as Dan noted, it felt too long.

Maybe we should consider only showing these share links for open and restricted groups, not for private groups?

If these links do include the pubids of private groups then I think this may be worth some further thought. Giving someone the pubid of a private group doesn't just mean that person can see that group's annotations on the current page, it means the person can join the group and see all of its annotations (past and future) and also create annotations in the group, and this group membership is not revocable. _Publicising_ a private group's pubid is kind of nuclear -- the internet now has permanent access to your private group which has for all intents and purposes effectively become an open group, and this can't be undone. And it looks like we're providing handy Twitter and Facebook links to blow up your group like this.

I understand someone would have to copy and paste the pubid out of the URL but still -- the way private groups work in h is that the pubid is the permanent and unchangeable secret key to the group. I think encouraging people to share that, especially to Twitter and Facebook, might not be a good idea. The only place we currently ask people to copy and share the pubid is _in order to invite people to the group_, not in order to share the group's annotations of a page.

**Comment by lyzadanger** [comment]
> Maybe we should consider only showing these share links for open and restricted groups, not for private groups?

Curious, how would you suggest we do that, UX-wise? This share dialog is launched from the share icon in the top bar, which is always present. (As an aside, I have long thought that the sharing icon—because it pertains to a collection of annotations, not the whole app—doesn't necessarily belong in the top bar, but closer to the set of annotations it references.)

**Comment by dwhly** [comment]
> Maybe we should consider only showing these share links for open and restricted groups, not for private groups?

Deny all possible use cases in order to avoid the potential for self-inflicted harm?  Hmm.

I think we can all imagine workflows in which being able to grab a focused links into a specific page would be useful within that community-- for instance, on summary documents that provide links into the various articles the community has annotated, etc.  I think if we're concerned, we should consider a warning label instead.

Remember that *two* things have to go wrong:  1) someone has to share a link to something they already consider private, and 2) someone else has to then reverse engineer the group URL.

Also, there's already an invite link we provide to groups.  And that invite link itself could be accidentally or otherwise shared without the group owner's knowledge to invite any others into their group.  This feels like the same thing.

**Comment by lyzadanger** [comment]
@jaredpdesigns The look of the updated component is clean and clearer than our current variant—thank you!

There are a couple of typos (e.g. `annotation` should be plural) but I think we can skim over that for now.

I have a concern that the dark close button, while I _like_ it and it stands out well in isolation, may feel stark/too-contrasty in our very-low-contrast sidebar context reality. Really the solution IMHO is to up our app's contrast across the board (pet campaign of mine for a11y ;) ) but that's not gonna happen overnight.

The second icon is more unambiguously a copy-to-clipboard icon to my eyes, but I know there are other opinions on that.

I'm hesitant to link the group names in the descriptive text... in part because it's not clear where those links go but also because of the reality we have because of our interesting sharing/invite model that those links _actually do different things_ depending on the group type and the user's relationship to that group, so I think it could open a can of worms.

I'm also still musing about whether the heading here should include the group name. Though the description text does mention the group, it's not crystal clear that this is a sharing link for annotations _in this group_. (i.e. "Share Annotations in Finagle a Bagel" is clearer). We have a hard limit on group-name lengths (25 chars) so we can rest assured at this point that the heading wouldn't get _too_ long.

**Comment by dwhly** [comment]
>  I have long thought that the sharing icon—because it pertains to a collection of annotations, not the whole app—doesn't necessarily belong in the top bar, but closer to the set of annotations it references

We did consider share, search and sort all being on the line below, to the right of the tabs for exactly this reason.  Not an unreasonable notion.

**Comment by lyzadanger** [comment]
> I'm also still musing about whether the heading here should include the group name. Though the description text does mention the group, it's not crystal clear that this is a sharing link for annotations in this group. (i.e. "Share Annotations in Finagle a Bagel" is clearer). We have a hard limit on group-name lengths (25 chars) so we can rest assured at this point that the heading wouldn't get too long.

One of the reasons I'm pushing on this is also because we are proposing changing the behavior of this link from what it currently does (no group context currently) so I want to try to be as clear as possible.

**Comment by seanh** [comment]
> > Maybe we should consider only showing these share links for open and restricted groups, not for private groups?
> 
> Deny all possible use cases in order to avoid the potential for self-inflicted harm?  Hmm.
> 
> I think we can all imagine workflows in which being able to grab a focused links into a specific page would be useful within that community-- for instance, on summary documents that provide links into the various articles the community has annotated, etc.  I think if we're concerned, we should consider a warning label instead.
> 
> Remember that *two* things have to go wrong:  1) someone has to share a link to something they already consider private, and 2) someone else has to then reverse engineer the group URL.
> 
> Also, there's already an invite link we provide to groups.  And that invite link itself can be further shared without the group owner's knowledge to invite any others into their group.  This feels like the same thing.

_Surely_ we're not going to ship a handy `Share these annotations [Twitter] [Facebook]` widget that, if used, leaks the secret key that gives read and write access to your private group and all its past and future annotations?

The already existing invite link is a different thing. It's _purpose_ is to invite people to join the group. It's labeled in the UI as "**Invite new members:** Sharing the link lets people join this group." These invite links are what the pubids were created for and are still used for. But we're now talking about a "Share these annotations" link that contains the same pubid.

I don't think the harm would be self-inflicted: if we give the user a "Share these annotations" button it's reasonable for the user to assume that that won't leak read/write access to their entire group. That would be like if a share link on one google doc, gave someone complete access to our team drive.

Here's a couple of suggestions:

1. Implement an alternative type of group ID to use in the URLs. An ID that doesn't let people join the group.

2. Make these share links explicitly double as invite links. If a user who is not a member of the group clicks on one of these share links then, just as if they had clicked on one of the invite links, they should be shown a _Join this group_ button. Then make the share widget UI clearly say __"Anyone with the link can join the group"__ (and hopefully that implies write access, and read access to past and future annotations).

**Comment by jaredpdesigns** [comment]
Here are a few more iterations based on the feedback from @lyzadanger 

- I think including the name of the group in the title provides the clearest intention of what in fact a user will be doing.
- Provided a couple of options for `close`—me thinks if we stick with a lower-contrast background color for the button it would probably be best to accompany the icon with a label for added clarity and scannability. For consistency it’s also probably best to stick with the pattern of highlighting things that are actually buttons—see the caret pattern developed for the groups menu.
- Played around a bit more more with typographic hierarchy for the cards themselves to distinguish between secondary helper text and primary labels.
- Picked the first option for `copy` which is also consistent with the icon we’re using for “Copy activity link” in the groups menu

![share-open](https://user-images.githubusercontent.com/6108048/60307345-ec3c1400-98df-11e9-9490-71be7f2ba776.png)

![share-open-alt](https://user-images.githubusercontent.com/6108048/60307351-efcf9b00-98df-11e9-9e07-e6d9bd711b9c.png)

![share-private](https://user-images.githubusercontent.com/6108048/60307347-ec3c1400-98df-11e9-8ad3-62c4c9b4a87f.png)

![share-private-alt](https://user-images.githubusercontent.com/6108048/60307357-f65e1280-98df-11e9-904b-fe54068b87fc.png)

**Comment by jaredpdesigns** [comment]
@lyzadanger wanted to post a small design change for the share card to make it clearer there was a `button` to click to copy a particular URL—it's something we discussed in our design meeting today.

![share-open-separation](https://user-images.githubusercontent.com/6108048/61164366-2ac0f980-a4b0-11e9-8956-729d1fc0f3e2.png)

**Comment by klemay** [comment]
Please move to 1209 in client - along with the final screenshot(s)

**Comment by lyzadanger** [comment]
I was working on implementing this and I just now noticed that both the Facebook and email icons are different here than what is available in the hypothicons set. @jaredpdesigns help?

**Comment by jaredpdesigns** [comment]
@lyzadanger I am migrating the Hypothicons to the new Pattern Library site and all the icons on that page are easily click-copy to get an SVG of the icon itself. [https://hypothesis-pattern-library.netlify.com/#icon](https://hypothesis-pattern-library.netlify.com/#icon)

The icons that are featured in the previous mock-up above are what was currently in the application via the icon font and other resources. 

I hope that helps!

**Comment by lyzadanger** [comment]
@jaredpdesigns I have another question: what is the intended interaction behavior of both the Close button and the copy button (i.e. hover states, etc.)?

**Comment by jaredpdesigns** [comment]
@lyzadanger the `:focus/:hover` states should both darken the background of that area by one step, in this case would step up to `gray-2`. On the copy action, I think we could also increase the color contrast of the icon to a step above it’s current as well, so to `gray-6`. Open to suggestions however :)
