### ISSUE TITLE
Spike: Should we move from Pingdom to New Relic for availability monitoring?

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#1048]
This is a spike to see if this is something we should do. 
Things to think about:
1. It would be nice to have all these dashboards in one place
2. Having health check metrics in the same place as the rest of our metrics will enable us to do smarter alerting
3. There may be a cost consideration

**Comment by hmstepanek** [comment]
I have added all the pingdom checks into New Relic plus some additional checks.

# Things left to consider/explore here:
- [x] I have issued an inquiry to NewRelic about pricing for yearly/monthly reports. The free tier has weekly reports (~ a month worth of data retention) and if we purchase a years worth of data retention we can get monthly reports which we could also send to our mailing list as part of our SLA requirements for monthly reports of uptime. The alternative is to generate our own monthly reports-not difficult and we might have to do this anyway or at least modify the ones New Relic builds because they contain a bunch of other info like load times from various ping locations, etc.
- [x] I would like to explore waiting a couple minutes before firing a pager duty alert so we have less false alarms. In pingdom it looks like we wait 5 minutes before firing a pager duty alert. We should really only be paging ourselves if it's an unrecoverable incident meaning it's ongoing for multiple ping attempts. New Relic's default is if 3 ping attempts fail from the same location (so 3 minutes). In general I think this is a fine default. There's certainly a trade off here as the more time we wait the longer the downtime is but I think waiting an extra couple minutes in the grand scheme of things won't hurt us. If we do want to go with 5 minutes instead of 3 in NewRelic, (this article is a bit outdated but it looks like the basic plot is the same) I think we can do this through [NRQL](https://discuss.newrelic.com/t/relic-solution-alert-on-x-synthetics-failures-in-y-minutes/49025).

# Some additional thoughts:
- NewRelic has built in linking to a runbook url which could be a useful way of linking developers with a guide of what to do if a particular alert triggers while they are on call.
![image](https://user-images.githubusercontent.com/30059933/63964872-df0ce400-ca4c-11e9-8159-e4dd27057143.png)

**Comment by hmstepanek** [comment]
I heard back from New Relic today, 12 months of data retention is out of our price range compared to Pingdom (~6x the price). On the other hand I don't think this is a blocker for us switching over. AFAICT we weren't really doing anything with the yearly data in Pingdom anyway, we still have a months worth of data retention with the free tier in New Relic (sufficient for uptime reports), and we still get the benefit of consolidating our monitoring which means smarter alerting and looking at all our metrics side by side.

**Comment by emckean** [comment]
I'm subscribed to this repo kind of accidentally (I think just because I sent in a feature request) but I wanted to point out that New Relic has a pretty generous program fir 501c3 nonprofits (altho you have to ask for it). Just FYI! :)

**Comment by hmstepanek** [comment]
@emckean-they absolutely do and we are already part of it! Unfortunately, even so the data retention is pretty expensive. :(  Thank you for taking the time to make sure we were aware-much appreciated!

**Comment by ajpeddakotla** [comment]
@hmstepanek something to note that some of the security questionnaires we get in do ask us about log retention. A cursory glance at some of the questionnaires shows that the storage time we get asked about the most 90 days. So if we can get data retention for three months in New Relic without the cost going up too much we should do that. We do need to ensure data retention for our partners, so this is an important feature to keep.

**Comment by hmstepanek** [comment]
The decision here is to keep pingdom around for the 90 day report requirement with the possibility of moving the alerting to newrelic if the alert policy needs to be smarter than a not up for x number of minutes.
