### ISSUE TITLE
API docs: buggy behavior in Chrome for Mac

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1103]
We were alerted of this [via a user's annotation](https://hypothes-is.slack.com/archives/C91AR72KH/p1588687333006800). I was able to reproduce.

## Steps to reproduce
1. Using Chrome for Mac, visit our API documentation: https://h.readthedocs.io/en/latest/api-reference/v1/
2. Attempt to scroll down and read the page

## Expected behavior
You can scroll through the page like you would any web page

## Actual behavior
As you scroll down, the page jumps back up to the top. See this gif:
![screenshot-h readthedocs io-2020 05 05-15_07_10](https://user-images.githubusercontent.com/12087705/81105734-5d762b80-8ee2-11ea-8dbb-0cfa1c398c5b.gif)

## Notes
This seems to be a Chrome problem; the site works fine when I try with Firefox and Safari.

**Comment by lyzadanger** [comment]
Likely, this is good news. This seems to be widely reported against the dependency we use (`redoc`) to build these docs, and it appears to have been fixed in a newer version: https://github.com/Redocly/redoc/issues/1170

We "manage" the version of this dependency in an unusual way, see, e.g. https://github.com/hypothesis/h/blob/master/docs/_extra/api-reference/index.html

It may be as easy as updating those CDN references to require a newer version.
