### ISSUE TITLE
A11y question re: consistent screenreader experience for toggles

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1111]
This issue was raised by our follow-up accessibility audit:

> There are three show/hide toggles and each behaves differently. The annotation panel toggle changes the label of the button, the Help toggle has an aria-pressed attribute, the More/Less button has an aria-expanded attribute. This inconsistency in functionality can be confusing for non-visual users. 

It would be helpful to know if this inconsistency is a usability issue that we could address later, or if it would prevent us from getting "Supports" on any particular WCAG criteria. We are planning to [apply the `aria-expanded` attribute to buttons that show and hide panels](https://github.com/hypothesis/product-backlog/issues/1110) - is that enough to get us to "supports"?

NOTE: sounds like this will be moot once we merge https://github.com/hypothesis/client/pull/2189 and add `aria-exapnded` attribute to the button that opens and closes the sidebar.

**Comment by lyzadanger** [comment]
@klemay The `aria-pressed` cited here for the Help toggle is changing to `aria-expanded` as of https://github.com/hypothesis/client/pull/2189

Do you know what the "annotation panel toggle" is? Is that the entire sidebar?

It sounds like the desire is to use `aria-expanded` in these instances...maybe? At least that seems to be the thrust of the other concrete issues. Let's say we merge https://github.com/hypothesis/client/pull/2189 and also add an `aria-expanded` attribute to the show/hide sidebar button (assuming that's what "annotation panel toggle" means). Then there wouldn't be an inconsistency here because all of the buttons cited here would use `aria-expanded`. Right?

**Comment by klemay** [comment]
@lyzadanger yes, the "annotation panel toggle" is the button that opens and closes the sidebar. so if we merge https://github.com/hypothesis/client/pull/2189 and add `aria-expanded` to the button that opens and closes the sidebar, we'll have a consistent experience for all 3 items and can close this issue

**Comment by lyzadanger** [comment]
@klemay I believe our merged a11y fixes from last week should settle this issue. Can you confirm and we can close?
