### ISSUE TITLE
Implement overlay based highlighter

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/product-backlog#1136]
For many reasons including breaking apps/selectors, conflicting with the environment, and odd layering issues with pdfs, we are going to try to implement the overlay svg style highlighter system which Nick previously built a POC for: https://github.com/nickstenning/marks

This will directly address: https://github.com/hypothesis/client/issues/403

High level work items:
- [ ] feature flag ability to turn on overlay highlighter
- [ ] port marks poc into a module that satisfies the current highlighter interface methods
- [ ] turn on and allow staff to test in production

Implementation should handle:
- [ ] click passthrough
- [ ] touch passthrough
- [ ] matching z-index of content to layering will not break with in-page popups
- [ ] page resizing
- [ ] page scrolling
- [ ] page orientation change

**Comment by ajpeddakotla** [comment]
Hey @sean-roberts! Good to hear from you. Hope things are well with you and the fam, and yep - I remember that PR. Thanks for the heads up though!

**Comment by robertknight** [comment]
Implementing a highlighter that doesn't wrap content has become more complex now because we have a requirement that highlights are visible to assistive technologies. For highlight elements we leverage [hidden text](https://github.com/hypothesis/client/blob/310b5ad15f05989198447f3ed4be218fc1267ba4/src/styles/annotator/highlights.scss#L32) to make screen reader users aware of highlights. In future we can also leverage new browser specs for [marking up annotations](https://github.com/aleventhal/aria-annotations/blob/master/README.md#simplified-aria-annotations-proposal--explainer). If the [CSS highlights API](https://drafts.csswg.org/css-highlight-api-1/) is implemented in browsers and has sufficient assistive technology support we might be able to use that instead.

The issues with PDFs that were mentioned in the issue description have been resolved by separating the markup of highlighted text in the hidden text layer and the rendering of the actual highlights, which in PDFs is now done with an SVG overlay. See https://github.com/hypothesis/client/blob/310b5ad15f05989198447f3ed4be218fc1267ba4/src/annotator/highlighter.js#L63.

For these reasons, I'm going to close this for now.
