### ISSUE TITLE
Possible to annotate archive.org PDFs?

### ISSUE THREAD

**Issue by AJamesPhillips** [hypothesis/product-backlog#1158]
### Steps to reproduce
1. Go to https://web.archive.org/web/20201101001702/https://www.fda.gov/media/134922/download
2. Activate hypothes.is chrome extension
3. Try to annotate the PDF

### Expected behaviour
Should be able to annotate the PDF.

### Actual behaviour
Selecting text does not produce the annotation popup / context menu.

### Browser/system information
Chrome Version 86.0.4240.111 (Official Build) (x86_64), Mac 10.13.6

### Additional details
Works if you go to https://web.archive.org/web/20201101001702if_/https://www.fda.gov/media/134922/download 
this is the url in the `src` attribute of the `embed` tag `<embed id="plugin" type="application/x-google-chrome-pdf" src=`

**Comment by klemay** [comment]
Hi @AJamesPhillips - annotation isn't working at the first URL you provide because the PDF is inside of an iframe. This is a [known issue](https://github.com/hypothesis/product-backlog/issues/1084) with the workaround being to open the PDF directly in your browser (either by using the link you provide in the Additional Details section or by downloading & [annotating locally](https://web.hypothes.is/help/annotating-locally-saved-pdfs/)).
