### ISSUE TITLE
VitalSource PoC: Show booklist

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1200]
Dave Campbell, who works on integrations, wants to see the PoC working with other VS books before moving forward with the UI work we’ve asked for on their end.

They’ve given us access to another book, ISBN 9781400847402 (The vbid for this book is the same as the ISBN)

He’s asking for this because he initially hard-coded the Hypothesis config into the book we’ve been using and he wants to confirm the change works for other books now that it’s been pushed to prod.

We will need to make it so that the VS selection option presents a book list which initially has these two hardcoded books, and confirm the PoC works with the other book.

**Comment by robertknight** [comment]
As of https://github.com/hypothesis/lms/pull/2728 it is now possible to create a Hypothesis assignment that uses the book mentioned in the issue description (ISBN 9781400847402). In the process we discovered that recent changes on the VitalSource side appear to have broken the Hypothesis integration, so we need to chase that up with the VS developers.

Meanwhile on our side, the current VitalSource book selection UI hard-codes the book list and chapter data in the frontend. The next step is to move this to API views on the backend, which will initially return the same hard-coded data (see https://github.com/hypothesis/lms/pull/2831) and then change the chapter-data API call to use the VitalSource products API instead of returning a fixed result.

There isn't an API yet that can return a list of VS books associated with the current course as far as I know, so we will have to look into options for that. One possibility for an initial release is that instead of a book list we present instructors with an input field where they can paste a link to a VitalSource book. From that we can extract the book ID.

**Comment by lyzadanger** [comment]
The prototype requirements here have been satisfied. Please see https://github.com/hypothesis/product-backlog/issues/1100 (the original epic) and https://github.com/hypothesis/lms/issues/2861 (the next epic we're working on here).
