### ISSUE TITLE
[PDF] Expand and contract reader view in PDFs (instead of overlay)

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1258]
**See #1248. This is the same card, except for PDFs.**

**Comment by robertknight** [comment]
I'm not sure if introducing side-by-side mode for fixed layout/PDF-based books will work well, at least if done in the obvious way. The problem is that the content of the page won't automatically reflow if we shrink it, when the sidebar is open, as it does for EPUBs. As a result the text is going to get smaller and may not be comfortably readable. We might be able to try and reserve more space for the text by allowing the sidebar to overlap border/margin areas of the page which don't contain any text. I can do some experimentation and see if a simple approach produces usable results, but we might need to revisit this later.

We do have side-by-side mode for PDFs already of course, but there are some differences compared to PDF.js:

1. The full width of the browser window is available for the sidebar + shrunk content. The VS reader, as it is currently set up, takes up some space on the left/right margins for its own UI.
2. In PDF.js the PDF is re-rendered to the target size from the original content when shrunk, whereas VS PDFs are pre-rendered images. I'm not sure yet how this will affect the visual quality when resized.

**Comment by chrisshaw** [comment]
@robertknight I would suggest that we make **this** card about giving a vanilla experience. That (2) you mention seems like the largest risk. Let's use this ticket to determine whether (2) forces us to pull the plug on side-by-side mode with PDFs.

(Even if it does work, this will, to your point, likely shrink the text beyond usability. But we can at least let the user make that decision, which may not be a problem on larger screens or custom screen settings.)

So I would without from trying to capture the extra space in the margins for now.

Instead, I'll put together 2 new tickets that will allow us to revisit these other risks later:

- [ ] Discovery for UI and UX design on allowing users to choose their view mode (something with brainstormed about in a 1:1)
- [ ] Capturing extra margin space on PDFs (which we may end up discarding, depening on what we learn from risk 2)

**Comment by robertknight** [comment]
> @robertknight I would suggest that we make this card about giving a vanilla experience. That (2) you mention seems like the largest risk. Let's use this ticket to determine whether (2) forces us to pull the plug on side-by-side mode with PDFs.

I agree. Let's use this ticket to make a simple prototype that works similarly to how side-by-side mode works with PDF.js and see how that fares.

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [View annotations side-by-side in VitalSource ebooks ](https://app.harvestr.io/components/0/list/ROQJT_zcS)
