### ISSUE TITLE
Change "Select a Chapter" to "Pick where to start reading"

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1269]
**As a teacher, I want the picker to direct me to pick an entrypoint, so I don't get confused by it.**

Some teachers aren't looking to assign a chapter. They may be looking to assign multiple chapters, or they may be looking to assign only a small segment of a chapter.

The table of contents that show up in the picker show all of these segments but calls them all "chapters." This has confused a few teachers because they think they **must** pick a chapter.

Meanwhile, some teachers wonder if students will have to find the reading. And teachers **always** ask whether students can keep reading or navigate away from the assignment, and we are always explaining that they will land the book at the entrypoint chosen.

### Flow

The header now says, "Pick where to start reading".

**Comment by esanzgar** [comment]
Maybe a page picker feels more natural: 'Pick the page to start reading'.

**Comment by robertknight** [comment]
Changing the current "chapter" terminology to something more abstract, eg. "location", should be straightforward. For EPUB books I would suggest using _location_ rather than _page_ because EPUBs don't have a pre-defined partitioning of the content into the pages. That depends on the viewer settings (eg. larger font => more pages). For PDF books we could offer page number selection. I'd hope it should be possible to determine the type of book (PDF or EPUB) before we open it, since that information is shown in the VS book store UI (using "fixed" or "reflowable" terminology).

> The table of contents that show up in the picker show all of these segments but calls them all "chapters."

AFAIK the level of detail in the table of contents is up to the publisher, so it may not always be possible to offer teachers as fine grained a choice as they want from the table of contents. If it turns out the table-of-contents level of detail is not enough we might need to add some additional way of specifying the location. If the book link has been copied from VitalSource directly then it will include a "CFI" identifier indicating the content the teacher was looking at when they copied the link. I'm not sure, but this may be more precise than what is available in the table of contents.

**Comment by chrisshaw** [comment]
@lyzadanger Let's use ""Pick where to start reading"

This
- is abstract to the TOC
- takes up less space with fewer characters
- scores best on readability

**Comment by lyzadanger** [comment]
What should the submit button say? Right now it says “Select chapter”.

**Comment by lyzadanger** [comment]
Might I suggest just "Select" for the confirm button without a modifier?

**Comment by lyzadanger** [comment]
@chrisshaw 

Screenshot from my current working branch. Just looking for direction on that submit button, if this otherwise looks about right? Note change from "Page" -> "Location" in column header as well, per Rob's good suggestion.

![image](https://user-images.githubusercontent.com/439947/152403415-c73b0347-9d56-473f-a32b-6904bfd0d22f.png)

**Comment by chrisshaw** [comment]
Good catch on the location, I wasn't looking at that. I think the Select works just fine for the submit button. LGTM.
