### ISSUE TITLE
Last line of PDF text on a page not selectable in the new PDF.js

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1283]
**Describe the bug**
From user ticket: https://app.hubspot.com/contacts/6291320/ticket/583626067/

User reports two PDFs that have issues selecting the last line of certain pages in the LMS app that don't have this problem in Firefox.

[PDF 1](https://drive.google.com/file/d/1uIX9xnlXbF9trlNa7pNsjG3GaqTrPnrp/view?usp=sharing) aka "Jess" had a problem at the last line of page 74.

[PDF 2](https://drive.google.com/file/d/12ptZGzJAsXocMiGAZuvaaL7OpBCPl6Cj/view?usp=sharing) aka "Tatum" had a problem with the last line of page 50. 

In Firefox 92:
![image](https://user-images.githubusercontent.com/22603275/135728659-1a175902-a6a1-4d45-bfa7-f014c4e7cc12.png)

![image](https://user-images.githubusercontent.com/22603275/135728684-2d631d90-a40b-48c7-abaa-6177cd1dc41e.png)

In the LMS app:

https://hypothesis.instructure.com/courses/258/assignments/2032
![image](https://user-images.githubusercontent.com/22603275/135728716-39c48ed0-d116-4ac7-bb3d-aa4e15052361.png)

https://hypothesis.instructure.com/courses/258/assignments/2037
![image](https://user-images.githubusercontent.com/22603275/135728760-cf026171-620b-4b66-b568-840830f1f53c.png)

**To Reproduce**
1. Compare PDFs linked above to assignments linked above
2. Note the difference in selectable text in the indicated pages.

**Expected behavior**
If possible it would be good to have the LMS app reflect what users can currently select using their web browsers.

**Comment by mkdir-washington-edu** [comment]
Unsure, but maybe related to https://github.com/hypothesis/support/issues/226.

**Comment by mkdir-washington-edu** [comment]
From backlog meeting: In PDF.js - in FF dev tools you can find version of PDF.js. Get versions of FF and LMS app.

Firefox 94 uses PDF.js: 2.11.298
The LMS app uses PDF.js 2.11.249

**Comment by robertknight** [comment]
Testing the "Jess" PDF from the issue description with PDF.js v2.13.153 in Chrome:

<img width="615" alt="Jess 5 1 - PDFjs 2 13 153" src="https://user-images.githubusercontent.com/2458/154460330-955cd3dd-9f90-4c9f-ae6e-382772a56e0d.png">

In the cases where the selection doesn't cover the whole line, it still includes the correct text. However the position of text in the hidden text layer doesn't line up with the underlying content. This can be seen if changing the styling on the hidden text layer (here it has red text and a slightly-translucent white background):

<img width="553" alt="Jess text layer" src="https://user-images.githubusercontent.com/2458/154471947-2e7a22c1-dac6-47ad-a9bc-7f5f9b2dbc8a.png">

For contrast, here is the text layer from the version of PDF.js that we currently ship in Chrome:

<img width="562" alt="Jess text layer - PDFjs 2 11 - Chrome" src="https://user-images.githubusercontent.com/2458/154474050-5dc5e0aa-6743-486d-8870-c09320d4283b.png">

Testing in Firefox 97 with the same PDF.js version:

<img width="573" alt="Jess 5 1 - PDFjs 2 13 153 - Firefox" src="https://user-images.githubusercontent.com/2458/154470439-e57cc25e-0de3-4fcf-a3bb-350f3e9813c4.png">

Here is the text layer in Firefox:

<img width="571" alt="Jess text layer - Firefox" src="https://user-images.githubusercontent.com/2458/154472165-c5ec1f43-fc13-426c-8394-e72d2e38b23f.png">

To test in Firefox I ran a local HTTP server with `python3 -m http.server 8006` in the directory containing the PDF and accessed the PDF via http://localhost:8006/jess.pdf. This was necessary because the Firefox extension doesn't support accessing file:// URLs yet, at least not in development mode.

**Comment by robertknight** [comment]
It occurs to me it would be quite useful to add a hidden "visualize PDF text layer" feature to the client for debugging purposes. What would be the best way to enable it? Keyboard shortcut?

**Comment by robertknight** [comment]
Here is the example from the "Tatum" PDF in 2.13.153. The main issue is fixed, although there are now some lines where the text layer doesn't align correctly with the content underneath. Similar to the issue with the other PDF it does have all of the content, but the horizontal sizing doesn't match.

<img width="591" alt="Tatum text layer - PDFjs 2 13 153 - Chrome" src="https://user-images.githubusercontent.com/2458/154481910-26f98ea2-e1b2-4bc9-b29e-8e59e760ea23.png">

**Comment by robertknight** [comment]
I started looking at this in the browser extension. See https://github.com/hypothesis/browser-extension/pull/799. In the process I filed a client issue which we'll need to resolve first - https://github.com/hypothesis/client/issues/4331.

**Comment by robertknight** [comment]
I'm currently working on a PDF.js update here: https://github.com/hypothesis/browser-extension/pull/799.

**Comment by robertknight** [comment]
Open PRs that will close this:

https://github.com/hypothesis/browser-extension/pull/799
https://github.com/hypothesis/pdf.js-hypothes.is/pull/26
https://github.com/hypothesis/via/pull/720

**Comment by robertknight** [comment]
The new PDF.js version will bump the minimum supported browser version for the PDF viewer as described at https://github.com/mozilla/pdf.js/pull/14538 to versions that are ~3 years old, which conveniently aligns approximately with our typical cut-off point for older browsers:

- Chrome 73
- Firefox ESR
- Safari 12.1
