### ISSUE TITLE
LMS app fails to load U of Montana-Western OneDrive files

### ISSUE THREAD

**Issue by chrisdaaz** [hypothesis/product-backlog#1409]
## Bug report form

We're not sure if this is a bug with our proxy server, or a security configuration in the school's OneDrive account. We were able to meet with the instructional designer to get a demo of the error. We **are** able to access files from their OneDrive account using the "Anyone with the link" shared link, so this is not a simple user error for the file permissions. They replicated the problem across multiple courses and Microsoft accounts.

### Steps to reproduce

1. Open a new Hypothesis assignment in Moodle
2. Use the "Select PDF from OneDrive" option
3. Create the assignment
4. Attempt to view the assignment

### Expected behaviour

The LMS app loads the OneDrive file with the proxy server, alongside the client. 

### Actual behaviour

Error Message: Could Not Get Web Page

```
UpstreamServiceError: HTTPSConnectionPool(host='universityofmontanawestern-my.sharepoint.com', port=443): Max retries exceeded with url: /:b:/g/personal/leslie_johnson_umwestern_edu/Eb_FY9OuE2ZDoy1AxXvTqMABfBKgdbgmiXgkx3gzBkCPwA?download=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36f09dfc70>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

URL: https://lms-via.hypothes.is/route?via.client.ignoreOtherConfiguration=1&via.client.openSidebar=1&via.external_link_mode=new-tab&via.client.requestConfigFromFrame.origin=https%3A%2F%2Flms.hypothes.is&via.client.requestConfigFromFrame.ancestorLevel=2&via.blocked_for=lms&url=https%3A%2F%2Funiversityofmontanawestern-my.sharepoint.com%2F%3Ab%3A%2Fg%2Fpersonal%2Fleslie_johnson_umwestern_edu%2FEb_FY9OuE2ZDoy1AxXvTqMABfBKgdbgmiXgkx3gzBkCPwA%3Fdownload%3D1&via.sec=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJoIjoib3BJc21GQVJmc0p2SzY3N1lheEwiLCJleHAiOjE2Njk5MzIwMDB9.XGHK8_DEAhhNZiHaBM2MaAzBfGiXf7--I2YKsZChOuo

Third party URL: https://universityofmontanawestern-my.sharepoint.com/:b:/g/personal/leslie_johnson_umwestern_edu/Eb_FY9OuE2ZDoy1AxXvTqMABfBKgdbgmiXgkx3gzBkCPwA?download=1

```

![image](https://user-images.githubusercontent.com/24395592/205166478-93d8f648-817c-4cc8-a05a-67c9eea32a50.png)

### LMS

Moodle

### Additional details

After meeting with the instructional designer, we learned that the Microsoft administrator for the school quit earlier that day, having recently done some work related to security policies...

Links to tickets: 

- https://app.hubspot.com/contacts/6291320/ticket/1294759463
- https://app.hubspot.com/contacts/6291320/ticket/1298575489

**Comment by indigobravo** [comment]
### Overview

1. We can see from the error thrown that a connection can not be established because of a name resolution failure.

> Failed to establish a new connection: [Errno -2] Name does not resolve'

2. We can load the URL directly when bypassing all Hypothesis services

### Attempts to recreate the issue

The first thing I try and do when troubleshooting problems like these is break them into small chunks. We can then try and recreate them in a reliable environment. https://via.hypothes.is is a good starting point.

When I attempt to load the URL through Via I see the same error as you. 

```
https://universityofmontanawestern-my.sharepoint.com/:b:/g/personal/leslie_johnson_umwestern_edu/Eb_FY9OuE2ZDoy1AxXvTqMABfBKgdbgmiXgkx3gzBkCPwA?download=1
```

[`problem via link`](https://via.hypothes.is/https://universityofmontanawestern-my.sharepoint.com/:b:/g/personal/leslie_johnson_umwestern_edu/Eb_FY9OuE2ZDoy1AxXvTqMABfBKgdbgmiXgkx3gzBkCPwA?download=1)

This is great because it means the problem can be created outside of the customers environment.

### Tracing the cause of the resolution failure

The next step is to try and identify the cause of the resolution failure. Using the `host` command on my local computer I was able to run the following.

```
host -vvv universityofmontanawestern-my.sharepoint.com
```

Which returned these results...

```
host -vvv universityofmontanawestern-my.sharepoint.com
Trying "universityofmontanawestern-my.sharepoint.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13432
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;universityofmontanawestern-my.sharepoint.com. IN A

;; ANSWER SECTION:
universityofmontanawestern-my.sharepoint.com. 3600 IN CNAME universityofmontanawestern.sharepoint.com.
universityofmontanawestern.sharepoint.com. 2633	IN CNAME 4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com.
4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com. 60	IN CNAME 192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com.
192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com. 60 IN CNAME 192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net.
192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net. 300 IN	CNAME 192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net.
192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net. 240 IN CNAME dual-spo-0003.spo-msedge.net.
dual-spo-0003.spo-msedge.net. 240 IN	A	13.107.136.8
dual-spo-0003.spo-msedge.net. 240 IN	A	13.107.138.8

Received 402 bytes from 192.168.0.1#53 in 73 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35977
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	AAAA

;; ANSWER SECTION:
dual-spo-0003.spo-msedge.net. 204 IN	AAAA	2620:1ec:8f8::8
dual-spo-0003.spo-msedge.net. 204 IN	AAAA	2620:1ec:8fa::8

Received 102 bytes from 192.168.0.1#53 in 25 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63718
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	MX

;; AUTHORITY SECTION:
spo-msedge.net.		240	IN	SOA	ns1.spo-msedge.net. msnhst.microsoft.com. 2018012401 1800 900 2419200 240

Received 106 bytes from 192.168.0.1#53 in 22 ms
```

Again this is good information. We can see `my computer` can resolve the address. We now need to understand why Via can not.

From this point we are digging into areas that only the development team is going to be able to assist with.

### Attempt to resolve address directly on a Via server

Below is the output of the `host` command run directly on a server hosting the Via service. Successful queries have been returned from both AWS and Google DNS servers. Again this is all good information. We now 

#### AWS DNS

```
[ianburden@ip-10-1-2-217 ~]$ host -vvv universityofmontanawestern-my.sharepoint.com
Trying "universityofmontanawestern-my.sharepoint.com"
Trying "universityofmontanawestern-my.sharepoint.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4033
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;universityofmontanawestern-my.sharepoint.com. IN A

;; ANSWER SECTION:
universityofmontanawestern-my.sharepoint.com. 300 IN CNAME universityofmontanawestern.sharepoint.com.
universityofmontanawestern.sharepoint.com. 300 IN CNAME	4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com.
4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com. 59	IN CNAME 192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com.
192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com. 59 IN CNAME 192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net.
192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net. 299 IN	CNAME 192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net.
192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net. 240 IN CNAME dual-spo-0003.spo-msedge.net.
dual-spo-0003.spo-msedge.net. 79 IN	A	13.107.138.8
dual-spo-0003.spo-msedge.net. 79 IN	A	13.107.136.8

Received 402 bytes from 10.1.0.2#53 in 208 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33776
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	AAAA

;; ANSWER SECTION:
dual-spo-0003.spo-msedge.net. 158 IN	AAAA	2620:1ec:8fa::8
dual-spo-0003.spo-msedge.net. 158 IN	AAAA	2620:1ec:8f8::8

Received 102 bytes from 10.1.0.2#53 in 1 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16998
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	MX

;; AUTHORITY SECTION:
spo-msedge.net.		240	IN	SOA	ns1.spo-msedge.net. msnhst.microsoft.com. 2018012401 1800 900 2419200 240

Received 106 bytes from 10.1.0.2#53 in 3 ms
```

### Google DNS

```
[ianburden@ip-10-1-2-217 ~]$ host -vvv universityofmontanawestern-my.sharepoint.com 8.8.8.8
Trying "universityofmontanawestern-my.sharepoint.com"
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2504
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;universityofmontanawestern-my.sharepoint.com. IN A

;; ANSWER SECTION:
universityofmontanawestern-my.sharepoint.com. 3600 IN CNAME universityofmontanawestern.sharepoint.com.
universityofmontanawestern.sharepoint.com. 3600	IN CNAME 4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com.
4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com. 60	IN CNAME 192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com.
192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com. 60 IN CNAME 192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net.
192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net. 300 IN	CNAME 192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net.
192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net. 240 IN CNAME dual-spo-0003.spo-msedge.net.
dual-spo-0003.spo-msedge.net. 240 IN	A	13.107.136.8
dual-spo-0003.spo-msedge.net. 240 IN	A	13.107.138.8

Received 402 bytes from 8.8.8.8#53 in 173 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24410
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	AAAA

;; ANSWER SECTION:
dual-spo-0003.spo-msedge.net. 114 IN	AAAA	2620:1ec:8f8::8
dual-spo-0003.spo-msedge.net. 114 IN	AAAA	2620:1ec:8fa::8

Received 102 bytes from 8.8.8.8#53 in 9 ms
Trying "dual-spo-0003.spo-msedge.net"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11143
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dual-spo-0003.spo-msedge.net.	IN	MX

;; AUTHORITY SECTION:
spo-msedge.net.		240	IN	SOA	ns1.spo-msedge.net. msnhst.microsoft.com. 2018012401 1800 900 2419200 240

Received 106 bytes from 8.8.8.8#53 in 11 ms
```

**Comment by indigobravo** [comment]
### Output of my troubleshooting

The customers DNS record can be resolved outside of Via, but not when using it. This causes pages to fail to load and returns a HTTP 409.

**Comment by indigobravo** [comment]
### Update

We have been able to reproduce a resolution failure within the Docker container running the service. However, it is very selective. We have only seen a failure with:  `universityofmontanawestern-my.sharepoint.com.` Attempts to resolve the CNAME target work as expected: `universityofmontanawestern.sharepoint.com.` I can also resolve many other domain names without issue.

We have perform some exhaustive first efforts to trace the root cause, but as it stands have drawn a blank. I will accept the issue, but I need to have a think about next steps.

**Comment by indigobravo** [comment]
### Update 2

We are getting closer to the root cause. It would appear we are hitting a bug with Alpine Linux Docker containers in conjunction with the AWS managed DNS servers, maybe.... The issue here closely describes the problem we are hitting: https://github.com/docker/for-linux/issues/1219

Technically this is not a problem with Via or any of the Hypothesis applications. It is a problem outside of our control, but used by all Hypothesis applications.

#### Alpine Tests

I have run tests using two different versions of Alpine Linux.

- python:3.8.12-alpine3.13
- python:3.8.15-alpine3.17

1. Spun up a `python:3.8.x-alpine3.1x` container on an EC2 server in AWS.
2. Ran a ping inside the container and it returned the same `bad address` error we have been seeing in the Elastic Beanstalk managed Docker environments
3. Stopped the container and started it again. This time specifying the `--dns 8.8.8.8` parameter to Docker run.
4. Ran the same ping command inside the container and it worked successfully

In both Alpine Linux scenarios tested the same problem was seen.

#### Debian Tests

I wanted to test with a different distribution to see if the problem was still apparent. This time I tested with:

- debian:latest

The same tests were run, but no problems were seen! 

Step `2` listed above worked without issue on `debian:latest`.

##### Ping command

The following command has been used to test.

```
ping universityofmontanawestern-my.sharepoint.com.
```

**Comment by robertknight** [comment]
I have done some poking around in an Alpine Linux container that Ian set up on the management server. I think I can see what the problem is. Skip to the bottom of this comment for the conclusion.

**Investigation:**

I first checked that it was possible to switch between the AWS DNS server and Google's by editing `/etc/resolv.conf` within the container. When that file was [edited to use Google](https://wiki.alpinelinux.org/wiki/Configure_Networking#Configuring_DNS), I was able to ping `universityofmontanawestern-my.sharepoint.com`. When using the regular DNS server, it failed.

I then compared `nslookup universityofmontanawestern-my.sharepoint.com` results when using Google DNS vs AWS DNS. When using Google DNS, the response contained address information:

```
Name:   dual-spo-0003.spo-msedge.net
Address: 13.107.136.8
```

When using AWS DNS, these were missing.

The version of nslookup installed in Alpine is one that comes with BusyBox. I installed `bind-tools` in order to run `dig`, and noticed that its version of `nslookup` produced this output when using the AWS server:

```
/ # nslookup universityofmontanawestern-my.sharepoint.com
;; Truncated, retrying in TCP mode.
Server:         10.1.0.2
Address:        10.1.0.2#53

Non-authoritative answer:
universityofmontanawestern-my.sharepoint.com    canonical name = universityofmontanawestern.sharepoint.com.
universityofmontanawestern.sharepoint.com       canonical name = 4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com.
4318-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com     canonical name = 192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com.
192970-ipv4v6e.farm.dprodmgd105.aa-rt.sharepoint.com    canonical name = 192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net.
192970-ipv4v6e.farm.dprodmgd105.sharepointonline.com.akadns.net canonical name = 192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net.
192970-ipv4v6.farm.dprodmgd105.aa-rt.sharepoint.com.dual-spo-0003.spo-msedge.net        canonical name = dual-spo-0003.spo-msedge.net.
Name:   dual-spo-0003.spo-msedge.net
Address: 13.107.136.8
Name:   dual-spo-0003.spo-msedge.net
Address: 13.107.138.8
Name:   dual-spo-0003.spo-msedge.net
Address: 2620:1ec:8fa::8
Name:   dual-spo-0003.spo-msedge.net
Address: 2620:1ec:8f8::8
```

Note two things:

1. The "retrying in TCP mode" notice
2. The output includes IP addresses now

This led me to look into TCP retries during DNS lookups and whether there are any Alpine-specific issues. This led me to https://news.ycombinator.com/item?id=28312935. Note this comment:

> Musl fails to resolve that because it does not support “upgrade to TCP” and the response does not fit into single UDP packet so it gets truncated, so node fails to resolve the name.

**Conclusion:**

So here is what I think may be happening:

1. When using Amazon's DNS server, the response size is larger than when using Google's DNS server
2. The response size, for this particular domain, often exceeds the UDP threshold (512 bytes) when using Amazon's DNS server, requiring a TCP retry. I say "often" because I think did sometimes get a name lookup to succeed.
3. The Musl libc library that Alpine ships, which provides the OS's hostname lookup functions, does not implement this TCP retry behavior, so DNS resolution fails.
4. The problem cannot be reproduced directly on the EC2 machine or locally because all these systems are using a different C library which does support TCP during DNS lookup.

Relevant Stack Exchange post, with a bunch of useful links at the bottom https://serverfault.com/a/1073494

**Comment by robertknight** [comment]
Other links:

- https://christoph.luppri.ch/fixing-dns-resolution-for-ruby-on-alpine-linux

**Comment by robertknight** [comment]
Some general ideas for a solution:

1. Set up a proxy DNS server in the container (something like [dnsproxy](https://github.com/AdguardTeam/dnsproxy)), which can somehow avoid the UDP issue (can a proxy "flatten" the CNAME chain to shorten the response?)
2. Configure the container to use a non-AWS DNS server. I don't yet understand the differences between the AWS and Google DNS responses and so I don't know if there is a good reason why we would expect Google DNS responses to be smaller in general
3. Somehow make Python use a different DNS server than the system default, one which can handle TCP retries
4. Build Python against a C library which does support TCP retries (eg. glibc)
5. Replace Alpine with a different Linux distribution

For the options that involve filtering the DNS response somehow, it would help to understand what is actually in the response and whether any of it could be elided. I can look into this, but I'm not that knowledgeable about DNS in general, so someone else might be more efficient at it.

[This tweet](https://twitter.com/RichFelker/status/994629330130161664) from a Musl developer has the original rationale for not supporting TCP.

**Comment by robertknight** [comment]
It looks like the Musl developers are now in favor of adding TCP fallback. See this WIP patch for Musl that adds it: https://marc.info/?l=musl&m=166387822930279&w=2.

_Edit_: Patches have actually landed in musl git: https://git.musl-libc.org/cgit/musl/commit/?id=51d4669fb97782f6a66606da852b5afd49a08001. These have not yet shipped in a musl release yet though.

So when a new Alpine Linux version is released with musl >= 1.2.4, this will hopefully resolve the problem.

**Comment by robertknight** [comment]
So just to summarize the whole thread:

- A DNS query for `universityofmontanawestern-my.sharepoint.com` returns a long chain of CNAMEs before the A records
- When performing a DNS query for this host using Amazon's DNS over UDP, the response is long enough that it gets truncated (the "TC" flag is set in the response). The truncated response is missing the A records.
- Our web applications run in Alpine Linux Docker containers that use Musl libc as the system library for DNS resolution
- Musl libc does not support TCP fallbacks for DNS, or UDP responses >= 512 bytes (via EDNS), so the domain resolution fails. This leads to the "Failed to establish a new connection: [Errno -2] Name does not resolve" part of the initial error message in this thread

TCP fallbacks have being implemented in Musl's development branch, so when a new version is released, the best solution will be for us to simply upgrade the Alpine Linux version our apps use, to incorporate the new Musl release (>= 1.2.4).

In the meantime, all the workarounds we've thought of so far come with plenty of added complexity or risk. Just for the sake of enumerating them though, here are a few:

1. Ask the customer if they can find a way to shorten the CNAME chain (this might be a crazy ask). See https://github.com/hypothesis/product-backlog/issues/1409#issuecomment-1334945038 for the chain.
2. Override the DNS resolution used by the requests library, to use a custom resolver rather than the C standard library. https://stackoverflow.com/a/22614367 has some notes on where to patch. Something like [dnspython](https://www.dnspython.org) could be used, although I'd expect this to be somewhat slower than regular lookups, so it should be used purely as a fallback. This won't help with any DNS lookups done outside of requests, and it adds an extra dependency to the app.
3. Change the DNS server used by the container to eg. Google's, for queries that don't reference domains inside AWS. This might work because Google DNS's responses are shorter and don't get truncated, at least for this host. I don't yet understand why Google's DNS responses are shorter as they appear to contain the same CNAME chain. This isn't a general solution as a different host could have an even longer chain which would still get truncated, and there is potential to run into a new set of issues.
4. Build a custom version of musl from the latest git sources and use that in the container.
5. Change the container to use a glibc-based Linux distribution (as glibc's resolver does support TCP retries), at least temporarily until Musl gets support for TCP retries

**Comment by mkdir-washington-edu** [comment]
We've implemented solution #5 above. Ready to contact users. @chrisdaaz

**Comment by chrisdaaz** [comment]
Already done.

**Comment by robertknight** [comment]
A new version of musl-libc has been released which should resolve this issue when it gets integrated into Alpine Linux: https://www.openwall.com/lists/musl/2023/05/02/1. This means that we should be able to switch back to Alpine in future if we want to, though we haven't had any issues with the Debian-based container images.
