### ISSUE TITLE
Via handles srcset incorrectly. Issue fixed upstream but pywb is out of date.

### ISSUE THREAD

**Issue by chrisdaaz** [hypothesis/product-backlog#1414]
## Bug report form

_This was reported by a user of the LMS app, but was reproduced using Via. An instructor created an hypothesis-enabled reading but an image on the page would not load._

### Steps to reproduce

1. Notice how the first image loads fine [outside of the proxy server](https://mlpp.pressbooks.pub/modernworldhistory/front-matter/introduction/)
2. Notice how the first image does not load [within the proxy server](https://via.hypothes.is/https://mlpp.pressbooks.pub/modernworldhistory/front-matter/introduction/)

### Expected behaviour

The image should load:

![image](https://user-images.githubusercontent.com/24395592/211066613-68ded19b-608e-4a3e-bbf0-5928adead45a.png)

### Actual behaviour

Image does not load:

![image](https://user-images.githubusercontent.com/24395592/211066838-fa3175ac-0b4d-4ed7-b2d2-757b7d496d78.png)

### Browser/system information

Microsoft Edge on Windows 11.

### Additional details

It seems that the problem has to do with the file name of the image on the page: `Molino_neolítico_de_vaivén.jpg`

There are two instances of an accent character that get re-written by the proxy server: `Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg`

Here are the elements for more context:

This is the HTML outside of the proxy:

```html
<img class="size-full wp-image-306" src="https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén.jpg" alt="neolithic grindstone" width="1648" height="1000" srcset="https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén.jpg 1648w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-300x182.jpg 300w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-1024x621.jpg 1024w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-768x466.jpg 768w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-1536x932.jpg 1536w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-65x39.jpg 65w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-225x137.jpg 225w, https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén-350x212.jpg 350w">
```

This is the HTML as re-written by the proxy:

```html
<img class="size-full wp-image-306" src="https://viahtml.hypothes.is/proxy/im_/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg" alt="neolithic grindstone" width="1648" height="1000" srcset="https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg%201648w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-300x182.jpg%20300w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-1024x621.jpg%201024w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-768x466.jpg%20768w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-1536x932.jpg%201536w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-65x39.jpg%2065w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-225x137.jpg%20225w, https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n-350x212.jpg%20350w">
```

**Comment by chrisdaaz** [comment]
User who reported the issue: https://app.hubspot.com/contacts/6291320/contact/63414001

**Comment by robertknight** [comment]
https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén.jpg and https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg are the same URL, but the latter has been percent-encoded. The browser does this percent-encoding if needed when it makes the request, you just see the original in the HTML.

In a JavaScript console:

```js
encodeURI('https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neolítico_de_vaivén.jpg')
// Output: https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg 
```

I think the actual issue is very closely related however. The `srcset` attribute should contain strings like `{URL} {size}` however the space character between the URL and the size has been incorrectly percent-encoded as well. As a result when you visit the page through Via, the URL it tries to fetch, as reported in browser devtools is: https://viahtml.hypothes.is/proxy/https://mlpp.pressbooks.pub/app/uploads/sites/607/2019/06/Molino_neoli%CC%81tico_de_vaive%CC%81n.jpg%201648w. Note the "%201648w" at the end. That shouldn't be there. The other images in a similar position on the page have not had the space in their `srcset` strings encoded.

It looks like an upstream fix was applied in the middle of last year: https://github.com/webrecorder/pywb/commit/32e9020fd25469c28b2128ec7425b617a1f286fe. The version of pywb we have is v2.6.7 which is [out of date](https://pypi.org/project/pywb/). Any idea what is going on here @seanh?

Edit: Upstream bug report - https://github.com/webrecorder/pywb/pull/712

**Comment by robertknight** [comment]
Issue fixed by https://github.com/hypothesis/viahtml/pull/467.
