### ISSUE TITLE
Security vulnerability - V-002 Cookies Set Without Secure Flag - `Medium`

### ISSUE THREAD

**Issue by indigobravo** [hypothesis/product-backlog#1524]
### Overview

- Medium severity security vulnerability identified as part of the security review performed by Subgraph in August 2023
- Cookies Set Without Secure Flag

### Impacts

- https://github.com/hypothesis/h

### Description

The following is taken from the [Draft SubGraph 2023 Security Review](https://drive.google.com/drive/u/0/folders/1xEZWqRijdtpovKrlq8ENOQOsAm8kv2s6)

> #### Discussion
> Cookies set during the login process are not set with the Secure flag. This means that the browser may send them when making HTTP requests under some specific circumstances, with older browsers being more exposed. The Pyramid Python framework apparently does not set the secure flag by [default](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html), which may be the root cause of this issue.

<img width="597" alt="Screenshot 2023-08-28 at 08 32 28" src="https://github.com/hypothesis/product-backlog/assets/18003117/f3063881-baff-42c9-85bb-36ba468e4619">

> #### Impact Analysis
> This issue is mitigated by the following:
> - Modernbrowserswillnotsendcredentialsbydefaultunlesstheoriginatingrequestisfromapage that matches the origin
> - TheapplicationserversendsaStrict-Transport-Securityheaderwithamax-ageof6monthsand instructs the browser to include subdomains
> 
> This reduces the opportunities for exploitation, but does not eliminate them.

> #### Remediation Recommendations
> Add the secure flag to cookies that are set following a successful login. For applications that use the Pyramid framework, this is documented here:
> - [pyramid.session](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/session.html)

**Comment by robertknight** [comment]
Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies:

> A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol.

It should be fine to enable this flag in QA + production, since all requests go over HTTPS, but we'd want to disable it in development.

I did some testing locally setting the [`secure` flag](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/session.html) and it seems that Chrome and Firefox's "treat localhost as HTTPS" feature works for secure cookies too, so if you're only testing in those browsers you could set this flag all the time. However Safari does not support this behavior, and sometimes developers might have reasons to test h environments that are not hosted over HTTPS.

In production we always redirect HTTP traffic to HTTPS, so we could determine whether to set the `Secure` flag based on the protocol in the request. If the user connected to the site over HTTPS, we can assume that all other traffic which needs to include the cookie will also go over HTTPS too.
