### ISSUE TITLE
Generate report of deal to org mappings for revops to review prior to ORG ID / date range work

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1536]

**Comment by marcospri** [comment]
### Organizations that don't have a record in HubSpot

[Report in metabase ](https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJkYXRhYmFzZSI6NiwibmF0aXZlIjp7InF1ZXJ5Ijoic2VsZWN0IGNhc2UgcmVnaW9uIHdoZW4gJ2NhJyB0aGVuICdodHRwczovL2xtcy5jYS5oeXBvdGhlcy5pcy9hZG1pbi9vcmcvJyB8fCBzcGxpdF9wYXJ0KGxtcy5vcmdhbml6YXRpb25zLmlkLCAnLScsIDIpIGVsc2UgJ2h0dHBzOi8vbG1zLmh5cG90aGVzLmlzL2FkbWluL29yZy8nIHx8IHNwbGl0X3BhcnQobG1zLm9yZ2FuaXphdGlvbnMuaWQsICctJywgMikgZW5kLCAgbG1zLm9yZ2FuaXphdGlvbnMubmFtZSwgY3JlYXRlZFxuZnJvbSBsbXMub3JnYW5pemF0aW9uc1xubGVmdCBvdXRlciBqb2luIGh1YnNwb3QuY29tcGFuaWVzX3JhdyBvbiBsbXNfb3JnYW5pemF0aW9uX2lkID0gb3JnYW5pemF0aW9ucy5wdWJsaWNfaWRcbndoZXJlIFxuLS0gb25seSBlbmFibGVkIG9yZ3Ncbm9yZ2FuaXphdGlvbnMuZW5hYmxlZCA9IHRydWVcbi0tIE5vdCBzZXQgaW4gSFNcbmFuZCBsbXNfb3JnYW5pemF0aW9uX2lkIGlzIG51bGwiLCJ0ZW1wbGF0ZS10YWdzIjp7fX19LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)

Looking at this it looks like a lot of testing orgs so probably not that much ones to fix.



### Organization that map to multiple HB companies
[
Report in metabase ](https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJkYXRhYmFzZSI6NiwibmF0aXZlIjp7InF1ZXJ5Ijoic2VsZWN0IGNhc2UgcmVnaW9uIHdoZW4gJ2NhJyB0aGVuICdodHRwczovL2xtcy5jYS5oeXBvdGhlcy5pcy9hZG1pbi9vcmcvJyB8fCBzcGxpdF9wYXJ0KGxtcy5vcmdhbml6YXRpb25zLmlkLCAnLScsIDIpIGVsc2UgJ2h0dHBzOi8vbG1zLmh5cG90aGVzLmlzL2FkbWluL29yZy8nIHx8IHNwbGl0X3BhcnQobG1zLm9yZ2FuaXphdGlvbnMuaWQsICctJywgMikgZW5kLCBhcnJheV9hZ2coaHVic3BvdC5jb21wYW5pZXNfcmF3LmlkIHx8IGh1YnNwb3QuY29tcGFuaWVzX3Jhdy5uYW1lKSBcbmZyb20gbG1zLm9yZ2FuaXphdGlvbnNcbmxlZnQgb3V0ZXIgam9pbiBodWJzcG90LmNvbXBhbmllc19yYXcgb24gbG1zX29yZ2FuaXphdGlvbl9pZCA9IG9yZ2FuaXphdGlvbnMucHVibGljX2lkXG53aGVyZSBcbm9yZ2FuaXphdGlvbnMuZW5hYmxlZCA9IHRydWVcbmFuZCBsbXNfb3JnYW5pemF0aW9uX2lkIGlzIG5vdCBudWxsXG5ncm91cCBieSBsbXNfb3JnYW5pemF0aW9uX2lkLCBsbXMub3JnYW5pemF0aW9ucy5pZCwgbG1zLm9yZ2FuaXphdGlvbnMucmVnaW9uXG5oYXZpbmcgY291bnQoKikgPiAxXG5vcmRlciBieSBjb3VudChsbXNfb3JnYW5pemF0aW9uX2lkKSBkZXNjIiwidGVtcGxhdGUtdGFncyI6e319fSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1uX3dpZHRocyI6W251bGwsbnVsbCw4NzFdfX0=)


Not sure if based on the IDs in that report it's possible to access the records in HS.

---

Next steps:

## Organization that don't have a record in HubSpot

- [ ] Disable organization that should be disabled so the are not present in the report
- [ ] Group organizations from our test instances in one record and assign it.
- [ ] Get an empty report from this query
- [ ] Set up an alert for when new row appear here.


## Organization that map to multiple HB companies

- [x] Clarify if this is a legit situation. Can somehow multiple companies point to the same org.
- [x] If it's not create new organizations to split the data.
- [ ] Get an empty report from this query
- [ ] Set up an alert for when new row appear here.

**Comment by mkdir-washington-edu** [comment]
Notes from 2024-05-24

marcos questions/needs:
- should all of our organizations in the LMS app should have an ORG in HubSpot?
- - Almost all, but there are some ORGs that hold unused data (mistakes, etc., since Support can't delete ORGs or AIs)
- - Also, we need to evaluate if there are ever scenarios where, for Support, it makes sense to create Child ORGs, but Sales/RevOps does **not** want child orgs represented in HubSpot. I'm not sure this scenario occurs.

- is it ok if multiple organizations aggregate to the same company
- - yes

- is it possible that multiple HS companies will use the same ORG ID
- - if so this will mess up the calc, we'll generate an error support can see
- - we don't think this is desirable, so Support will work with rev ops to fix this.
- - there are 24 current examples of this, per Marcos' second query linked above.


How the reporting works:
- every night it'll find all the companies in HubSpot and match them by ORG ID, it will look at the dates on the deal, and it'll generate a usage report every month until the deal ends
- - if a HubSpot company doesn't have an ORG ID this won't happen

**Comment by mkdir-washington-edu** [comment]
@marcospri I've completed removing duplicate ORG IDs from HubSpot using your 2nd metabase report above.

**Comment by marcospri** [comment]
I made a couple of cards in the board out of this. I reckon we can close this one. Thanks @mkdir-washington-edu
