### ISSUE TITLE
Resolve issues with h client at hypothesis.vitalsource.com

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1547]
### Steps to reproduce
1. visit https://hypothesis.vitalsource.com directly, 
2. groups fail to load after logging into the client.
3. refresh the page after logging in, 
4. then groups are loaded properly.

### Expected behaviour
The client should launch normally and allow annotation of the VS text.

### Actual behaviour
Groups fail to load after log in without a refresh. See: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1721982579405939?thread_ts=1721982156.699809&cid=C4K6M7P5E

![CleanShot 2024-07-22 at 10 01 41@2x](https://github.com/user-attachments/assets/d7650237-cc90-4bea-ab14-a9cf05c92e1f)

### Browser/system information
Modern chrome

**Comment by dwhly** [comment]
@robertknight You mentioned before what the issue was but I've lost the thread, so I created this stub to track.

**Comment by robertknight** [comment]
https://hypothesis.vitalsource.com always configures the client assuming it is inside the LMS app. When you visit this directly, the client get stuck in a loading state because it is waiting for configuration from the LMS parent app that never arrives.

Ideally we would either have different domains for the different use cases (`hypothesis-lms.vitalsource.com` vs `hypothesis.vitalsource.com`) or pass some configuration in the launch URL which tells VitalSource whether to configure Hypothesis for use in the LMS or not.

**Comment by dwhly** [comment]
Is the fix on our end or theirs in terms of how they embed the client.

+1 650 274 7647 m
My calendar ( https://calendly.com/dwhly )

**Comment by robertknight** [comment]
> Is the fix on our end or theirs in terms of how they embed the client.

Changes will be needed on both sides, as we'd need to change from having just one configuration of the client within VitalSource (for use in the LMS), to somehow having two (for use inside and outside the LMS).

**Comment by mkdir-washington-edu** [comment]
@janraev 
Updated repro steps:
1. Open a VS book
2. Load Hypothesis via the chrome extension
3. See the Public group
4. Try to log in
5. Lose the group context

Try in other chomium browsers
Try with Bookmarklet, Via in other browsers

**Comment by mkdir-washington-edu** [comment]
Janrae's reproductions here: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1724164760282779
