### ISSUE TITLE
Write a new ADR about a new decision re client state storage

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#226]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

Write a new ADR about our current approach to state storage in the client. A previous decision was made to store state in the client in a way that isn't typical for an AngularJS app, and this was partially applied across the codebase: <https://github.com/hypothesis/product-backlog/issues/225>. What is our new decision about this way of storing state going to be? For example are we going to roll back this decision? O roll it forward?

**Comment by robertknight** [comment]
This is mostly covered by https://github.com/hypothesis/client/pull/687. We decided to keep the current approach but finish rolling it out to the rest of the code.

We haven't yet implemented any kind of wrapper around data from the API, which is something we could still consider.

I'm going to close this though since we have addressed the main issue here.
