### ISSUE TITLE
STORY: Alert on persistent high load

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#257]
### Context

We currently don't have any means of being alerted if one of our servers is experiencing continued high load. This would usually be a strong indicator that operator action is required, and so we should set up alerts to notify us if this occurs.

### Discussion

To avoid generating too many alerts, we probably want to alert on abnormally high load averaged over a sufficiently long timescale (10m?) that any alert isn't going to fire for a transient self-resolving load spike.

There are many possible components in our stack that could alert on this. Icinga would be the traditional place, but we don't currently have NRPE or similar configured, so this might be a fair bit of work. One other option is to alert from Grafana, where we already have the relevant metrics and averaging over any period is straightforward using Graphite's `summarize` or similar.

Some options:

1. Icinga and some kind of monitoring agent on hosts (NRPE, check_mk, and friends)
2. Alert from graphite metrics via Grafana alerting.
3. New Relic servers?

**Comment by nickstenning** [comment]
@sheetaluk and @fatbusinessman: could you find some time before our next backlog refinement session to update this card? Happy to answer any questions you have about this in Slack.

**Comment by sheetaluk** [comment]
We should start with configuring a Grafana alert. Once we decide where we are going from Skyliner, we could revisit this.

Icinga:
We are running our own icinga server.We will need to run a run a demon in our machines to collect the load, cpu info.
nrpe, check_mk are demons which will run on our servers and talk to the icinga installation and report the load of the cpu etc and then we can configure alerts to go to pager duty.
Note: Since we moved to skyliner, we don’t run icinga checks on app servers. 
Can we install an agent on our servers?
Will it work with a docker container?

Graphite metrics via grafana:
We already seem to have the data in graphite, it is likely that we only have the configure the alert. If it doesn’t work with the 5m load graph, the time series data from collectD can be used to create a new graph with the alert.
https://mon.hypothes.is/grafana/dashboard/db/h-system-overview-skyliner?panelId=9&fullscreen&edit&tab=alert

New Relic:
New Relic is a hosted service that we don’t need to worry about maintaining. It has a demon we can run on our servers which will send cpu, memory and n/w activity for free.
Can we install an agent on our servers?
Will it work with a docker container?

Things to consider with New Relic and Icinga:
Is it possible that the service can be given a docker image?
How much can we do on the ops side? Skyliner didn’t allow us to run anything we used collected.
Heroku gives us no access to system resources.
If we end up using amazon ecs, do we care about load?

**Comment by robertknight** [comment]
This came up during a [recent outage](https://docs.google.com/document/d/1Rsf4mKxMnEYhE7pteI2eSyuEhcKyQpRwtQTGHCKrfGs/edit#) where h maxed-out the number of instances allowed by the pre-configured autoscaling limits in its EB environment. All instances had >95% load for an extended period of time and we didn't notice until users reported problems.

**Comment by hmstepanek** [comment]
I think we have pretty good coverage of this in New Relic now. We've seen several alerts triggered from New Relic over the past couple months due to high loads. They general manifest as a deviation from baseline in the db time or deviation from baseline in the request time. As we experience a higher volume of traffic generally the CPU utilization increases to a point where things start slowing down and eventually an alert fires. I realize these are symptoms rather than the actual problem tho. We could add an alert that specifically tracks average requests and if it goes above a certain threshold or percentage we can fire an alert. This might serve us better as an early detection mechanism vs relying on things getting ugly first. However, something else to consider is we prob shouldn't be paging anyone unless the increased load has a degrading impact on the server so maybe relying on things like slow response times isn't so terrible.  With this in mind it might be useful to setup a non-pager alert to output info into the slack channel when there's an increase in request traffic without notifying on-call until it starts to impact performance.
