### ISSUE TITLE
Show highlights dependent on the sidebar open v. closed state for eLife

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#273]
### User Story
As a publisher, I would like to show highlights on my page when the Hypothesis sidebar is in a particular state, so that I can give my readers a clean reading experience.

### Background
After speaking with Nick D. at eLife, we will adjust the appearance of highlights on the eLife page, so that the eLife users can have a clean, uninterrupted reading experience (one of eLife's main UX priorities)

This work will likely need to be done in phases:
- The first is a simple on/off of highlights for when the sidebar is open/closed
- There are then a bit murkier situations to walk through that we will address after this work is done. So this ticket, is only dealing with the first iteration - turn the highlights off when sidebar is closed, turn them on when the sidebar is opened. 

### Acceptance Criteria
- The default behaviour of highlight visibility remains the same as it is now
- When a client configuration option is enabled, highlights will be hidden by default but will show when the sidebar is opened.
- When the client configuration option is enabled, the user can still adjust the appearance of the highlights through the eye button in the button bar. 
  - eye button configuration is only for a single page load and does not persist across pages
  - eye button will override initial site preference. Turning highlights on via the button will keep highlights visible until the user uses the button again to turn highlights and vice versa (for this page load, subsequent loads will take initial site preference)

The ticket has been given 5 points to provide some padding for feedback and discussion as it is implemented, both internally and with eLife.

**Comment by seanh** [comment]
As <https://github.com/hypothesis/client/pull/392> was merged this is now implemented (behind a config setting).

There's a known issue that, unlike what the acceptance criteria above ask for, opening the sidebar _always_ shows the annotations even if the user has clicked on the _Show Highlights_ button to turn them off. And closing the sidebar _always_ hides the annotations, even if the user has clicked on the _Show Highlights_ button to show them. Hopefully what's implemented will still be enough to demonstrate this as a prototype feature, though.

Here's a video of one of the issues with this behaviour previously raised (in <https://github.com/hypothesis/product-backlog/issues/259>):

1. With the sidebar already open
2. Select some text in order to annotate it. Since selecting text involves clicking on the page, and the sidebar automatically closes when you click on the page, the sidebar closes and all the highlights disappear.
3. Click on the annotate button. The sidebar opens again, and all the highlights appear again.

If the part of the page that's on screen has a lot of annotations then a large portion of the screen flashes white and then yellow again. The big yellow flashing on and off might be distracting / annoying / look broken:

![peek 2017-05-23 11-10](https://cloud.githubusercontent.com/assets/22498/26349819/02c7bedc-3fa9-11e7-97c7-26acb73aba90.gif)

I think another issue with this behaviour is that, when there are other annotations on screen, it potentially confuses the user as to what they're annotating:

1. With the sidebar closed, and therefore no highlights shown
2. Select some text and click annotate, the sidebar opens and all the highlights (not just the text you just selected) appear.

![peek 2017-05-23 11-20](https://cloud.githubusercontent.com/assets/22498/26350593/adcf7958-3fab-11e7-8634-81d8a4d189ed.gif)

When you create an annotation, the page shows you all these highlights, it would make sense if the highlight it was showing you was the highlight that you're currently annotating, and I think this could confuse the user into thinking it's annotating a different selection to what they actually selected. This is particularly bad when there are other annotations close to or overlapping the new one you're creating.
