### ISSUE TITLE
Link to share group annotations needs to include ability to join group

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#28]
**User story:** 
As a user making annotations in a group, I expect the ability to share the annotation with others, so that I can have community dialogue with the members that are in part of that group. 

**Problem:** 
When I share a link to an annotation made from a group, it should allow users to join that group. 

As I made annotations, I clicked the share button at the top of the sidebar, thinking that I could share the annotations with the team, and that they would see them. 
<img width="435" alt="screen shot 2016-10-27 at 1 20 05 pm" src="https://cloud.githubusercontent.com/assets/7463523/19779755/21d70b34-9c48-11e6-87de-d23c8615db1b.png">

Instead, I learned that I separately have to go to the groups profile page, and share the link to the group so that team members can join the group first, and then they can view the annotations. 
<img width="448" alt="screen shot 2016-10-27 at 1 20 17 pm" src="https://cloud.githubusercontent.com/assets/7463523/19779759/234e0152-9c48-11e6-91f9-1049554f189d.png">

This is a clumsy way of sharing annotations with team members. Users should only have to share one link to get other team members to annotate.

**Potential Solution:** 
Is there a way we can combine the two actions into one? So that by clicking on one share URL, we can both give access to the group, and the set of annotations for that webpage? Users that don't have a hypothesis account might still be able to view the annotations, but will have to log in to start annotating. 

This feature may be solved when we create public groups....
Writing this issue to track this.

**Comment by klemay** [comment]
When I am annotating in a group and I click the Share link in the sidebar, I see:

<img width="407" alt="Screen Shot 2021-01-04 at 5 26 41 PM" src="https://user-images.githubusercontent.com/12087705/103585965-1d70a980-4eb2-11eb-8964-fd091d821f89.png">

If someone who is not logged in to Hypothesis follows that link, they see: 

<img width="476" alt="Screen Shot 2021-01-04 at 5 41 43 PM" src="https://user-images.githubusercontent.com/12087705/103586928-23678a00-4eb4-11eb-8ebb-191a94c926fe.png">

If they ARE logged in but they are not a member of the group, they see:
<img width="407" alt="Screen Shot 2021-01-04 at 5 44 55 PM" src="https://user-images.githubusercontent.com/12087705/103587186-ac7ec100-4eb4-11eb-8010-8322034d5e38.png">


I do still have to invite people to my group before they can see the annotations, but I can now do that right from the sidebar instead of having to go to the group activity page:

<img width="275" alt="Screen Shot 2021-01-04 at 5 28 57 PM" src="https://user-images.githubusercontent.com/12087705/103586120-69bbe980-4eb2-11eb-8308-907cdefcdcee.png">

I think it's a _good_ thing that unauthorized users aren't automatically directed to join the group. Given this issue was created in 2016 and we haven't seen any activity on it since 2017, I propose that we close this.
