### ISSUE TITLE
SPIKE [4 days]: Research rewrite of Via

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#307]
### Background
- Via was built as a proxy service, so that users without the extension annotate pages on the web
- Via was built off a piece of technology called pywb, based off the  wayback machine and written by Ilya Kreymer, a former staff member of the Internet Archive.
- Via currently proxies all assets that are loaded on the page, no matter what they are (video, images, etc.). All of this traffic then goes through our service, causing major strain on our resources.
- Brand alignment, UX issues, engineering issues
- 37% of Hypothesis page events use Via, which is a significant enough amount of traffic to prioritize the rewrite work that needs to be done. 
- Recently we’ve been experiencing substantial operational issues with via as our traffic has grown.

**Via needs to be rewritten so that we can** 
- Stop the proxy of every asset on a page
- Significantly simplify the via codebase 
- Reduce the operational overhead

### Functional Requirements of a new Via Service
- [ ] The service should accept a publicly accessible URL as input (specified as a path in the URL), fetch that page and returns it to the user with a copy of the Hypothesis client embedded.
Images, CSS, videos, scripts and other resources referenced by the original page’s HTML should still load in the proxied page.
- [ ] Security: Forms on the page should be disabled to prevent users entering passwords or other private credentials that then pass through our service.
- [ ] Security: The service should not allow proxied pages to set or receive cookies, as these could then leak to other proxied pages. In other words, the user is always an anonymous visitor to the proxied page.
- [ ] The user should see an appropriate proxied page for their device. In other words, if they are visiting a site with desktop and mobile versions through Via on a mobile device, the proxied page should also be the mobile version. This means communicating the user’s original user agent header to the upstream service.
- [ ] For discussion: Anchor links to other pages on the same domain should be modified so that they also go through Via. This means that users will “stay in Via” when they navigate through multiple pages of a multi-page article.
- [ ] Direct links, where the client is triggered to focus on a particular annotation or set of annotations by a ‘#annotations’ fragment at the end of the URL, should work when visiting a page proxied by Via.
- [ ] For the Canvas/LTI app we need the new Via service to follow redirects like old Via does. This is because the download URLs for PDF files uploaded to things like Canvas, Google Drive, etc are usually `302` redirects to the URLs that actually download the PDFs 
- <del>For the Canvas/LTI app we need the new Via service to acts as a CORS proxy for us for PDF files uploaded to Canvas or Google Drive etc. This means the service needs to proxy PDF files, if given the publicly accessible URL of a PDF file, and it needs to add an `Access-Control-Allow-Origin` header into the PDF file responses. I don't think that CORS preflight request support is needed.</del> I don't think the LTI app's gonna need this anymore - **seanh**
- [ ] For the Canvas/LTI app: If you paste the URL of a PDF file into Via it detects that it's a PDF file and renders the file inside PDF.js with the Hypothesis client embedded. I think the LTI app is going to depend on this so will require the same from any new Via service. This feature is also of course just useful to anyone wanting to annotate a PDF in Via.

### End Result of Spike: 
- A rough plan of implementation that scopes out the complexity of the project, and approximates the potential # of developer hours needed for rewrite of via.

**Comment by dwhly** [comment]
Re the requirements:

- I don't think we need to rewrite anchor links so that users "stay in via".  From discussions, we know that whether publishers will be resistant to probably is related to just how much control and information they're losing through the process.  Since a primary goal of publishers is to keep people reading and clicking once they've arrived at a story, then rewriting anchor links is very much a negative-- since not only are they losing folks on the initial page, but on all subsequent clicks, whereas what we primarily care about is rendering the annotations on the initial page, since that's the page that the user was pointed to initially through a tweet or whatever.  On the other hand, from the classroom experience, there seems to be a suggestion that having via persist through links is preferable-- perhaps because the lesson pointed to the root of a set of materials that students will be navigating and annotate throughout.  Perhaps long term this is configurable.  For now, lets drop rewriting the anchor links.  We can add it back later if people complain.
- A question I suppose is whether pages still need to update via AJAX, websockets or other methods after the initial page load.  This probably turns on what exactly users would miss that's important-- but from previous discussions it would seem that these are things we can probably skip.

cc @judell @jeremydean

**Comment by dwhly** [comment]
A stretch goal for this spike might be to deploy a prototype from one of the several examples that folks have created in order to be able to test various questions about what needs to be rewritten in order to have a sufficiently complete user experience.

**Comment by chdorner** [comment]
Most of this is a summary of various messages over the last days in #eng-sensible-via on Slack.

We currently have a prototype of injecture (see the [`develop` branch](https://github.com/hypothesis/injecture/tree/develop)) running on our own infrastructure:

* https://qa-injecture.hypothes.is
* https://injecture.hypothes.is

Note: Since the new code I was writing was all extremely hacky, I've decided to not work in the `master` branch.

This prototype currently does:

* Inject the an [html template](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/inject.html) which sets the `base` tag, `canonical` url, and adds the `embed.js` script tag - only for the path section of the URL that starts with `http://` or `https://`. Note: It does this by reading the first 8 kilobytes and injects it based on a regex (see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/injector.go)).
* Removes certain headers before it makes the request to the origin (`CF-*`, `Authorization`, `Cookie`, etc. - see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L17-L36) and [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L101-L103)).
* Adds "Hypothesis-Via" at the end of the user agent header (see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L105-L110)).
* Removes certain headers in the response (`Set-Cookie` - see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L38-L40) and [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L114-L116)).
* Handles server-side redirects for the given request (see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/proxy.go#L118-L123)).

This seems to work fine for a decent amount of websites, although we did discover at least one drawback.

**Problems discovered with the current approach:**

It breaks HTTP websites.
This is due to HTTP websites tending to load assets over HTTP as well, and we're serving the initial page over `https`, so the browsers refuse to load these assets (JS and CSS for example. I've attempted a rather bad fix for this by implementing another endpoint (`/_/http...`) which just proxies through the page without rewriting anything. And then I parse and rewrite the initial HTML to replace `<link rel="stylesheet" href="https://injecture.hypothes.is/_/http://...>` (see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/rewrite.go#L59-L89)) and `<script src="https://injecture.hypothes.is/_/http://...">` (see [here](https://github.com/hypothesis/injecture/blob/b1447d77cdc9c103242f7530b2046a6d8448110a/injecture/rewrite.go#L91-L110)) tags.
This is obviously not going to work on all websites. The [BBC](http://www.bbc.com) (caution: bbc.com is different from bbc.co.uk) for example loads some Javascript files over HTTP with `requirejs`, which is not getting rewritten, and I would also really like to avoid having to do this.

There are two different solutions that will need to be investigated, both of them should remove the need to rewrite any HTML or any of the assets that are getting loaded:

* @seanh mentioned that we could just serve injecture over HTTP when the origin request is HTTP, and otherwise serve it over `https` (see [here](https://hypothes-is.slack.com/archives/C6RS34A3E/p1503652879000175) for the Slack discussion). This sounds like an easy and sensible solution to me, we also don't compromise any level of security since the non-proxied request would have been over HTTP anyway.
* @robertknight mentioned that we could make use of [Upgrade Insecure Requests](https://w3c.github.io/webappsec-upgrade-insecure-requests/) - which allows browsers to automatically try for the `https` version if it is supposed to load an HTTP one. This might work for a lot of cases, although this means that the server serving the requested asset does need to have SSL support which might or might not be the case.

**Further testing**

We have some ideas of other potential problems that need testing:

* Various CSP configurations need to be tested to ensure the browser will still load and execute assets (because the main HTML page is now served from another domain).
* Load testing - can it handle at least the amount that current via is getting?

**Note on load testing**

I've set up a traffic replaying daemon on via which currently duplicates the via traffic to injecture. This will be even more helpful once we have better monitoring set up, there are currently just the basic load/CPU/net io/disk usage data set up in its [Grafana dashboard](https://mon.hypothes.is/grafana/dashboard/db/injecture).

There's also a weird issue when replaying the traffic from an instance that sits behind CloudFlare to another instance that also sits in behind CloudFlare. So I've had to disable the CloudFront CDN (including its caching) for injecture (it's still on for via).

---

There's a list of our [top 100 annotated domains](https://docs.google.com/a/hypothes.is/spreadsheets/d/1supdiMUHsoKsaiGQdAPl4BHG03dBV-D4qwfUzDYqZ1Y) that we should test this against.

**Comment by dwhly** [comment]
Thanks for this writeup @chdorner.  

> we could just serve injecture over HTTP when the origin request is HTTP, and otherwise serve it over https

Seems sensible.

**Comment by seanh** [comment]
Great write up @chdorner

**Comment by seanh** [comment]
I've added a couple of "For the Canvas/LTI app" requirements to the task list above

**Comment by seanh** [comment]
>  For discussion: Anchor links to other pages on the same domain should be modified so that they also go through Via. This means that users will “stay in Via” when they navigate through multiple pages of a multi-page article.

My vote is we shouldn't do that (not even just for links to other pages on the same domain):

- It would mean that the proxy would have to scan the entire HTML file looking for anchor links to rewrite, which adds complexity to the proxy and slowness to its performance. As soon as we start moving in this direction (the proxy scanning the web pages that it proxies and modifying them) we start to move towards the issues that we have with Via: complex code that's buggy and breaks some web pages etc.

- Rewriting anchor links won't actually mean that the user stays in Via whenever they navigate, because there are many ways to navigate a page besides anchor links (form submission, JavaScript...). So the UX you'll actually get is that sometimes it stays in Via but sometimes it doesn't, for reasons unclear to the user. The kind of thing we'd have to do to try to get it to actually stay in Via all the time, is probably ill-advised.

- Even sticking to just anchor links, staying in Via sometimes (when link is to same domain) but not other times (when link is to other domain) is gonna look like "sometimes it works and sometimes not, and unclear why" to the user.

I do understand that things like paging through multi-page articles busting out of Via are a pain, though. I'd recommend we live with it.
