### ISSUE TITLE
Allow publishers to register display names for user accounts

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#323]
### Problem you are trying to address with this feature

The Hypothesis sidebar currently displays usernames to identify the creator of an annotation or reply. These usernames have a limited length, character set restrictions and they have to be unique. Due to these restrictions, they are often not meaningful identifiers for readers of an annotated document (eg. the person's real-world name).

As a publisher, I would like to associate annotations with identifiers, eg. real names taken from an ORCID profile, that my readers will recognise.

### Your solution

Hypothesis accounts currently have a "Display name" field but in order to solve the above need, we will need to:

1. Enable publishers to associate a display name with an account, most importantly at the time when the account is registered.
2. Provide the display name to the client, probably as part of the data for each annotation
3. Render the data in the client

Since display names are not unique in Hypothesis, we may as an extension need to add some kind of visual disambiguation in the client if multiple users have the same name. This could take the form of showing the username as well in this case, or the ORCID ID.

**Comment by robertknight** [comment]
eLife devs have stated their intention to stick to a 50-char limit when generating display names. This seems like a reasonable limit to start with that we could enforce in any API for registering display names and leverage when designing the display of these names in the sidebar.

**Comment by chdorner** [comment]
As discussed and summarised [here](https://gist.github.com/robertknight/8a8e85e90c2bb34e4934544e0f61fbc4), the necessary steps are:

* [x] Render `"user_info": {"display_name": "John Doe"}` in annotation JSON response (important: eager load for `/api/search` endpoint).
* [x] Add support for setting display name in `POST /api/users`
* [x] Add `PATCH /api/users/{username}` endpoint, allowing a third-party publisher authclient to change the email address and display name of a user, but no other fields.
* [ ] Show display name instead of username in sidebar annotation cards.
* [x] BONUS (not really): Fix 500 error when validation fails in `POST /api/users`
