### ISSUE TITLE
Signing up inside the popup window is weird

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#336]
The sign up flow is still the old one, which is designed for a full-sized page. It redirects to the front page inside the popup window after:

![peek 2017-07-13 18-08](https://user-images.githubusercontent.com/22498/28178450-683a88ba-67f6-11e7-8d14-5deda971342d.gif)

**Comment by seanh** [comment]
By the way @robertknight you can also see in the above gif that I need to scroll within the popup window to use the forms. Initial window size is too short. Should I open a separate issue for that?

**Comment by dwhly** [comment]
@dawariley ^

**Comment by robertknight** [comment]
Perhaps the simplest solution would be to open the "Sign up" form in a new window. Then the flow would be something like this:

1. User clicks "Sign up" in authorize form
2. User populates form that appears in new window and clicks "Sign up"
3. User sees checks email and clicks activation link
4. User returns to "Log in" popup and signs in

In future we could use federated login to eliminate most of these steps for a user without an account:

1. User clicks "Log in" button in client
2. User clicks "Sign in with {Google, GitHub, whatever}" in popup window
3. User clicks "Authorize" button in {Google, GitHub etc.}'s authorization dialog
4. Client's auth dialog disappears and user is logged in, ready to start annotating

**Comment by robertknight** [comment]
It turns out that triggering opening of the "Sign up" form in a new window using `target="_blank"` doesn't reliably work in at least Safari because the directive is ignored if the popup window is above a certain size.

In Chrome and Firefox, the Sign Up window is opened as a new tab in the parent window, which is good. In Firefox however things can get confusing because clicking the "Log in" link in the client if the popup is already open does nothing. In Chrome the existing window is brought to the foreground, which is helpful behaviour.

For these reasons, I think it would probably be better to keep the "Sign up" flow happening inside the popup window.

Some other ideas:

- Have the "Sign up" dialog redirect back to the login screen and show the "Please activate your account" flash message
- Make the "Sign up" dialog show a spinner and wait for the user to activate their account. After they do, the login flow should continue as normal
- Just remove the "Sign up" link from the log in popup. The user will have to click the "Sign up" link in the client instead.

**Comment by robertknight** [comment]
The login form design has been changed in the context of the OAuth popup to make the "Sign up" link open in a separate window. See https://github.com/hypothesis/h/pull/4637
