### ISSUE TITLE
Popup window should open over parent window

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#337]
Just a suggestion: it looks like the popup window is programmed to open in the centre of the screen (I think) but this may not be over or anywhere near the parent window to which it belongs:

![peek 2017-07-13 18-12](https://user-images.githubusercontent.com/22498/28178623-0d17e602-67f7-11e7-9161-17110803f9a2.gif)

Is it possible to make the popup window appear over the middle of the parent window instead?

**Comment by robertknight** [comment]
> Just a suggestion: it looks like the popup window is programmed to open in the centre of the screen (I think)

This is correct. The reason for this is that 1) it was simple to implement in the sidebar app alone, 2) I thought it would work fine most of the time.

> Is it possible to make the popup window appear over the middle of the parent window instead?

Yes, but I think it would require the sidebar app to get some help from the code that runs in the host page. The reason is that the sidebar app is on a different origin from the parent window, and therefore it can only read very limited information from `window.parent`. This excludes information about the position and size of the parent window. Therefore in order to get that information and position the popup in the centre of the parent window, I think the sidebar would need to make an RPC call to the host page code (in `src/annotator`) which would reply with the geometry of the parent window.

**Comment by robertknight** [comment]
I took off the "bug" label because this is working as designed. The more important question is whether the "as designed" behaviour is reasonable most of the time, or whether it is significant enough that we should implement the suggested behaviour instead.

**Comment by robertknight** [comment]
I'm going to defer this for now given that I think it will be quite fiddly to fix and I think most users are unlikely to notice on the assumption that browser windows usually occupy most of the screen.
