### ISSUE TITLE
Import Disqus comments as page notes and replies

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#349]
### Original comment

Problem: eLife would like to migrate the Disqus comments they have to a single user annotation in Hypothesis. One of the main issues with this is that we don't allow the setting of timestamps on annotations. ~~This ticket simply addresses the need to add timestamps to be set through the API.~~

### Updated by seanh 20th Nov 2017

I just read through this entire discussion below (up to [20th Nov 2017](https://github.com/hypothesis/product-backlog/issues/349#issuecomment-345676712)) to get up to speed with it. Here's my summary of what I think we've agreed to do:

* We will write a command line command for importing a W3C Web Annotation Model-compatible JSON file into Hypothesis as page notes and replies.
* eLife will be providing us with the Disqus comments that they want us to import, in the required W3C JSON file format
* So we're not actually importing Disqus comments as such, we're importing a limited subset of JSON-formatted W3C web annotations, a format to which eLife will be exporting their Disqus comments for us
* Presumably this'll be a subcommand added to the `hypothesis` command, and on production a developer will [run it manually in Jenkins](https://github.com/hypothesis/playbook/blob/master/docs/running-tasks-on-qa-and-prod.md).
* Note that production and QA share the same database, so it won't be possible to do the import on QA first and then test the results
* It won't be an HTTP API
* It won't support importing annotations, only page notes and replies to page notes (and replies to replies to page notes)
* Replies to replies _will_ be supported
* It's not going to support the entire Web Annotation Model, only the minimum that we need to do the eLife import. (For example: no annotations.) In future it can be extended.
* We'll add a new `imported_id` column to the annotation table in the database, for recording the unique ID of the comment or reply in Disqus. This can be used to know when we're re-importing the same comment twice (so we can either skip it or update the already-imported object), and is also used by replies to say what comment or reply they're replying to. This is separate from our usual internal `id` field on annotations in our DB. It's for importer purposes only.
* All of the imported annotations will go into one group (the eLife publisher group), for example by adding the group ID as a required command-line argument

The JSON formats that we're expecting for page notes and replies are as in [David's comment](https://github.com/hypothesis/product-backlog/issues/349#issuecomment-327140022) (also see [Christof's comment](https://github.com/hypothesis/product-backlog/issues/349#issuecomment-321825439) for how the various fields in this file should be mapped to fields in h's database):

Page note (notice `"motivation": "commenting"` and `"target": "https://xkcd.com/1831/"`): 

```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "disqus:123456789",
    "type": "Annotation",
    "created": "...",
    "modified": "...",
    "creator": "acct:username@authority",
    "motivation": "commenting",
    "body": [
      {
        "type": "TextualBody",
        "value": "...",
        "format": "text/markdown"
      },
      {
        "type": "TextualBody",
        "value": "...",
        "purpose": "tagging"
      }
    ],
    "target": "https://xkcd.com/1831/"
}
```

Reply (notice `"motivation": "replying"` and `"target": "disqus:123456789"`):

```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "disqus:234567890",
    "type": "Annotation",
    "created": "...",
    "modified": "...",
    "creator": "acct:username@authority",
    "motivation": "replying",
    "body": [
      {
        "type": "TextualBody",
        "value": "...",
        "format": "text/markdown"
      },
      {
        "type": "TextualBody",
        "value": "...",
        "purpose": "tagging"
      }
    ],
    "target": "disqus:123456789"
}
```

**Comment by ajpeddakotla** [comment]
- We need to determine if we'll allow this for eLife, or for everyone. 
- Reminder that imported annotations will affect metrics measurements for annotations created.

**Comment by chdorner** [comment]
I've had a chat with @fatbusinessman and @robertknight yesterday and we came up with the following:

* We should add a new field `timestamp` to the annotation
* This new `timestamp` field can be set through the API (and edited)
* The only validation is that the `timestamp` field isn't allowed to be too far into the future (clock skew)
* If the `timestamp` field is not set through the API when creating an annotation, we will initialize it with the current timestamp
* We will change most uses of `created` or `updated` to use the new `timestamp` field, see list below for details.

Open questions:

* Do we want to update the `timestamp` whenever an annotation gets updated? Similar to how the `updated` field works. If we want to allow a client to manage the timestamp, then this might not be desirable. But this also means that the logic of the timestamp that we show in the UI changes.
* How do we fit this new timestamp into the jsonld annotation model? (see [spec here](https://www.w3.org/TR/2017/REC-annotation-model-20170223/#lifecycle-information))
* How do we change the reply email notification? (check the templates [here](https://github.com/hypothesis/h/blob/master/h/templates/emails/reply_notification.txt.jinja2) and [here](https://github.com/hypothesis/h/blob/master/h/templates/emails/reply_notification.html.jinja2))

Timestamp usage of `created` or `updated` and what changes:

* Client:
  * Uses `created` to fetch annotations & replies from the API in batches of 200 - __stays the same__
  * Sorting replies by `created` - __change to `timestamp`__
  * Sorting annotations by date using `updated` - __change to `timestamp`__
  * Displaying an annotation’s associated time to the user on the annotation card uses `updated` - __change to `timestamp`__
  * Filtering annotations using a “since:<time>” query in the filter bar uses `updated` - __change to `timestamp`__
* Backend / API:
  * `AnnotationJSONLDPresenter` - __see open question__
  * Reply email notification - __see open question__
  * RSS item `pubDate` uses `created` (see [here](https://github.com/hypothesis/h/blob/ca5a35d76086a91f60cddae258b6e8d8cab3a2a4/h/feeds/rss.py#L45)) - __change to `timestamp`__
  * Atom item `published` uses `created` (see [here](https://github.com/hypothesis/h/blob/ca5a35d76086a91f60cddae258b6e8d8cab3a2a4/h/feeds/atom.py#L33)) - __change to `timestamp`__
  * Atom item `updated` uses `updated` column (see [here](https://github.com/hypothesis/h/blob/ca5a35d76086a91f60cddae258b6e8d8cab3a2a4/h/feeds/atom.py#L32)) - __change to `timestamp` depending on if we update the field automatically for edits?__
  * Activity Pages bucketing uses `updated` for calculating cutoffs (see [here](https://github.com/hypothesis/h/blob/ca5a35d76086a91f60cddae258b6e8d8cab3a2a4/h/activity/bucketing.py#L126)) - __change to `timestamp` depending on if we update the field automatically for edits?__
  * Activity Pages bucketing uses `updated` for generating bucketing windows (see [here](https://github.com/hypothesis/h/blob/ca5a35d76086a91f60cddae258b6e8d8cab3a2a4/h/activity/bucketing.py#L156-L160)) - __change to `timestamp` depending on if we update the field automatically for edits?__
  * Default ordering of ElasticSearch requests use `updated` - __change to `timestamp`__
  * Activity Pages annotation card template shows `updated` - __change to `timestamp`__

**Comment by dhwthompson** [comment]
Hmm. This feels like it’s getting messy. Particularly given that the W3C spec only allows for `created` and `updated` timestamps.

I think the model that makes the most sense in my head is to treat this timestamp as a way to override `created`, having nothing to do with `updated` at all. This new field then becomes “when the author **says** the annotation was created”, as opposed to our own internal “this is when the annotation resource appeared on our servers”. We could potentially use the former in our API, and the latter for our own metrics, Elasticsearch pagination, feeds and so forth.

Having those two separate concepts may also mean we can have the user-defined creation timestamp default to `NULL`, so we’re not throwing away information about whether the client explicitly provided an override.

Whether this means there’s a better name than `timestamp`, I’m not sure.

This would make the answers:

> Do we want to update the timestamp whenever an annotation gets updated?

No.

> How do we fit this new timestamp into the jsonld annotation model?

I think we would use the new author-definable field in place of `created`, when it’s present.

> How do we change the reply email notification? (check the templates here and here)

It _probably_ makes the most sense to report the actual creation time, as we’re less likely to confuse someone by saying “hey, so-and-so replied to your annotation before you wrote it”.

**Comment by chdorner** [comment]
Okay, @segdeha, @robertknight, and I have been talking about this again yesterday and came to the conclusion that this is not a viable strategy for now. We don't want API clients to be able to write to the `created` and `updated` timestamps because we don't want to give that amount of power to API clients.
The solution of adding a third timestamp that the client can set sounds great in theory, but it opens a whole lot of other questions that need answering. Most importantly it would change certain fundamental functionality of the service that we don't want to change as a side effect of this.

So we've come back to the idea of having an import functionality based on a text file of some sorts containing all the necessary information in a well-defined structure.
It just so happens that there is a [W3C web annotation spec](https://www.w3.org/TR/annotation-model/#introduction).

So the current working plan is to implement a simple import functionality that takes a JSON file containing an array with annotations in the [Web Annotation Model](https://www.w3.org/TR/annotation-model/#introduction) format.
Since we're mostly doing this to allow elife to import their comments from their old comment system we can cut some corners.

Here's the proposed mapping of Web Annotation Model fields to our annotation model/database table:

```
{
    "@context": "http://www.w3.org/ns/anno.jsonld", # dismiss
    "id": "...", # external id for potentially allowing re-imports, maps to field `imported_id` (will become an extra field)
    "type": "Annotation", # dismiss
    "created": "...", # maps to field `created`
    "modified": "...", # maps to field `updated`
    "creator": "acct:username@authority", # maps to fields `username` and `authority`
    "body": [
      {
        "type": "TextualBody",
        "value": "...",
        "format": "text/markdown"
      }, # maps to field `text`
      {
        "type": "TextualBody",
        "value": "...",
        "purpose": "tagging"
      } # maps to field `tags` (does support multiple)
    ],
    "target": [
        "source": "...", # maps to field `target_uri`
    ], # only one allowed - no need for supporting selectors yet, elife just wants to import page notes
}
```

Some of the aforementioned shortcuts that allow us to get this done in a quicker way:

* We will get a well-formed JSON file from elife (I still have to confirm with Nathan)
* We will provide a CLI tool that can import said JSON-formatted files
* The annotation data is imported manually by one of our developers (it should be some sort of admin/group admin tool in the future).
* We don't need to support any annotation target selectors at the moment since elife just wants to import what we call page notes (which are annotations without selectors), in the future, we need to map Web Annotation Model selectors to our selectors, which is a bit more work.

Can I get a quick thumbs-up/-down from @ajpeddakotla, @segdeha, @robertknight, and @fatbusinessman?

**Comment by robertknight** [comment]
@chdorner - So to recap, the main decision here is to sidestep the issue of how to give publishers the power to set arbitrary `updated` and `created` timestamps on annotations by having someone at Hypothesis use an admin-only tool to run the import.

This seems fine as a starting point. We should check whether we are likely to need to do continual imports or additional batches after Hypothesis-powered annotation goes live on eLife.

**Comment by chdorner** [comment]
> We should check whether we are likely to need to do continual imports or additional batches after Hypothesis-powered annotation goes live on eLife.

I will check this with Nathan next week, I still want them to give us their comment ids, at least then we could enable re-import functionality later down the road.

**Comment by chdorner** [comment]
This is on pause for now until Nathan is back from his vacation, which should be around the 28th.

**Comment by dhwthompson** [comment]
Having caught up with Nathan, there's one new issue that's cropped up: the existing comments are threaded, and it would be useful to preserve that threading.

Disqus supports replies to replies (possibly to an arbitrary depth). I don't know what depth of replies eLife has in their existing comments, but it seems likely we're going to need to accommodate more than two levels (top-level comments and replies).

As far as I can tell from reading through the [W3C annotation model][w3model], the intended way to model replies is to treat them as annotations on their parents. To that end, I'd suggest we use the following model.

[w3model]: https://www.w3.org/TR/annotation-model

For the parent:

```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "disqus:123456789",
    "type": "Annotation",
    "created": "...",
    "modified": "...",
    "creator": "acct:username@authority",
    "motivation": "commenting",
    "body": [
      {
        "type": "TextualBody",
        "value": "...",
        "format": "text/markdown"
      },
      {
        "type": "TextualBody",
        "value": "...",
        "purpose": "tagging"
      }
    ],
    "target": "https://xkcd.com/1831/"
}
```

For the reply:

```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "disqus:234567890",
    "type": "Annotation",
    "created": "...",
    "modified": "...",
    "creator": "acct:username@authority",
    "motivation": "replying",
    "body": [
      {
        "type": "TextualBody",
        "value": "...",
        "format": "text/markdown"
      },
      {
        "type": "TextualBody",
        "value": "...",
        "purpose": "tagging"
      }
    ],
    "target": "disqus:123456789"
}
```

We can either use the `motivation` field to distinguish between top-level comments and replies, or we can base it on the `target` URI.

So long as we only want to support page-level annotations and replies (both of which can identify their target by URI alone), I think [the standard says we're fine using bare URIs][w3relationship].

[w3relationship]: https://www.w3.org/TR/annotation-model/#dfn-relationship

Another option I considered was the ability to use multiple values for `target`, which would let us have the annotation target both the document it's annotating and any parent comments, but that would mean more work to generate the JSON, and just as much work for us to validate that the set of `target`s was self-consistent.

**Additional note**: the choice of `disqus:123456789` in the `id` field is just an example. So long as the value is a globally unique URI of some form, we’re not bothered how it gets generated.

**Comment by seanh** [comment]
Couple comments:

1. Christof said that certain fields from the JSON file that can only contain one value, e.g. `"type": "Annotation"`, should be dismissed by the importer. I agree that these fields shouldn't get imported and end up in the DB anywhere. But I think we should _validate_ them all, so if `"type"` is anything other than `"Annotation"` we reject the entire annotation.

2. I know we've decided to write a CLI tool only, so this is just a comment for future direction, but if we one day want to add this import functionality to the HTTP API I'd consider whether writing a _separate_ import API would be better, rather than extending the normal annotation create API to allow setting of created and updated times.

**Comment by seanh** [comment]
I've updated the issue description at the top of the page with a summary of what we're intending to do, based on the discussion in the comments above.

**Comment by seanh** [comment]
DB migration we need to run after the import is finished: https://github.com/hypothesis/h/pull/4698

**Comment by dhwthompson** [comment]
As this currently stands, we’ve successfully run a version of this migration against comments in a test environment. I’ve added placeholders for further work we’re expecting to crop up, but for now we’ve done everything that’s available for us to do on this, and we’ve shown that our current solution is feasible.

Given that, I’m marking this as done and leaving the future placeholders. We’ll add migrations for further imports as and when they come to us.
