### ISSUE TITLE
Create groups admin interface that allows Hypothesis team members to create and invite members to groups

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#370]
### Background
Currently the only way to create "publisher only" groups is for a Hypothesis developer to create the group on the backend. 

We want to open this ability up to all Hypothesis team members so that H team members will be able to: 

- [ ] Choose group type they wish to create (publisher, open, public)
- [ ] Create group (group title, group icon)
- [ ] Invite group members (add emails for new group members)

**Does not require design work to start implementation, but needs a design review before shipping**

**Comment by gobengo** [comment]
This is next up for me. Code is here for now: https://github.com/hypothesis/h/compare/master...gobengo:groups

Will tag this issue once there's a real PR

**Comment by gobengo** [comment]
@ajpeddakotla I think my linked PR implements most of the checkmarks in this issue, with the exception of choosing a 'group icon'. I don't believe the current schema stores an icon, nor can I see where it would be necessary.

The group creation form I made lets you pick the group title, description, type, and authority. @ajpeddakotla will you clarify the requiremenst around icon? Or if that was just a placeholder and it's not really required, edit the issue here. Thanks.

**Comment by seanh** [comment]
Oops, I created a separate user story for admin page for open groups: <https://github.com/hypothesis/product-backlog/issues/421>. I'm gonna close this one
