### ISSUE TITLE
Deploy AJ's app to https://lms.hypothes.is and https://qa-lms.hypothes.is when we get it from them

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#384]
The app: https://github.com/hypothesis/lms

WIP pull request documenting the steps for deploying an app: https://github.com/hypothesis/playbook/pull/154/files?diff=unified

**Comment by seanh** [comment]
AFAICT so far, I think the environment variables that we'll need to set are:

* `JWT_SECRET`
* `VIA_URL` (app needs to be fixed to use this instead of hard-coding)
* `GOOGLE_CLIENT_ID`
* `GOOGLE_DEVELOPER_KEY`
* `GOOGLE_APP_ID`
* `DATABASE_URL`
* `LMS_SECRET` (code needs to be fixed to add support for reading this environment variable)
* `HASHED_PW` (code needs to be fixed to add support for reading this environment variable)
* `SALT` (code needs to be fixed to add support for reading this environment variable)
* `USERNAME` (code needs to be fixed to add support for reading this environment variable)
* `SENTRY_DSN`
* `ENV` (`prod` or `qa`, not sure if we have to set this manually)
* `NEW_RELIC_APP_NAME`
* `NEW_RELIC_ENVIRONMENT`
* `NEW_RELIC_LICENSE_KEY`
* `STATSD_HOST` (`statsd.svc.hypothes.is`)
* `STATSD_PREFIX` (`prod.lms` or `qa.lms`)
* `GRAPHITE_HOST` (`graphite.svc.hypothes.is`)

**Comment by seanh** [comment]
There's already [a bunch of database migration scripts](https://github.com/hypothesis/lms/tree/master/lms/migrations/versions). We'll need to stamp the prod and qa dbs with the latest version. We won't need to run pre-existing migrations on qa or prod.

**Comment by seanh** [comment]
Looks like [`lms/util/get_password_hash.py`](https://github.com/hypothesis/lms/blob/f60e162b185a29462f359afa72d1cc1fee80269e/lms/util/get_password_hash.py#L20) can also be run as a command-line script to generate a hashed password and salt, presumably for use in the `hashed_pw` setting (which needs to become the `HASHED_PW` env var).

(In fact I think running from the command-line may be the _only_ thing this module is used for.)

**Comment by dhwthompson** [comment]
As summarised by @seanh, here are the remaining tasks to get this all set up in QA:

- [x] Setup a subdomain in CloudFlare
- [x] Create a Google OAuth client and API key in some Google account (_which_ account remains undecided), and use them to set the app's three `GOOGLE_*` environment variables
- [x] Generate values for and set the `USERNAME`, `HASHED_PW` and `SALT` env vars and set those
- [x] Create a Sentry project and set `SENTRY_DSN`, for Python crash reporting
- [x] Create a New Relic project
- [x] Add a `Jenkinsfile-tasks` file to the lms app's git repo, plus any related setup on Jenkins, so that we can run database migrations on the QA and production DBs
- [ ] <del>Create a Jenkins bot to report `qa-lms` app deploys where the external developers can see them</del> (Moved to own note on sprint board)

In prod:

- [x] Deploy to prod environment with minimum env vars to get the app running
- [x] Setup a subdomain in CloudFlare
- [x] Create a Google OAuth client and API key in some Google account (_which_ account remains undecided), and use them to set the app's three `GOOGLE_*` environment variables
- [x] Generate values for and set the `USERNAME`, `HASHED_PW` and `SALT` env vars and set those
- [x] Set `SENTRY_DSN`, for Python crash reporting
- [x] Create a New Relic project
- [ ] <del>Create graphs in Grafana</del> Moved to [own card](https://github.com/hypothesis/product-backlog/issues/398)
- [ ] <del>Create a Jenkins bot to report `lms` app deploys where the external developers can see them</del>  (Moved to own note on sprint board)

**Comment by seanh** [comment]
I'll add a separate card for writing up the docs for this, too
