### ISSUE TITLE
Grouping groups by publisher

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#418]
As a publisher I want my open groups to be **grouped under my publisher name** in the groups menu (so that...?)

Done when:

- [ ] A Hypothesis developer can specify a named publisher when creating an open
      group
- [ ] Publisher is a required field. All open groups must belong to a publisher.
- [ ] Multiple open groups can belong to the same publisher.
- [ ] Any previously existing open groups in the production DB have been added to
      a publisher by a database migration (or just delete the preexisting
      groups if you can)
- [ ] The publisher's open groups appear grouped under the publisher's name in
      the groups menu
- [ ] Hypothesis groups appear grouped under the Hypothesis name in the groups
      menu
- [ ] The publisher's groups appear above the Hypothesis ones

<br />

**Mockups:**

@seanh Current working groups control designs can be found here: https://docs.google.com/presentation/d/1ESiIotb91xJnUj9v6M2R2qW0o7akT1MbwsIMPjab6Ho/edit#slide=id.g2576362aea_1_2. Caveat: the mocks don't factor in the 'non grouped' or community groups as they prioritise the v1 implementation as fleshed out before Christmas. 

<br />
<br />

**Notes on the mockups:** 

- The following mockups show grouping groups by organisation(parents): Publisher and Hypothesis.
- There is no world logo against the publisher group - it is always the publisher logo. If this feature won't be implemented in this card, let either use a different placeholder (grey square) or no logo, including the world icon is really confusing,
- Private groups only occur under Hypothes.is, see 'Neuro Club' below.

<br />
<br />

**Groups Control Overview mockup**
This mockup illustrates the main features of the group control.

![screen shot 2018-02-22 at 06 16 20](https://user-images.githubusercontent.com/5212631/36535476-ce17ec30-1797-11e8-8fa9-d091b4d65708.png)

<br />
<br />

**Grouping Groups by Parent: Publisher and Hypothesis**

![screen shot 2018-02-22 at 05 51 03](https://user-images.githubusercontent.com/5212631/36534352-509ec1f0-1794-11e8-9a89-59fb22a8026f.png)

<br />

![screen shot 2018-02-22 at 05 51 51](https://user-images.githubusercontent.com/5212631/36534376-6475ecc6-1794-11e8-801e-cb35dfb52bc0.png)

<br />

![screen shot 2018-02-22 at 05 52 56](https://user-images.githubusercontent.com/5212631/36534434-8b14ee72-1794-11e8-972e-8d7eaee41876.png)

<br />

![screen shot 2018-02-22 at 06 02 11](https://user-images.githubusercontent.com/5212631/36534863-dcd9685e-1795-11e8-9458-401d404d84d8.png)

*Additional styling specs* - font-sizing and spacing are included in a separate comment below as final UI styling might need to be added to a separate card. @seanh can you confirm this is out or in scope for this card.

*Out of scope:*
* Inclusion of the login/username against the publisher domain @seanh can you confirm this is out of scope for v1.
* No publisher icons yet
* Small request from Dawa on publisher logo: 
Can you please use a placeholder e.g grey square rather than the world icon, or no logo against the group in the top bar of the sidebar. the previous mockup had the world icon which is in the current implementation in production and this is misleading.

**Comment by lyzadanger** [comment]
Just ruminating here about relationships implied by this feature...

>  Publisher is a required field. All open groups must belong to a publisher.

I'm curious about this requirement and its origin; wherefore the enforced relationship? Does that come from a user need or a data design perspective?

This seems like it would create a curious non-normalized constraint—_some_ groups (the ones we call "open") would have a required "publisher" relationship, while others (private groups, restricted groups?) would not.

Requiring a publisher relationship for all open groups also raises the question of how this would work in the future when all users are able to create open groups (not just rarified partners and publishers). Would a user have to belong to a publisher (somehow? Implying an additional publisher-user relationship) to be able to create an open group?

I have some other questions, too, like whether private groups can belong to a publisher or not.

HUGE CRAZY IDEA DISCLAIMER HERE ALERT ALERT — Please no one panic and think I'm about to rewrite our product!

I'm going to throw out something crazy and probably something we should bury under 20 feet of mud and rocks, but...is it possible that a _publisher_ is a type of _group_? I know, I know, ridiculous, but here's why that idea floats into my head:

* This requirement is slightly suggesting the notion of _hierarchy_, versus a flat set of relationships
* We have already overloaded what _group_ means in how we're twisting them to pack in the notion of _type_. Sometimes we treat groups like a set of user relationships and permissions, sometimes we treat them as containers or folders.
* Recall that a _type_ of group is an imaginary concept that is really a grouping of permissions and access restrictions (I separate those two because of the _scoping_ element of open-type groups). Technically, a _publisher_ could be a group with `writableBy` of `None` (i.e. you can't put annotations in the group; though even this is up for debate; maybe some publishers would want their top-level group writeable) and `readableBy` = `authority` (or `world` or `members`...really the sky's the limit, sorta). Really we could tweak the permissions as we or the users please.
* In this crazy crazy world, the task would not be to create a new entity but to create an optional parent-child relationship between groups. If we wanted, child groups could inherit things from their parents—things like icons, for example—or override them. 
* This would also give publishers the ability to have nested collections of groups.

OK, I'm done with my loose cannon thoughts :boom: for the day. Thanks!

**Comment by dawachan** [comment]
Just to clarify:

"This seems like it would create a curious non-normalized constraint—some groups (the ones we call "open") would have a required "publisher" relationship, while others (private groups, restricted groups?) would not."

Open **and** Restricted groups are nested under publishers because team members have determined that these 2 types of group would add the most value to publishers (@heatherstaines can provide more details behind this requirement) They are 'owned' by publishers and closely associated to publishers, content wise, creation (in a future state) and moderation wise, so it makes sense to nest them under the publisher's 'domain'. 

Private groups are created by individuals for individuals, not associated with publishers in this present schema therefore it is suggested they live outside of the publisher/domain control.

A flat list quickly becomes unmanageable (as we can see from the current first pass iteration of groups) it is better to organise things according to a hierarchies that enable the creation of a mental model that will help users find/retrieve content and provide affordance for content (annotation) creation. This grouping of parent/child might not be publisher centric in the future - we could introduce other 'parents' into the mix e.g institutions/departments etc. but grouping by association is a helpful construct and the association we have at present is:
publisher -> open group *and* restricted groups, for schools this might be teacher name -> class for example.

**Comment by dwhly** [comment]
> Publisher is a required field. All open groups must belong to a publisher.

> I'm curious about this requirement and its origin; wherefore the enforced relationship? Does that come from a user need or a data design perspective?

I'm curious about it too!  :)

@seanh May simply be saying that in an early version of implementation it might simplify some things in order to enforce this as a requirement— or that the team’s commitment was to implement the publisher flavor first and the community flavor second.

Certainly there are diverse examples of groups we imagine in the very near future which there's no requirement or need to have a publisher, for instance community groups (think: a subreddit over the whole web). 

> HUGE CRAZY IDEA DISCLAIMER

Love your crazy idea.  :)

I have another suggestion to throw in the mix: 

That we skip creating a database container or structure for publishers (for now).  

Consider this:

What if instead of a data structure, the page itself simply asserted the collection (group of groups).

After all a "publisher group” is just a named cluster which says “Whoever who has authority over this page asserts that these groups are relevant here.  If you like the content, it probably matters to you to pay attention to these recommendations.”

It’s important that such a cluster is established by someone who clearly has the proper authority to do so, i.e. we don’t want random “authoritative” clusters showing up on pages where there is no proper relationship.  (e.g. over the NY Times, gov.uk, etc).

Of course we could enforce this by requiring H (or the annotation service's) staff to have to manually create all such clusters and in the process verify their proper authority (not very scalable)— or we could simply listen for metadata in the page to tell us.  If they can get the metadata in the page, then by definition they have the authority.

Maybe something like:

PublisherGroupName=“Bio Pub”
PublisherGroupIcon="http://biopub.org/icon.png”  (when/if needed)
PublisherGroup="/groups/ljrSLDJ"  Service=“hypothes.is”
PublisherGroup="/groups/ld3s9KL" Service=“hypothes.is”
PublisherGroup="/groups/ClimateFeedback" Service="hypothes.is”

When we see this assertion in the page, we create the cluster of groups.

Perhaps instead of “PublisherGroup", we could simply call them “PageGroup” or “PageCluster” or “GroupCluster” to reduce confusion about whether the page owner need be a formal publisher or not.  Of course they're not actually _groups_ in the other way we use the term, and we probably shouldn't confuse them. (We can always market them under whatever name we want.)

Possible advantages of this:

We skip having to figure out the best data structure for now.  We can always create one later if we find that there is a clear need, and maybe we’d know more then which would help inform us how to design it.

It becomes easy for anyone to implement this over their page, for any reason.  Bloggers, etc.  (We don't need to worry about not being able to charge folks.  We can have clear terms of service that for commercial use you need to contract with us / the annotation service provider.) 

Groups show in the interface in the order they're listed.  The first one is the default.

Named PublisherGroups can be a mix of groups that the publisher has created themselves, and groups that they didn’t create.  We already know that specific publishers want to declare groups created by other orgs to be featured on their site.

Groups only show up on the pages that include the metadata.  And if different pages on a site want to show different groups, they can.

Groups still should (optionally) stipulate in our data structure which domain(s) they’re restricted to.  When group creators do that, it prevents their being used on sites other than the domains listed (the publisher).

Groups themselves can individually still have icons perhaps, stored in the db entry for the group, so that we can show them on their activity pages and perhaps in the pull down.  Only the icon for the cluster (if desired/implemented) itself need be referenced in the metadata.

**Comment by dwhly** [comment]
Addressing @dawariley's comments:

> Open and Restricted groups are nested under publishers because team members have determined that these 2 types of group would add the most value to publishers (@heatherstaines can provide more details behind this requirement) They are 'owned' by publishers and closely associated to publishers, content wise, creation (in a future state) and moderation wise, so it makes sense to nest them under the publisher's 'domain'.

> Private groups are created by individuals for individuals, not associated with publishers in this present schema therefore it is suggested they live outside of the publisher/domain control.

Not sure I agree.

I don't think any group should be required to have a publisher relationship.  Plenty of open and restricted groups will be created (in the future) separately from publishers. 

And, conversely, any group _should be able to be_ grouped under a publisher's clustering-- including private groups.  There's no reason to exclude, for instance, a publisher from creating a private group, inviting some folks to it, and having it conveniently show up under their cluster at the top of the page.  Perhaps for internal discussions, copy editing or whatever, it's simply convenient for their staff to have it handy at the top of the page, even though no one else can see it.  (My suggestion above would already accommodate that).

> A flat list quickly becomes unmanageable (as we can see from the current first pass iteration of groups) it is better to organise things according to a hierarchies that enable the creation of a mental model that will help users find/retrieve content and provide affordance for content (annotation) creation. 

+1  

I do believe strongly that the notion of a cluster of groups organized under a heading associated with the page owner is a key idea.

**Comment by dawachan** [comment]
Styling specs for the grouping groups by their parent:
@seanh to confirm whether this is in or out of scope and needs to be moved to a separate card, although it would be nice to keep it all together.

_Font sizes_
![screen shot 2018-02-22 at 06 20 18](https://user-images.githubusercontent.com/5212631/36535653-64ca5aa0-1798-11e8-8944-3e2692c1b51b.png)

<br />

_Spacing_
![screen shot 2018-02-22 at 06 20 09](https://user-images.githubusercontent.com/5212631/36535633-58b2886e-1798-11e8-90ac-18a8e3fb8c16.png)

**Comment by dawachan** [comment]
Responding to @dwhly:

"I don't think any group should be required to have a publisher relationship. Plenty of open and restricted groups will be created (in the future) separately from publishers."

Just to confirm what we are saying is that there can be instances where there are no parents or parents besides publishers - see my comment about Teachers -> Classes. My question would be how best to group the open/restricted/private groups separate from publishers - I am thinking that they will appear under the Hypothesis 'parent' or we're thinking of a list of groups outside of a parent entirely and that this list will appear at the top for to have it 'handy at the top of the page'.

Note: this is a new requirement so it was not factored into the earlier mocks, I will need to revise mocks once we agree upon the rules and benefits to the user of having a list of groups with no grouping/parent. e.g the community use case. It might make sense to deliver the mocks against the v2 iteration of groups (community and non grouped groups) functionality @ajpeddakotla.  

My main question is: when a publisher creates a group that they wish to appear outside of their grouping (as represented in the group control), how will they specify this and besides having handy access to the groups at the top, are their other rules that will determine their inclusion. I'm thinking recency (last accessed) could be one helpful rule for users to have easy access to a group they recently or frequently annotated in. 

This would be partially automated (driven by user behaviour) and also publishers and organisations can manually assign groups to this 'non grouped' prioritised list of groups. This sounds like V2 groups control features.

Crazy idea warning: Would it be beneficial to users to have multiple non grouped clusters e.g at the top of the group scope menu we have a 'high priority' list of groups, can these 'high priority' groups appear in 2 places in the the control e.g. at the top because a user recently visited or annotated in a group, or a publisher designates them to show up at the top? Willthey also show up under the publisher/organisation/parent grouping? 

Perhaps there is a secondary non grouped list of groups which don't have a parent and aren't a priority and don't appear under a publisher/organisation/parent grouping e.g Other groups which is towards the bottom. 

So approximate order in the control:

Priority non grouped groups:
       - group A
        - group B
        - group C

Parent 1 (e.g Publisher):
      - group C (in 2 places)
      - group D 

Parent 2 (e.g Hypothesis):
      - group E
      - group F 

Secondary non grouped groups (Other groups):
      - group G
      - group H
      - group I
      - group J

**Comment by dawachan** [comment]
Just to note: the work we did before the holidays did not factor in community groups as we decided to focus on the v1 implementation of groups for the publisher use case.

**Comment by seanh** [comment]
Don't mess up our cards peeps, we're tryina sprint here!

I think the discussion and designs on this card got a little off topic. This card is supposed to be a small-as-possible slice: simply adding the publisher names above the groups in the groups menu. And developers need a clean space where we can have a focused discussion with each other about how we're going to implement everything behind the scenes that's necessary to make that happen.

I've created [a fresh copy of this card](https://github.com/hypothesis/product-backlog/issues/497) so that we can have a clean slate, and I'll now close this card.

I've also copied [Lyza's comment](https://github.com/hypothesis/product-backlog/issues/418#issuecomment-367464075) onto the [current sprint spike card for discussing implementation of grouping groups by publisher](https://github.com/hypothesis/product-backlog/issues/481) so we can discuss it there.

Since we (developers) won't be needing this card anymore, I suppose off topic discussion can continue on it!

**Comment by seanh** [comment]
> I suppose off topic discussion can continue on it!

Or these kind of broader discussions might fit better in a google doc somewhere?

**Comment by segdeha** [comment]
Or even on Slack. What I'd like to see is that we use the cards to capture _decisions_ that come from conversations that happen wherever because Slack is terrible for that. What it is good for, even designed for, is for hashing out ideas. Let's do that work on Slack and use GitHub as more of a record, if that works for folks.
