### ISSUE TITLE
User is being asked to login every time they open a page

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#45]
**Reported by user:** 
I am logged in WHEN I am on https://hypothes.is/ and can use the tool ON THAT PAGE. When I go to any other page I am asked to log in again (even when the other page is still open and still logged in) and I CAN NOT highlight until I log in. Kind of a catch 22. I am logged in AND I'm not logged in.

Can't log in on Firefox
Session is invalid. Please try again.
Changed password successfully.
Session is invalid. Please try again.

Can't use the tool. Like a hammer without a handle.

Version: 0.47.0
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:49.0) Gecko/20100101 
Firefox/49.0
URL:
PDF fingerprint: -
Username: KeithDJohnson
Date: 15 Nov 2016 15:09:04 -0500

https://hypothesis.zendesk.com/agent/tickets/778
---
I'm not able to reproduce this, but am adding it as an issue for tracking purposes.

**Comment by lidel** [comment]
I've just stumbled upon `Session is invalid. Please try again.` error while using the bookmarklet under Firefox 55.  

FYI it may not be caused by any extension: 
**Firefox itself gives user an option to opt-out from 3rd party cookies.**

I was able to to make it work by going to _Preferences_ → _Privacy_ and  changing 3rd party cookie policy from "Never":

>   ![2017-08-21-000333_845x496_scrot](https://user-images.githubusercontent.com/157609/29498855-7cecc35a-8604-11e7-948a-d2831e8d4bbf.png)

to "From visited":

> ![2017-08-21-000416_407x42_scrot](https://user-images.githubusercontent.com/157609/29498858-8414452c-8604-11e7-880e-9f4d1fcd6986.png)

A better alternative is to add `https://hypothes.is` to the whitelist under `Exceptions...` button:

> ![2017-08-21-001728_686x305_scrot](https://user-images.githubusercontent.com/157609/29498935-2b34af8a-8606-11e7-89da-a9b09d70c3b0.png)


Hope this helps. (same for https://github.com/hypothesis/h/issues/2742 and https://github.com/hypothesis/vision/issues/211)

**Comment by robertknight** [comment]
The OAuth implementation should fix this. Depending on the browser and privacy extensions being used it may or may not enable the browser to maintain the login between sessions, depending on whether the sidebar iframe can access localStorage or not. However, in cases where the login cannot be persisted between pages, the user will at least be able to login with a single click and it should put an end to the "Session is invalid" errors.

**Comment by robertknight** [comment]
Hypothesis (as of v1.39) now detects when the browser is preventing it from storing cookies and falls back to using OAuth rather than cookies for authentication in this context. You may find that you need to click the "Log in" button each time the client loads, but as long as you are signed in to the website you won't have to re-enter your login details each time.

**Comment by tim-hub** [comment]
Firefox 75.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/2884320/79735352-ac6b7080-82e7-11ea-9db2-cb0ca1de4173.png">

this setting solved the problem

**Comment by krillin666** [comment]
Hey, 

I had this problem and none of the solutions provided here worked. 
I managed to get it working by setting: `privacy.firstparty.isolate = true` to **false**. Now hypothesis works in firefox **but** in detriment of better security and privacy.

If anyone knows how to keep First Party Isolation (FPI) on but still having Hypothes.is working please document it here !

Thank you so much for all the work done.

**Comment by robertknight** [comment]
> I managed to get it working by setting: privacy.firstparty.isolate = true to false. Now hypothesis works in firefox but in detriment of better security and privacy.
> If anyone knows how to keep First Party Isolation (FPI) on but still having Hypothes.is working please document it here !

What you'd need here is probably a way to whitelist the https://hypothes.is domain so that it is not subject to First Party Isolation. From a quick reading of https://bugzilla.mozilla.org/show_bug.cgi?id=1556212 it seems that is not currently possible. [This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1556212#c52) suggests that it may not get resolved any time soon either as FPI is apparently not a supported feature in the stable release of Firefox.

**Comment by izzues** [comment]
Hey, thanks for the great work!

I'm still having this issue, and I don't think this is solved yet, at least not properly. Correct me if I'm wrong, but it seems the extension communicates with the Hypothes.is server using an injected script, and this context is what causes all the issues above.

As far as I know, the proper way to architect WebExtensions that need to communicate with a server is to instead send messages from the injected script to a background script and vice-versa, and the background script is able to communicate with the server without such restrictions (of course the server URL must first be allowed in `manifest.json`).

**Comment by robertknight** [comment]
> I'm still having this issue, and I don't think this is solved yet, at least not properly.

The specific issue that was originally reported was solved, as we no longer use cookies at all for authentication. Since then however some browsers have introduced new tracking protection measures which are intended to target ads, but also affect Hypothesis in a similar way. Safari and Firefox for example segregate data storage in iframes depending on the top-level site.

> Correct me if I'm wrong, but it seems the extension communicates with the Hypothes.is server using an injected script, and this context is what causes all the issues above.

Usually communication with the server is not the problem. The problem is storing the credentials after login completes. The client stores these credentials in local storage. If local storage is partitioned based on the top-level site in the tab, then you'll find that you need to log in to Hypothesis (or at least click the log-in button, but not re-enter credentials) for each different domain you annotate. We could fix this by storing the credentials in extension storage rather than local storage. We've just not gotten around to it.

**Comment by krillin666** [comment]
I experience exactly this on Firerfox

**Comment by ht55ght55** [comment]
> > I'm still having this issue, and I don't think this is solved yet, at least not properly.
> 
> The specific issue that was originally reported was solved, as we no longer use cookies at all for authentication. Since then however some browsers have introduced new tracking protection measures which are intended to target ads, but also affect Hypothesis in a similar way. Safari and Firefox for example segregate data storage in iframes depending on the top-level site.
> 
> > Correct me if I'm wrong, but it seems the extension communicates with the Hypothes.is server using an injected script, and this context is what causes all the issues above.
> 
> Usually communication with the server is not the problem. The problem is storing the credentials after login completes. The client stores these credentials in local storage. If local storage is partitioned based on the top-level site in the tab, then you'll find that you need to log in to Hypothesis (or at least click the log-in button, but not re-enter credentials) for each different domain you annotate. We could fix this by storing the credentials in extension storage rather than local storage. We've just not gotten around to it.

Thank you for explaining this. 

Looking forward to a fix or workaround!

Thanks for all the work so far.  Great utility!

**Comment by mpr1255** [comment]
FWIW for anyone seeing this in 202...4. The problem seems to persist with Brave, and adding the exceptions for the browser extension, via.hypothesis, and hypothesis didn't seem to work (https://web.hypothes.is/help/how-long-do-i-remain-logged-in-to-hypothesis/). I ultimately had to disable blocking of third party cookies entirely in order to get hypothes.is Brave plugin working across sites.

**Comment by serranomorante** [comment]
> FWIW for anyone seeing this in 202...4. The problem seems to persist with Brave, and adding the exceptions for the browser extension, via.hypothesis, and hypothesis didn't seem to work (https://web.hypothes.is/help/how-long-do-i-remain-logged-in-to-hypothesis/). I ultimately had to disable blocking of third party cookies entirely in order to get hypothes.is Brave plugin working across sites. 

Yep, I can confirm this. I have to click "Login" after every Brave restart.
