### ISSUE TITLE
Non-existant group search returns all annotations rather than error message

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#462]
### Steps to reproduce
1. In the search filter, search for: group: DoesNotExist (while logged in)
2. You will see the following:
<img width="1242" alt="searchfornonexistantgroupissue" src="https://user-images.githubusercontent.com/30059933/35891441-30509546-0b59-11e8-9c22-34b4156ef0a1.png">

### Expected behaviour
Should indicate that the group does not exist.

### Actual behaviour
Page shows all annotations as if the filter was successful.

When a search is not successful the user should be notified or at least nothing should be returned. Here this is what I would call a "silent failure" where it looks like that group exists and the search was successful. The user would be blissfully unaware that that was not the case.

### Browser/system information
Chrome, MacOS

**Comment by hmstepanek** [comment]
There appears to be a test for the current behavior in tests/h/views/activity_test.py:    
`def test_search_just_returns_search_result_if_group_does_not_exist`

**Comment by hmstepanek** [comment]
This behavior also occurs when searching for a user that doesn't exist.

**Comment by judell** [comment]
This is a longstanding problem, it's been reported before (by me) but I can't find where, doesn't matter, it would be great to clean this up as part of the ES upgrade.

**Comment by dawachan** [comment]
### Current Behaviour

_Note: Current behaviour is for non existent user returns "**No annotations match your search.**"_
* this is for a keyword only, non faceted search works different  - see below.

![non existent user](https://user-images.githubusercontent.com/5212631/39425408-38131cd0-4c73-11e8-8e4b-15a49aec73fa.png)

_User faceted search returns **all matching annotations** that don't match the keyword!_ 

![screen shot 2018-04-30 at 12 39 58](https://user-images.githubusercontent.com/5212631/39425541-df2ebfce-4c73-11e8-8004-57d30ebdafac.png)


This is confusing. I think all searches, faceted or non faceted should have the same behaviour - "No annotations match your search."

**Comment by dawachan** [comment]
### Proposal for user: and group: faceted searches

For a faceted search on user: group: or keyword (non faceted) to keep consistency and reflect the accuracy of the result set by returning 'No annotations match your search' message. No need to mention group or user in the message because the search box keeps the scope user: and group: s well as the query that returned a null result set, thus giving users a clear affordance and opportunity to refine the query and re-submit.

If we want to come up with a more meaningful UX for null result set or suggest content we can - but the suggested fix for this is to **keep the existing design pattern for a keyword null result search and extend this to the user: and group: facet search**.

**_Mock: Non existent user - No annotations found message._**
![revised - search user - no annotations](https://user-images.githubusercontent.com/5212631/39426048-265a12d4-4c76-11e8-81b4-e1a4940234fb.png)

**_Mock: Non existent group - No annotations found message._**
![revised - search group not found - no annotations](https://user-images.githubusercontent.com/5212631/39426066-40a70318-4c76-11e8-904e-6ea83da96695.png)
