### ISSUE TITLE
SPIKE: Research how we can group "groups" by publishers

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#481]
To be filled out by Arti

Issues tagged in this Spike: <del>https://github.com/hypothesis/product-backlog/issues/418</del> https://github.com/hypothesis/product-backlog/issues/497

**Comment by seanh** [comment]
I'm copying over @lyzadanger 's [comment from another card](https://github.com/hypothesis/product-backlog/issues/418#issuecomment-367464075) so we can discuss it here:

* * *

Just ruminating here about relationships implied by this feature...

>  Publisher is a required field. All open groups must belong to a publisher.

I'm curious about this requirement and its origin; wherefore the enforced relationship? Does that come from a user need or a data design perspective?

This seems like it would create a curious non-normalized constraint—_some_ groups (the ones we call "open") would have a required "publisher" relationship, while others (private groups, restricted groups?) would not.

Requiring a publisher relationship for all open groups also raises the question of how this would work in the future when all users are able to create open groups (not just rarified partners and publishers). Would a user have to belong to a publisher (somehow? Implying an additional publisher-user relationship) to be able to create an open group?

I have some other questions, too, like whether private groups can belong to a publisher or not.

HUGE CRAZY IDEA DISCLAIMER HERE ALERT ALERT — Please no one panic and think I'm about to rewrite our product!

I'm going to throw out something crazy and probably something we should bury under 20 feet of mud and rocks, but...is it possible that a _publisher_ is a type of _group_? I know, I know, ridiculous, but here's why that idea floats into my head:

* This requirement is slightly suggesting the notion of _hierarchy_, versus a flat set of relationships
* We have already overloaded what _group_ means in how we're twisting them to pack in the notion of _type_. Sometimes we treat groups like a set of user relationships and permissions, sometimes we treat them as containers or folders.
* Recall that a _type_ of group is an imaginary concept that is really a grouping of permissions and access restrictions (I separate those two because of the _scoping_ element of open-type groups). Technically, a _publisher_ could be a group with `writableBy` of `None` (i.e. you can't put annotations in the group; though even this is up for debate; maybe some publishers would want their top-level group writeable) and `readableBy` = `authority` (or `world` or `members`...really the sky's the limit, sorta). Really we could tweak the permissions as we or the users please.
* In this crazy crazy world, the task would not be to create a new entity but to create an optional parent-child relationship between groups. If we wanted, child groups could inherit things from their parents—things like icons, for example—or override them. 
* This would also give publishers the ability to have nested collections of groups.

OK, I'm done with my loose cannon thoughts :boom: for the day. Thanks!

**Comment by seanh** [comment]
Suggestion: lets remove this from the current sprint as we have way more than enough in the sprint without it and we're focused on implementing minimal restricted groups, not adding in publishers, right now. In fact I wonder if we should just close this spike card and use <https://github.com/hypothesis/product-backlog/issues/497> when we get to it?

**Comment by seanh** [comment]
Sprint planning: closing this. Use https://github.com/hypothesis/product-backlog/issues/497
