### ISSUE TITLE
Restrict ability to add annotation through API by group scope (?)

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#483]
Right now there is nothing in place on the backend to prevent an annotation being added to a scoped group for a target document with a URI outside of the group's scope. Granted, out-of-scope open groups are not presented to the user in the client, but there is nothing preventing anyone using a tool (e.g. `curl`, an app like `Postman`) to send (authenticated) requests at our API to annotate a document outside of a group's scope—e.g. it is perfectly valid to annotate a document at a URI on `http://example.org` within an open group scoped to `http://foo.com` from the API's perspective.

First, do we want to implement a backend validation restriction on this? My hunch is: probably?

The area of code we'd want to amend falls around here: https://github.com/hypothesis/h/blob/1620594d3f78d22583523d338cd64ab442b5a87b/h/storage.py#L124

That's where a check is made to make sure that the user is allowed to post an annotation (i.e. has `write` access) to the given group.

Attn @ajpeddakotla on this one!

**Comment by seanh** [comment]
I think we can just move this card into up next right away as this is something we already agreed but forgot to do. It was always the intention that scoped open groups can't annotate pages outside of that scope, because the group doesn't appear on pages outside of the scope, and the fact that you _can_ actually do it using the API or a broken client is just a technical hole we need to plug. We've had clarification from Heather in the past also that publishers would be "distressed" to see pages outside of their scope having been annotated in their group and this appearing on their group's activity page.

**Comment by robertknight** [comment]
I'm re-opening this because we need to make sure group scope restrictions are enforced when updating annotations as well as when creating them.

**Comment by lyzadanger** [comment]
@robertknight Took me a while to track this down, but I don't think such a change is actually necessary as all group-related fields are ignored on annotation update. To wit, in `h.schemas.annotation.UpdateAnnotationSchema`:

```
        # Some fields are not allowed to be changed in annotation updates.
        for key in ['group', 'groupid', 'userid', 'references']:
            appstruct.pop(key, '')
```

A related task might be to document that the `PATCH` endpoint ignores certain fields (for the benefit of anyone using our API)?

**Comment by robertknight** [comment]
@lyzadanger - You cannot change the _group_ on an update but you can change the _uri_, so you can violate scope constraints by changing the latter.

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/h/issues/4835
