### ISSUE TITLE
Launching sidebar in a restricted group

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#489]
This was pulled out of the [restricted groups card](https://github.com/hypothesis/product-backlog/issues/424) as separate work

### User Need ###
As a USER I want to be able to understand that I am unable to annotate in a restricted group.

### Justification ###
We want to avoid walking users into an error - see current working implementation:

_Error State_
![error_message](https://user-images.githubusercontent.com/5212631/37292625-88a41178-2611-11e8-8ed9-1181d8d44282.gif)

### Proposed Solution ###
When a user selects text to annotate and the associated group is 'read-only', the adder displays as normal with a few core differences:

- the Highlight button inside the adder is shown as greyed out/disabled.
- the 'Annotate' button is replaced with 'View Annotations.'
- when a user rolls over the view annotations button, they see a 'Read-only Group' tooltip.
- when a user rolls over **or clicks** the highlight button, they see a 'Read-only Group' tooltip.
- the 'add note' button is hidden in the button bar.

**Adder behaviour in a restricted group:**
![adder read-only mode](https://user-images.githubusercontent.com/5212631/37292641-913da40c-2611-11e8-9c4e-a6c5025f93e6.png)

**Sidebar launches in 'Read-only' mode**
- onClick 'View Annotations' the sidebar is launched in read-only mode. 
- the annotation field and post to button are not shown and the user is prevented from experiencing the error of trying to post to a restricted group shown in the error state animated gif above.
- Messaging in the form of a 'read only' badge in the header bar. ![read-only](https://user-images.githubusercontent.com/5212631/37659247-60fd08b4-2c47-11e8-89ce-f1a3a1e2ac6b.png)
(note: the 'READ ONLY' badge work has been moved to a separate card:  #552)

**Sidebar showing the banner at the top**
![revised restricted group 4_final](https://user-images.githubusercontent.com/5212631/37659234-5a8a478a-2c47-11e8-83c8-dcffdd8be4fe.png)

**A tooltip is shown on rollover**
![tooltip is shown](https://user-images.githubusercontent.com/5212631/37660224-d0fe4a90-2c49-11e8-9889-9cea81206e37.png)

**Add note button**
_Hide the add note button in the button bar_

Since a note is an unanchored annotation, and the user is in a restricted group, we need to remove the ability to add notes when the user does not have write permissions.

**Badge Responsivity**
_The badge needs to be responsive to group name char count and platform_

Due to limitations in real estate space in the header because of group name size and the platform users will view the H sidebar on, we need to scale the badge accordingly. Below are proposals for how the badge can scale to meet these various scenarios:

_Shorter group names 14 chars or less - web_
![shorter-web](https://user-images.githubusercontent.com/5212631/37714560-b9b59c62-2d11-11e8-871b-b181ae5b97cd.png)

_Medium group names 20 chars or less - web_
![medium -web](https://user-images.githubusercontent.com/5212631/37713984-531c891c-2d10-11e8-944b-4ec4cc92fbb3.png)

_Longer group names 20-25 chars - web_
![longer -web](https://user-images.githubusercontent.com/5212631/37714030-6c0e8880-2d10-11e8-849d-31b16c61165b.png)

_Mobile - long and short group names_
![mobile - badges](https://user-images.githubusercontent.com/5212631/37714058-7a04920e-2d10-11e8-826c-2e543cc92f67.png)

The optimal break points for determining which badge type is displayed: Read only -> Read -> R is TBD. I will create a new user story for the badge responsivity work.

**AC**

When the focused group is a restricted group which the current user is not a member of:

- [ ] The 'Annotate' button in the adder is substituted with 'View Annotations' (see mockup) and displays a different tooltip
- [ ] Clicking the "View annotations" button opens the sidebar but does not create a new annotation
- [ ] The 'Highlight' button in the adder is disabled and displays a different tooltip
- [ ] The "New note" button does not appear in the toolbar
- [ ] The "New note" button does not appear in the sidebar when that feature is enabled
- [ ] The "Reply" button does not appear on annotation cards in the sidebar
- [ ] ~~a 'read only' badge is shown to the right of the group name.~~ (note: the 'READ ONLY' badge work has been moved to a separate card:  #552)

**Implementation**

@robertknight's implementation notes/checklist here: https://github.com/hypothesis/product-backlog/issues/489#issuecomment-379178716

**Comment by ajpeddakotla** [comment]
Other notes from @dawariley on the original card: 

Note: the following is out of scope for this card and will be considered as part of a separate design spike.
- Users should still be able to 'Post to only me' within a Restricted group. 
- 'Only me' annotations should live outside of the group context and be readily accessible through the scope control e.g introducing 'Only me' as an option to filter sidebar annotations by annotations made only by me. Based on frequency of current annotation behaviour it is proposed that 'Only me' features near the top of the scope control below 'Public'.
- The post to button submit button within a restricted/read-only group allows users to post to 'only me'. 
- I will explore what, if any messaging is displayed to users including in the 'adder' TBD and the sidebar. Suggestions include: incorporating a watermark in the text field to make the scope of the post to explicit.

I will edit/remove the earlier comment and provide updated designs for this issue. Additional issues may need to be created to reflect moving 'only me' annotations out of the group level to a standalone 'only me' category. Referenced here already: #200

**Comment by ajpeddakotla** [comment]
We might also want to pull in some of the issues @seanh has pointed out here: https://github.com/hypothesis/product-backlog/issues/476

**Comment by seanh** [comment]
> - Users should still be able to 'Post to only me' within a Restricted group.
> - 'Only me' annotations should live outside of the group context and be readily accessible through the scope control e.g introducing 'Only me' as an option to filter sidebar annotations by annotations made only by me. Based on frequency of current annotation behaviour it is proposed that 'Only me' features near the top of the scope control below 'Public'.
> - The post to button submit button within a restricted/read-only group allows users to post to 'only me'. 
> - Adder annotate and highlight behaviours remain in-tact in the use case of Restricted groups.
> - I will explore what, if any messaging is displayed to users including in the 'adder' TBD and the sidebar. Suggestions include: incorporating a watermark in the text field to make the scope of the post to explicit.

Just to point out: the **problem** that we need to solve for this card is what happens when a logged-in user who is _not_ a member of a restricted group has that restricted group selected in the groups menu, and tries to annotate? _How_ we solve that problem, and whether it involves posting to only me or not, changes the the post button, changes to the adder, etc, is up to us, depends on what solution we come up with.

**Comment by dawachan** [comment]
@ajpeddakotla and @dwhly ready for review, thanks!

**Comment by dawachan** [comment]
Based on a review last week, I've made a few tweaks (attached) which are pending review.

![revised - restricted groups designs](https://user-images.githubusercontent.com/5212631/37597460-6e00954c-2b77-11e8-9399-62a8e7d7d12c.png)

**Comment by robertknight** [comment]
I think the implementation work here breaks down roughly as follows:

- [ ] In the API, communicate to the client whether the user can post to a given group. Note that we cannot just use `group.type === "restricted"` because that is a property of the group, whereas ability to post depends on the user's permissions within the group
- [ ] Monitor the read-only state of the focused group in the sidebar and communicate it to the host page.
- [ ] Communicate the read-only state of the focused group to any instances of the client loaded in iframes on the host page
- [ ] Add a 'read-only' state to the toolbar in the host page and make that reflect the read-only state communicated from the host page, following the mocks in the issue description
- [ ] Add a 'read-only' state to the "Adder" toolbar and make that reflect the read-only state communicated from the host page, following the mocks in the issue description
- [ ] Remove or disable the "New note" button in the sidebar when the current group is read-only, as well as the "Reply" button on individual annotation cards
- [ ] Add a "Read only" badge to the sidebar and make that reflect whether the focused group is read-only. This is captured in the separate card at https://github.com/hypothesis/product-backlog/issues/552

Since several of these steps depend on the focused group, it would be helpful if that state were moved from the groups service in `services/groups.js` to the store as per [this recent ADR](https://github.com/hypothesis/client/blob/master/docs/developers/arch/adr-003.md).

**Comment by robertknight** [comment]
As per @seanh's suggestion, I have created a new issue at https://github.com/hypothesis/product-backlog/issues/575 which summarises the outcome of design feedback and developer elaboration above, which we can then start actively working on.
