### ISSUE TITLE
The sidebar on activity pages displays the group's logo and publisher name

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#492]
As a user, it's quicker to identify a group based on the authority and logo of a group and the name rather than just the name. As a customer it would be nice if the my logo was present next to groups that are in my domain.
<img src="https://user-images.githubusercontent.com/5212631/36032068-b22e6c9e-0da4-11e8-9ee0-ab3e2335a7a3.png">

### See also

* [Organizations spike](https://github.com/hypothesis/product-backlog/issues/515)

**Comment by hmstepanek** [comment]
@dawariley Again, I attached the mock you uploaded here. Feel free to modify as you wish. :)

**Comment by seanh** [comment]
Note that this requires us to have the concept of a publisher (or "organization" as we've been calling it) to be implemented in Hypothesis first, since the organization name and logo shown in the mockup belong to the organization not to the group.

_Or_ we could just add the organization name and logo as a property of the group first, so that we can implement this without having to have organizations yet, and then move these properties onto the organizations when we get round to adding them.

**Comment by robertknight** [comment]
This now shipped.
