### ISSUE TITLE
Deprecating the Public, Private Group Icons (?)

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#573]
When putting together acceptance criteria for https://github.com/hypothesis/product-backlog/issues/572 it occurred to me that the mockup provided—for the groups control—implies the retirement of the public ("world") and private ("people") group icons.

I was wondering if that retirement stretches further than the group-select control, as those icons show up in other places in the client application, like in threaded annotations and replies and when toggling between the group/only me during annotation creation.

Is this something that needs to be audited?

This is likely a question for @dawariley

**Comment by dawachan** [comment]
I synced with @robertknight on this today and although group type icons are being retired from the group control since the core distinction we are making to users at a high level is around organisation and not group type. However, as you noted - we do use group type icons in other places such as against individual annotation cards both in the sidebar and activity pages. Let's leave them 'as-is' for now and we can subtract, augment or replace later in a separate issue.

They should only be deprecated in the groups control for now, and not globally.

**Comment by lyzadanger** [comment]
Thanks, @dawariley for a very clear answer—very helpful!

I'm going to close this issue for now as there is nothing to be done at this time.
