### ISSUE TITLE
Set up monitoring for Elasticsearch 6 cluster

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#607]
Make sure we have adequate monitoring / alerting in place for the Elasticsearch 6 cluster.

- [x] Make sure Elasticsearch 6 requests are tracked from the client-side and reported in New Relic (it should show up under [Database activity](https://rpm.newrelic.com/accounts/1385283/applications/22688631/datastores#/overview/All?value=total_call_time_per_minute)).
- [x] Make our Grafana monitoring dashboard show data from the Elasticsearch 6 cluster (see https://github.com/hypothesis/playbook/pull/178)

**Comment by robertknight** [comment]
For the existing Elasticsearch cluster we have two sources of monitoring info:

1. The [Amazon Elasticsearch dashboard](https://us-west-1.console.aws.amazon.com/es/home?region=us-west-1). This we get for free.
2. The [Elasticsearch AWS dashboard](https://mon.hypothes.is/grafana/dashboard/db/elasticsearch-aws) in Grafana. This may not be all that important. I don't think any of us have looked at it in a long time. From a look through the playbook it appears that this depends upon [collectd-elasticsearch](https://github.com/phobos182/collectd-elasticsearch) which hasn't been updated for ES 6. I would suggest we start with just (1), retire (2) and only look into alternatives if we find down the road that (1) is missing something important.

For getting automated alerts about problems with the cluster, we probably want to make use of CloudWatch, since that will provide a unified way to handle alerting across different services.

**Comment by robertknight** [comment]
One option for the ES 6 cluster is to use the Kibana service that comes with AWS Elasticsearch and its monitoring data explorer. In order to do that, we'll need to set up a VPN or some other means of accessing the Kibana service which lives inside our VPC.

**Comment by hmstepanek** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/cluster-admin.html Don’t forget we also have monitoring of es in New Relic for queries and such. It seems like x-pack is commonly used but I don’t think it’s free. I think it would be helpful to identify the kind of monitoring we need and don’t have and go from there. I think at least some of the monitoring provided by AWS is the same as the monitoring we have in grafana. This seems like it provides a nice overview of the different monitoring: https://www.datadoghq.com/blog/monitor-elasticsearch-performance-metrics/.

**Comment by hmstepanek** [comment]
We can also add custom metrics and events for identifying when something wasn’t found and should have been/etc.

**Comment by robertknight** [comment]
It appears that AWS Elasticsearch may not support x-pack, which removes the Monitoring tab from Kibana as an option :( - https://forums.aws.amazon.com/thread.jspa?threadID=248200&start=25&tstart=0

**Comment by robertknight** [comment]
Following an investigation into some of the available options, I have updated the issue description to cover tasks we'll need to do to get reasonable monitoring coverage:

- New Relic can give us info about volume of activity and latency as seen from the h application side
- Grafana can give us access to detailed stats from ES' stats APIs
- Amazon Elasticsearch's dashboard in AWS provides high-level health metrics for the ES nodes (CPU usage, IO volume, memory pressure)

**Comment by robertknight** [comment]
The [Elasticsearch AWS](https://mon.hypothes.is/grafana/dashboard/db/elasticsearch-aws) dashboard is now updated and showing stats from the ES6 cluster.

**Comment by robertknight** [comment]
The issue for updating documentation for connecting to and querying the ES cluster is tracked in the main cleanup ticket: 
https://github.com/hypothesis/product-backlog/issues/608
