### ISSUE TITLE
Decide what to do with our own ES backups

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#610]
(_Original description: Make backup of old es cluster before we take it down. Make sure our backups are in place and working for the new es cluster._)

We currently have two kinds of backup of the ES cluster:

- Automated snapshots created by Amazon's Elasticsearch service (see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html)
- Automated backups configured by our own scripts [in the playbook](https://github.com/hypothesis/playbook/tree/master/configure/roles/elasticsearch-backup)

When we move from ES 1.5 to a new ES 6.2 cluster, we should review our approach to backups:

- [x] Decide what kinds of backup of the ES cluster we need going forwards
- [x] Remove our custom infrastructure for automated backups entirely if we decide that we can rely just on those created by Amazon ES (https://github.com/hypothesis/product-backlog/issues/731)
- [x] Remove our own backups of the old ES cluster that are no longer required

**Comment by robertknight** [comment]
Given that ES is not our canonical data store and is just an index created from data in RDS, I'd suggest that Amazon Elasticsearch's [automated snapshots](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html) which keeps ES snapshots for the last 14 days will be sufficient for our backup needs.

Amazon ES is configured to create the automatic snapshots daily at 07:00 UTC for both the ES 1.5 and ES 6.2 cluster.

If we ever did have a problem with ES that required a restore, we would probably approach this by restoring the snapshot and then re-indexing all annotations updated since X, where X is the time when the snapshot was created. We don't actually have a way to do partial reindexing at the moment, only a. Jenkins task to reindex the entire DB.

**Comment by robertknight** [comment]
If we do decide to do away with our own ES backups and just rely on those created by AWS, then the work involved would be:

- Remove [the elasticsearch-backup role](https://github.com/hypothesis/playbook/tree/master/configure/roles/elasticsearch-backup) and make sure it isn't running on any machines where it is currently active
- Remove any existing ES backups that we no longer need from the `hypothesis-backup-es` bucket and delete the bucket itself

**Comment by robertknight** [comment]
[Discussed yesterday in Slack](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1532344621000052). Since ES is no longer our primary datastore and we can rebuild it fairly quickly from the DB (in ~2 hours or so), we're opting to remove our custom backup infrastructure and just use Amazon's automated ES snapshots.

The other use of the custom ES backups was restoring a prod search index dumb to a local development server. I don't think anyone at H has had a need to do this for a long time though.

**Comment by robertknight** [comment]
I have removed all of the "snapshots/indices/hypothesis-{hash}" folders from the "hypothesis-backup-es" bucket which were created by indexing data already in Postgres. There are a handful of older index folders left named "annotator*" which predate the transition of annotation data from Elasticsearch to Postgres. If we're happy we don't have any interest in those for historical purposes then we could also delete them, and save a whopping $1/month in storage costs 😛
