### ISSUE TITLE
Add the ability to write to both db's in h

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#615]
This should be hidden behind a feature flag where we can write to both db's (encrypted and not encrypted) as the same time.

**Comment by robertknight** [comment]
I don't think we should try to do this. Writing to two separate databases is going to require changes to many parts of the code for IMO little benefit, since we are not changing the software that we use as we are in the case of Elasticsearch, only switching over the RDS instance to one which uses encryption for the underlying block storage.

Instead what I suggest is that we take the service down for a small amount of time (I estimate about an hour, we'll tell users two) in order to snapshot the existing DB, create a new encrypted RDS instance from it, reconfigure the services to use the new instance, and then bring it back up again. In the event of a problem we can just roll back the configuration to point at the unencrypted RDS instance and bring the service back up again. See my sketch here: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1525272987000192

**Comment by robertknight** [comment]
I'm closing this card for now because, unless I hear objections, I'm going to assume we'll do what we outlined in my comment above which does not involve code changes to h.
