### ISSUE TITLE
Verify backups work on encrypted db

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#618]
You cannot easily restore an encrypted db from an unencrypted db (you have to create a new db from the unencrypted one). Also we don't want to keep unencrypted backups as that kinda defeats the purpose. Therefore, we need to make sure backups work on the encrypted db before deleting the old db.

**Comment by robertknight** [comment]
There are two types of backups for our production DB.

- RDS storage snapshots. These are daily snapshots of the whole DB instance created automatically by RDS. We currently have the service configured to keep 30 days worth of backups.
- h DB backups. This is a logical dump of the h DB configured to run [as a cron job](https://github.com/hypothesis/playbook/blob/master/configure/roles/postgres-backup/tasks/postgres-backup.yml) on [the monitoring server](https://github.com/hypothesis/playbook/blob/4b80ec70cccc5c11067539baeec30f4186f934c2/configure/site.yml#L56) taken using the [postgres-s3-backup](https://github.com/hypothesis/postgres-s3-backup) script.

For the RDS storage backups, we just need to configure the new encrypted RDS instance using the same settings as the existing one. The logical DB backup script shouldn't require any changes to just to function beyond being configured to connect to the correct RDS instance. However in order to maintain the encryption we'll need to make sure that the logical backups are encrypted as well. Assuming we decide that we want to continue making logical backups, we should probably look into using the recently added [Default encryption](https://aws.amazon.com/blogs/aws/new-amazon-s3-encryption-security-features/) S3 feature to ensure that all files in the bucket where the backups are stored are encrypted.

**Comment by robertknight** [comment]
Neither of the backups are affected by the change to encrypt the underlying storage. The only change required was to update the endpoint for the pg_dump backup script.
