### ISSUE TITLE
Implement encryption-at-rest for PostgreSQL

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#621]
This is the [Epic](https://github.com/hypothesis/product-backlog/labels/Epic) card for implementing PostgreSQL encryption-at-rest. We should add a checklist here of all the sub-cards that this breaks down into, but for now they all have the [Encrypt Postgres label](https://github.com/hypothesis/product-backlog/labels/Encrypt%20Postgres).

Implement encryption-at-rest for our PostgreSQL database. This probably requires migrating h over to a new database, rather than turning on encryption for our current database.

**Comment by seanh** [comment]
[Comment from @hmstepanek](https://github.com/hypothesis/product-backlog/issues/559#issuecomment-383362112):

From the amazon docs: 
```
You can only enable encryption for an Amazon RDS DB instance when you create it, not after the DB
instance is created. However, because you can encrypt a copy of an unencrypted DB snapshot, you
can effectively add encryption to an unencrypted DB instance. That is, you can create a snapshot of
your DB instance, and then create an encrypted copy of that snapshot. You can then restore a DB
instance from the encrypted snapshot, and thus you have an encrypted copy of your original DB
instance. 
```
This means we have to copy our existing db to a new encrypted db. We could make this switch by either temporarily putting the app into readonly mode so no new annotations get added, or alternatively, we can write to both at once, then make the switch to the encrypted (there may be some missing data in between the copy and the writing to both but we can fix that by adding them after and since we are still using the old db to read at first, our customers will never know). <-The second approach is the same plan as we are using on ES so we may just want to keep both these the same.

Again, what's important in all of this is to make sure our backups work. We will want to make a backup of the encrypted db before we take down the old one. It sounds a bit complicated to restore an encrypted db from a non encrypted db so we should avoid that. Also we don't want non encrypted restores hanging around as that kinda defeats the purpose.

**Comment by seanh** [comment]
[Comment from @hmstepanek](https://github.com/hypothesis/product-backlog/issues/559#issuecomment-383656880):

General info about amazon's encryption:

> Amazon RDS encrypted instances use the industry standard AES-256 encryption algorithm to encrypt your data on the server that hosts your Amazon RDS instance. Once your data is encrypted, Amazon RDS handles authentication of access and decryption of your data transparently with a minimal impact on performance. You don't need to modify your database client applications to use encryption.

**Comment by robertknight** [comment]
I read through these issues and walked through part of the process of snapshotting, encrypting and creating a new RDS instance yesterday. Though it would be _technically possible_ to do a near zero-downtime migration to an encrypted DB (see eg. [this blog post](https://blog.learnosity.com/2017/08/engineering-for-zero-downtime-advanced-rds-database-migrations/) which is about RDS and MySQL), that is going to be a somewhat more complex procedure than taking the site down for a brief time (I estimate about an hour), at a quiet time and following [the procedure outlined here](https://github.com/hypothesis/product-backlog/issues/615#issuecomment-386275116). Given our current team and usage levels at quiet times, I'm going to strongly recommend that we take the simple route.

As an aside, writing to two different databases from the app itself is a complete non-starter for me since it adds a bunch of exciting new failure modes (eg. transaction commits on one but fails on another for whatever reasons). If we did want to achieve a zero-downtime migration we would probably do something along the lines of what that blog post suggests involving the DB's binlog replication facilities.

**Comment by robertknight** [comment]
This is now done.
