### ISSUE TITLE
Do not show the H Public group when a publisher group is present and users are unauthenticated.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#702]
### Problem
Currently, unauthenticated users are able to see the H Public group on pages where we have publisher groups (restricted/open groups that are scoped to a publisher's page). 

The steps that you have to take to see the current behavior are as follows: 
1.  Log out
2. Go here: http://care.diabetesjournals.org/content/41/Supplement_1/S55#annotations:wmtWGjwnEeiOWY_FhVG-zA
3. Open group control
4. See the H Public group 

### User Story
As a publisher, I'd like to restrict the H Public layer from being visible on my site for unauthenticated users, so that I can focus users on the group that I control on my site. 

### Acceptance Criteria
- [x] H Public layer is not visible if user has not logged into their H account. 
- [x] Only the publisher's scoped/authoritative group should show in the group scope when an unauthenticated user is on a publisher's site that has a scoped group. 
- [x] If a user follows a direct link to an annotation in the Public group, regardless of whether they're logged in, the Public group should then be shown, and the annotation selected.

**Comment by klemay** [comment]
Question about how this would affect linking to annotations:

I am a Hypothesis user and I annotate in the Public channel on a site that has a publisher group and has suppressed the Public layer for non-authenticated users. I'd like to share a link to my annotation with Dan, another Hypothesis user, but he's not currently logged in. He clicks the `hyp.is` link I share with him - what happens? Is he able to see my annotation despite not being logged in, even though the Public group should be suppressed?

**Comment by dwhly** [comment]
@klemay Great question.  And I've added this to the acceptance criteria.

Clearly someone following a link to an annotation in the public group wants to see that annotation, and should be allowed to.  I don't think publishers would disagree.  This would go for any link to an annotation in any group that isn't visible by default.

**Comment by robertknight** [comment]
The case where a user is logged out but follows a direct link to an annotation in the Public group is a good catch but complicates things a bit. I've opened a PR that addresses the other two acceptance criteria but doesn't resolve this. I'll need to discuss with other devs.

I think we'll need to either 1) figure out a way to make groups show up dependent on a target annotation as well as the document URL, or 2) include the group ID in the metadata that bouncer passes to the client and have the client request that group in addition to whatever groups apply to the current page. If we go with the second approach, we'll need to make sure that only happens if the group is public to avoid leaking access to private groups.

**Comment by robertknight** [comment]
Implemented. See [Slack note](https://hypothes-is.slack.com/archives/C0C6BDS1H/p1533926490000200).
