### ISSUE TITLE
TinyTinyRSS feed reader can't access Hypothesis annotations

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#710]
A user has [reported in our Google Forum](https://groups.google.com/a/list.hypothes.is/forum/?utm_medium=email&utm_source=footer#!msg/dev/8C9JkQg9DAQ/KSFQhrkOBAAJ) that TinyTinyRSS feed reader isn't able to access Hypothesis annotations. 

When trying to subscribe, TTRSS shows:
`Couldn't download the specified URL: HTTP/1.1 403 Forbidden (feed behind Cloudflare)`

The user has done the following troubleshooting:

> I am pretty sure this is not a TTRSS issue.
I did some testing with wget from my TTRSS IP address, as well as from my local machine's IP address, and the former is consistenly denied (403 forbidden) whereas the latter is not (200 OK).
> 
> Previous reports by other users in the TTRSS forums strongly suggest that the problem is caused by Cloudflare over-zealously blocking what it thinks are bots. See below.
https://discourse.tt-rss.org/t/http-403-and-cloudflare/628/4
https://discourse.tt-rss.org/t/cant-add-feed-msg-specified-url-could-not-be-downloaded-false/1155/5
> 
> The same forum posts also suggest the service provider (Hypothes.is in this case) can remedy this problem by relaxing its Cloudflare settings. 
Is this something Hypothes.is would consider looking into? As it is now, I cannot subscribe to any of your users' Atom/RSS feeds (and I've tried my own as well as those of other users and tags).
> 
> N.B: the main Hypothes.is feed (https://web.hypothes.is/feed/) appears to be delivered through some other mechanism though, because I can both subscribe to it and wget it from my TTRSS machine without any problems. Confirmed: a quick lookup shows that web.hypothes.is points to 23.185.0.3, whereas hypothes.is points to 104.20.215.15 and 104.20.214.15, which are Cloudflare IPs).
> 
> I guess what I'm asking for is for Hypothes.is to relax or adjust your Cloudflare settings so we can subscribe to the hypothes.is user feeds without this mysterious IP-based block. Or, please explain what we are supposed to do be able to subscribe to Hypothes.is user feeds (does Cloudflare have a list of all blocked IP ranges published somewhere? should I contact Linode about this? any other remedies?).

**Comment by solarchemist** [comment]
So I did some testing from two different IP addresses, we'll call them "IP1" (my desktop) and "IP2" (Linode VPS), with a feed address as specified on the [Hypothes.is feed page](https://web.hypothes.is/help/atom-rss-feeds-for-annotations/), a suggested work-around using `via.hypothes.is` instead of `hypothes.is`, and Hypothes.is' own RSS feed. For this test I used `wget` on both machines, also used Firefox on desktop and TinyTinyRSS on the VPS - they all showed the same results.
```
                                                      desktop                  VPS
                                                      =======                  ====
https://hypothes.is/stream.atom?user=paulallison      200 OK                   403 forbidden
https://via.hypothes.is/stream.atom?user=paulallison  503 service unavailable  403 forbidden
https://web.hypothes.is/feed/                         200 OK                   200 OK
```

Both `via.hypothes.is` and `hypothes.is` point to the same IP addresses (`104.20.214.15` and `104.20.215.15`, i.e., Cloudflare) which is interesting considering that `via.hypothes.is` subdomain gives error 503 from `wget` on the desktop but `hypothes.is` works. I have no idea why. 
Here's the error on trying to access as shown in a browser:
![selection_069](https://user-images.githubusercontent.com/979546/42535734-7f72d62e-8490-11e8-9800-4cef05a4c1ae.png)

I hope what little information I managed to contribute will help your team to alleviate this issue. Thank you @klemay for all your help!

PS. I have intentionally withheld my own IP addresses. If you think having them will help, feel free to contact me privately.

**Comment by judell** [comment]
Hi Taha,

Please try https://via.hypothes.is/https://hypothes.is/stream.atom?user=paulallison (vs https://via.hypothes.is/stream.atom?user=paulallison) and let me know what you see.

(Sorry, should've been clearer about that.)

**Comment by solarchemist** [comment]
Well, dang! Sorry for misunderstanding that, I guess I was tired :-)

Ok, this makes more sense, but the IP block appears to remain:
```
                                                                          desktop   Linode UK   Linode DE   DO US/DE
                                                                          =======   =========   =========   =====
https://hypothes.is/stream.atom?user=paulallison                          200       403         403         200
https://via.hypothes.is/https://hypothes.is/stream.atom?user=paulallison  403       403         403         200
https://web.hypothes.is/feed/                                             200       200         200         200
```

Please note I extended the table with some more IP addresses. Now these are strictly `wget` tests, but as we've seen that should work well. Both my Linodes (London and Frankfurt) are blocked by your Cloudflare servers, while my Digitalocean droplets (one in NYC, one in Frankfurt) works. 

Now, I hope I'm not sending you on a wild-goose chase, but to me (from very limited data) this looks like Cloudflare interfering based on IP ranges. Perhaps I just happened to be among the first to try to subscribe to your feeds using a feed reader hosted on a Linode? I hope it's that simple.

**Comment by judell** [comment]
> Sorry for misunderstanding that, I guess I was tired :-)

Ditto here, or I wouldn't have bothered with that last suggestion :-)

Your linode vs digitalocean comparison looks pretty conclusive.

> should I contact Linode about this? 

If you're willing to do that, we'd appreciate knowing their response.

Thanks,

Jon

**Comment by solarchemist** [comment]
Hi guys,

I opened a ticket with Linode, and they looked into this issue/thread, and here's their findings (if I may summarise):

- Your Linode gets a captcha when attempting to access this URL.
- We seem to be getting the captcha from a wide selection of addresses within the Linode Network Range in both IPv4 and IPv6.
- We tried a number of sites outside of Linode's network and they are not required to do the captcha.

At this point, I'm pretty confident that this issue is caused by Cloudflare blocking some IP ranges on behalf of hypothes.is. More to the point, the issue is likely caused by a security setting (possibly unintended?) in your Cloudflare account. The issue should be fixable by either adjusting/reverting the setting in question, or else by explicitly whitelisting Linode's ASN: AS63949.

The Linode support team also found a [Cloudflare support article](https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-) which is probably relevant. 

I hope I didn't bungle Linode's response. (I feel a little like a parrot relaying messages between two highly intelligent species ;-) I hope you have enough information now to settle this matter.

**Comment by klemay** [comment]
@chepec Thank you for checking with Linode and relaying their answer back. I'll check with the Powers That Be (i.e,, those who have Cloudflare admin access)

**Comment by klemay** [comment]
Hi @chepec would you be able to provide a URL for the feed you're trying to add for your reader? We have some room for this in our current sprint and will need that URL for testing!

**Comment by solarchemist** [comment]
Hi @klemay! Here's a few with enough content to get you going:
https://hypothes.is/stream.atom?user=paulallison
https://hypothes.is/stream.rss?user=paulallison
https://hypothes.is/stream.atom?tags=edu305

PS. I was originally trying to add the feed for my own H.is account, but it has no public content yet so would be a poor example for testing.

**Comment by klemay** [comment]
Hi @chepec thanks for responding, and for your patience while we work through this! I actually need one more piece of information: we need the URL and IP address for your TinyTinyRSS feed. We're not able to whitelist Linode as a whole, but we can whitelist your specific instance of TinyTinyRSS.

You can send this info to support@hypothes.is rather than posting it publicly here :)

**Comment by solarchemist** [comment]
I've just sent the requested information via email to support@hypothes.is.

In closing, I hope you plan to add a snippet on your [Feeds for Annotations help page](https://web.hypothes.is/help/atom-rss-feeds-for-annotations/) saying something alone the lines of: "if you self-host your feed reader and host your RSS server on Linode, you need to request your IP to be whitelisted by sending us an email..." 
Wouldn't want anyone else to go through this same ordeal all over again, although it has been a pleasure dealing with you :-)

**Comment by klemay** [comment]
You've been whitelisted - please let us know if that worked!

And I'm adding a note now. Thanks for the suggestion and for your patience
:)

**Comment by solarchemist** [comment]
No joy so far, I'm afraid. I've tried adding a H.is feed a few times every 12 hours or so. Same error message as before.

**Comment by klemay** [comment]
I'm sorry that didn't work out!

I think the course of action from here is to choose a network other than Linode for hosting your RSS server. We do have Linode intentionally blocked and our Cloudflare admin doesn't feel comfortable removing that block.

**Comment by solarchemist** [comment]
Ok, so that went from "your IP is whitelisted" to "all of Linode is blacklisted". Well, I assume your admin has a good reason for blocking Linode's ASN, but I must say that seems rather arbitrary and over-reaching to me.

And how does blocking an entire ASN rhyme with Hypothes.is mission statement "to bring an open conversation over the whole web"? Automated feeds (such as RSS, Atom) are an important medium for that conversation, you know. Just my two cents.

**Comment by segdeha** [comment]
Hey @chepec. I'm the Director of Engineering here at Hypothesis. Saw that there might be some misunderstanding here, so I wanted to add my perspective.

It would have been before my time, but we must have had trouble with spammy requests coming from Linode in the past (Linode is used for a lot more than just serving RSS readers). I agree that it's a boil-the-ocean solution, so we will have a discussion internally to consider lifting that blanket restriction. For the record, I agree that it—in principle—is not in line with our mission to block an entire hosting company, but we do reserve the right to do that if allowing it is going to degrade the experience for our other users.

Sorry if this is an obvious distinction, but we do not block RSS/Atom readers, generally. It would be kind of pointless for us to serve RSS feeds if that were the case! 🙃

All of that said, I made a change to the firewall rule that _might_ make your particular case work. Please try again and let us know whether or not that's the case by emailing support@hypothes.is

I see all emails to that address, but you're also welcome to email me directly at andrew@hypothes.is if you have any remaining concerns.

Thanks for using Hypothesis!
