### ISSUE TITLE
Many users are seeing Invalid Session

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#72]
### Problem you are trying to address with this feature
Users who are using EFF's Privacy Badger are seeing an Invalid Session warning.

### Your solution
Per @nickstenning there is work we can do move away from cookies for auth for the H. sidebar.  This is a stub for that issue.

**Comment by robertknight** [comment]
Hypothesis (as of v1.39) now detects when the browser is preventing it from storing cookies and falls back to using OAuth rather than cookies for authentication in this context. You may find that you need to click the "Log in" button each time the client loads, but as long as you are signed in to the website you won't have to re-enter your login details each time.
