### ISSUE TITLE
Replace Builder class w/ elasticsearch-dsl

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#746]
Refactor the search code to remove the Builder class. The Builder class is legacy code that was made because there used to not be such a thing as elasticsearch-dsl. It generates a giant dictionary for an elasticsearch query that is customized to h's needs. It is complicated and can be replaced by elasticsearch-dsl. elasticsearch-dsl is designed in a higher-level way such that it is easy to transition between versions of elasticsearch, thus switching to elasticsearch-dsl will make upgrading elasticsearch in the future potentially simpler. An example of this can be found in the filter syntax below. Notice that the user does not have to specify 'bool' or 'should' as part of the filter query so if that ever changes, elasticsearch-dsl will take care of that internally rather than us having to make the switch in our code. It is also more readable, instead of trying to read a giant dictionary like:
```
{'bool': {'should': [{'match': {'url': 'foobar'}}]}}
```
instead elasticsearch-dsl enables the following more readable syntax: 
```
search.filter("match", field="foobar")
```

**Comment by robertknight** [comment]
I'm happy for you to explore using elasticsearch-dsl for the builder code but I have concerns about whether it is really going to be worthwhile or not. There are two things which I think would convince me:

- If it does actually make the code significantly shorter & easier to follow.
- If it is still easy to relate the logic in our code to the corresponding Elasticsearch REST API documentation. This was the biggest issue I encountered when looking at using it for indexing code. It was fine for trivial use cases. However figuring out how to write eg. custom analyzers was IMO much easier using the low-level API because it was easier to relate to the ES API docs which contain all the important details.

This last point is something I think you always need to watch out for with abstraction wrappers/libraries. They can add maintenance overhead in the form of a gap between your code and the documentation which really matters (that is, for the library which does the real work), as well as extra dependencies to manage. That is not to say they are always a bad idea, just that it is a cost that needs to be taken into account.

> elasticsearch-dsl is designed in a higher-level way such that it is easy to transition between versions of elasticsearch, thus switching to elasticsearch-dsl will make upgrading elasticsearch in the future much simpler.

I'm afraid I just don't buy this. The changes required to the existing query code for upgrading _three major versions_ of Elasticsearch were minimal (thank-you ES developers!). As I currently see it, the majority of the effort came from a) writing tests that actually interact with ES, b) reading/writing two separate clusters at the same time, c) digesting the major conceptual changes from ES 1 => 2 => 5 => 6 and understanding which affect us and how. For example the removal of mapping types and the separation of "string" fields into text and keyword.

**Comment by robertknight** [comment]
https://github.com/hypothesis/h/pull/5219
