### ISSUE TITLE
Jenkins 2018-08-21 outage follow-up

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#761]
On Tuesday 2018-08-21 we were unable to deploy anything for several hours due to a Jenkins outage. The outage was caused by a [kernel bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1787127) which caused Jenkins to go haywire.  See [Slack discussion](https://hypothes-is.slack.com/archives/C074BUPEG/p1534878540000100).

The issue has now been resolved by installing an updated kernel on the support machine but we identified follow-up tasks to do:

- [x] Upgrade Jenkins to latest version on support @seanh
- [x] Upgrade Java to latest version on support @seanh
- [x] Install the latest available kernel on other static infrastructure running Ubuntu 14.04 since other applications may be affected @robertknight 
- [x] Write an incident report @robertknight [done](https://docs.google.com/document/d/1fL2ACp7Gf58D5ee6w6KWrxrRK6e1AehkY6J_nRPLp_s/edit#)
- [x] Resize the support machine back to a smaller instance. We upgraded it so that it had enough spare CPU that we could actually SSH into the machine while Java was using as much CPU as it could. @seanh
- [ ] Investigate recovery options for support. How would we recover/rebuild the machine if it had been completely hosed?
- [x] TBD - Decide if we want to stick with weekly Jenkins updates or move to an LTS release @seanh Notes: https://github.com/hypothesis/product-backlog/issues/761#issuecomment-414954664
- [x] TBD - Upgrade systems to Ubuntu 18.04 [card](https://github.com/hypothesis/product-backlog/issues/294) added to eng/ops backlog
- [x] Fix "held back" packages on `support` @seanh [Done](https://hypothes-is.slack.com/archives/C074BUPEG/p1534931688000100)

**Comment by seanh** [comment]
## Third-party package sources used on `support`

Packages on `support` that're installed from outside of the standard Ubuntu repos (see `ls /etc/apt/sources.list.d/` on `support`):

• Jenkins from http://pkg.jenkins-ci.org/ :heavy_check_mark: looks official (but should be the LTS not the weekly version)
• Docker from https://apt.dockerproject.org/ :heavy_check_mark: looks official
• nginx from https://launchpad.net/~nginx :open_mouth: looks official-ish but certainly seems unnecessary to use a third-party nginx package
• Java 8 from https://launchpad.net/~webupd8team :open_mouth: looks dodgy (the PPA belongs to a blog mostly about desktop linux apps that hasn't been posted to in a year)

**Comment by seanh** [comment]
## Jenkins weekly vs LTS

### Jenkins download docs

Here are [docs about Jenkins's LTS releases](https://jenkins.io/download/lts/#switching-from-weekly-to-lts). It looks like if we were on the LTS release line we should only need to install a "minor release" of Jenkins every four weeks, and a bigger release every twelve weeks.

### jenkins-ci.org vs jenkins.io

We're currently using <http://pkg.jenkins-ci.org/>. Specifically we're on the weekly release packages, which is <http://pkg.jenkins-ci.org/debian/>. If you look at the [Jenkins download page](https://jenkins.io/download/) it's all about jenkins.io and <https://pkg.jenkins.io/> now, not jenkins-ci.org. Even <http://pkg.jenkins-ci.org/debian/> itself lists <https://pkg.jenkins.io/> as the apt source. So I'm gonna assume that pkg.jenkins-ci.org moved to pkg.jenkins.io (but they just keep pkg.jenkins-ci.org running as a mirror for backwards compat).

### Jenkins version

We're currently on Jenkins 2.138, the latest weekly. The latest "stable", i.e. LTS, release is 2.121.3, see: <http://pkg.jenkins-ci.org/debian-stable/>. I don't think we want to downgrade 2.138 → 2.121.3 as downgrading may break things. We want to wait for the next LTS release that's newer than 2.138 to come out, upgrade to that, and then stay on the LTS release line from then on.

It looks like 2.121 was released on 7th Jun, so based on their twelve-week cycle I think we can **expect the next LTS next week** (on around Thu Aug 30th). But I **don't know whether the next LTS will be newer than our current weekly version** (2.138), if it's not then we may have to stop upgrading the weekly and wait another 12 weeks for the _next_ LTS after that. **Update**: IRC tells me that the next LTS is to be 2.138.1 which is good news for us.

The question is how do we orchestrate this weekly → LTS transition without losing anything?

### How to migrate to the LTS version

Since I don't think we can do the migration until late next week at the earliest, this isn't urgent. I was unable to find any Jenkins weekly → LTS migration guide for people who've installed it using the Debian/Ubuntu packages as we have. I've [posted a question to Server Fault](https://serverfault.com/questions/927465/how-to-migrate-from-jenkins-week-ubuntu-package-to-lts) and we'll see what comes back. I also pinged the `#jenkins` IRC channel on Freenode about it, as people there were very helpful yesterday.

Note that the Server Fault question just talks about how to do this on Ubuntu, but we have the additional complexity that our Ubuntu servers are supposed to be managed by Ansible. So rather than editing files in `/etc/apt` directly, for example, we probably want to make the relevant edits in the relevant Ansible playbook and then run it.

### How to stop Jenkins notifying us about new weekly releases

Various Google results (e.g. [here](https://stackoverflow.com/questions/28870849/jenkins-move-from-rolling-release-to-stable-lts-release) and [here](https://stackoverflow.com/questions/41452225/upgrade-from-jenkins-weekly-to-lts?noredirect=1&lq=1)) suggest that Jenkins may still continue to notify us about new weekly versions to upgrade to after we've migrated to the LTS version, and that deleting Jenkins's upgrades folder might fix it.

### Jenkins LTS Changelog

Here's the [Jenkins LTS Changelog](https://jenkins.io/changelog-stable/) (and [RSS feed](https://jenkins.io/changelog-stable/rss.xml)) so we can watch out for the next LTS release.

**Comment by seanh** [comment]
## Size (instance type) of `support` machine

### Decision

Based on the notes below I'd recommend we **go back to our old `t2.large` and monitor its performance** (update: done), if it seems resource constrained we can consider upgrading to `t2.xlarge` or `t2.2xlarge`. But see note below about moving to the new T3 instance types.

### Notes

Before this incident began `support` was a `t2.large` instance. As part of getting Jenkins working again we upgraded it to an `m4.10xlarge` which is surely overkill.

Here's the [current EC2 pricing by instance type](https://aws.amazon.com/ec2/pricing/on-demand/). For simplicity I think we should stick within the "general purpose" instance types just because there are a lot of different instance types and because moving from one instance type to another isn't always trivial depending on the instance type. Although there are also compute optimized, GPU, memory optimized, and storage optimized instance types, and maybe one of those (probably compute optimized) would be more appropriate for Jenkins? But sticking with general purpose:

![screenshot from 2018-08-22 11-37-57](https://user-images.githubusercontent.com/22498/44458987-e4487f00-a5ff-11e8-8b87-66a4d974c640.png)

During the incident we discovered that changing to certain instance types requires installing [ENA](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html) support on Ubuntu, which we don't want to do, so lets simplify things / restrict our options further by just ruling out any instance types that require ENA:  C5, C5d, F1, G3, H1, I3, m4.16xlarge, M5, M5d, P2, P3, R4, R5, R5d, T3, X1, X1e, and z1d.

So I believe that leaves us with these choices, including the `t2.large` it was previously on:

| Type | vCPU | ECU | Mem | Storage | Price |
| ---- | ---- | --- | --- | ------- | ----- |
| **t2.large** | **2** | **Variable** | **8 GiB** | **EBS Only** | **$0.0928 per Hour ($812.93 per year)** |
| t2.xlarge | 4 | Variable | 16 GiB | EBS Only | $0.1856 per Hour ($1625.86 per year) |
| t2.2xlarge | 8 | Variable | 32 GiB | EBS Only | $0.3712 per Hour ($3251.71 per year) |
| m4.large | 2 | 6.5 | 8 GiB | EBS Only | $0.10 per Hour ($876 per year) |
| m4.xlarge | 4 | 13 | 16 GiB | EBS Only | $0.20 per Hour ($1751 per year) |
| m4.2xlarge | 8 | 26 | 32 GiB | EBS Only | $0.40 per Hour ($3504 per year) |
| m4.4xlarge | 16 | 53.5 | 64 GiB | EBS Only | $0.80 per Hour ($7008 per year) |
| m4.10xlarge |	40 | 124.5 | 160 GiB | EBS Only | $2.00 per Hour ($17520 per year) |

Combining this with [info about the instance types](https://aws.amazon.com/ec2/instance-types/) I'm thinking we want to stay on a `t2.*` instance type, and not move to an `m4.*`, because the T2's offer burstable CPU performance and the M4's don't. That leaves us with the choice of going back to our previous `t2.large` for $812.93 per year or upgrading to a `t2.xlarge` for $1625.86 per year or a `t2.2xlarge` for $3251.71 per year. The price per year jumps quite a lot as you upgrade.

#### T3 instance types

Amazon just [announced its new T3 instance types](https://aws.amazon.com/ec2/instance-types/t3/) which are similar to the T2s but o newer hardware (so presumably faster) and cheaper. We could move from our current `t2.large` to `t3.large` and get better performance for less money.

Unfortunately when you try to start up `support` as a `t3.large` you get this error message from AWS/EC2:

> Error starting instances
> 
> Enhanced networking with the Elastic Network Adapter (ENA) is required for the 't3.large' instance type. Ensure that your instance 'i-***' is enabled for ENA.

We would need to spend the time to check whether `support` has ENA enabled and, if necessary, enable it. Once we have the time to do that, though, there seems no reason not to change it to a `t3.large`.

| Type | vCPU | ECU | Mem | Storage | Price |
| ---- | ---- | --- | --- | ------- | ----- |
| t3.large | 2 | Variable | 8 GiB | EBS Only | $0.0832 per Hour ($728.83 per year) |
| t3.xlarge | 4 | Variable | 16 GiB | EBS Only | $0.1664 per Hour ($1457.66 per year) |
| t3.2xlarge | 8 | Variable | 32 GiB | EBS Only | $0.3328 per Hour |

#### Unlimited Mode

We may also want to consider enabling unlimited mode (unlimited CPU bursting) if we seem to be limited: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html

**Comment by seanh** [comment]
I've created a [card for upgrading `support` to 18.04](https://github.com/hypothesis/product-backlog/issues/762). As you can see I think we can get a few birds with one stone by doing that, and it will take care of the remaining open issues on this card. Closing this card now.
