### ISSUE TITLE
Use aria labels for sort options in client

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#779]
Part of https://github.com/hypothesis/product-backlog/issues/753. 

## Requirements

- [ ] Add `aria-label="Sort annotations"` to `button` element
- [x] Add `aria-haspopup="true"` to `button` element
- [ ] Add `role="radiogroup"` to `ul`
- [ ] Add `role="radio"` to each `span` within the `li`
- [x] Add `aria-checked` state to each ~~radio element~~ menu item (Location is the default option, so that will be set to `true` while the others will be `false`
- [ ] Add `aria-labelledby` attribute to associate the radio elements with their labels.

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 2 | 1 | 3 |

**Comment by lyzadanger** [comment]
Since the a11y assessment was performed, menu elements in the client have changed markedly, for the better. Some of the TODOs are therefore done, but a few of them are implemented in slightly different ways so I wanted to walk through them.

* Add `aria-label="Sort annotations"` to `button` element — we have a `label` attribute on the `button` now, but not an `aria-label`. This will require changes to the `Menu` component (not specific to the sort menu) if we want to address it...
* Add `role="radiogroup"` to `ul` — There is no `ul` anymore. The containing div for all of the options already has a role of `menu` (from the `Menu` component) so I'm not sure if there's action to take here.
* Add `role="radio"` to each `span` within the `li` — No `li` anymore, but these divs already have a role (`menuitem`), so we'd want to consider this carefully. This applies to the `MenuItem` component, not specific to the `SortMenu`.
* Add `aria-labelledby` attribute to associate the radio elements with their labels. — No radio buttons anymore, so I think this requirement is probably invalid now.

Summary:

* Some of the TODOs here are de-facto done thanks to a11y improvements in client components
* The TODOs that are not done involve some discussion and would apply to generic/reusable client elements (not specific to sort menu).

**Comment by ajpeddakotla** [comment]
Closed in favor of #1085
