### ISSUE TITLE
Handle url queries w/o needing httpx

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#796]
### Problem you are trying to address with this feature

As currently implemented, users and devs need to know to enter httpx:// in front of url queries to the API or activity pages.  This likely hasn't been a problem (w activity pages) up until now b/c frankly the utility of querying a single URL is fairly low.

With the wildcard capability in flight at https://github.com/hypothesis/product-backlog/issues/30 the utility will change significantly.

### Your solution

Enter httpx:// for them if not present.

w/ the API it's not as big a deal, since the API will usually be programmed, and it doesn't cost much to prepend the required bit once when you're crafting the routine.  But for activity pages, it would be nice if folks didn't always need to enter this every time. (let's always save the need to type useless chars for folks.)  At a minimum the instructions in activity pages need to reflect this requirement if it remains, because folks will often not realize they need to enter it.

**Comment by hmstepanek** [comment]
I did some preliminary investigation on this a couple days ago. It's easily done for urls like http://example.com/foo. It's not easily done for urls like server:port/foo. The way I was looking at implementing this was to pass it into urlparse and if it's missing a scheme (aka http/https) add it but for urls of the second class urlparse thinks the scheme is server. And you might think just append it to everything that doesn't start with http but what about doi urls or urn urls? There isn't a consistent way to do this for all urls which is why it's difficult. It could be we just decide we'll support it for example.com urls. The following branch does just that.

See branch [here](https://github.com/hypothesis/h/tree/automatically-add-protocol-if-missing).

If you think that's a good enough first pass at this I'll make a PR for it and we can release it, if you would like to do some more investigation into how to support all urls then this will have to be scheduled/prioritized into the sprint.

**Comment by judell** [comment]
> for urls of the second class urlparse thinks the scheme is server

I'm not seeing that:

```
>>> urlparse.urlparse('http://example.com/foo/bar?baz=97#abc')
ParseResult(scheme='http', netloc='example.com', path='/foo/bar', params='', query='baz=97', fragment='abc')
>>> urlparse.urlparse('http://example.com:8080/foo/bar?baz=97#abc')
ParseResult(scheme='http', netloc='example.com:8080', path='/foo/bar', params='', query='baz=97', fragment='abc')
```

> See branch here.

Seems like doing this in `uri.py` would also require more investigation. Here's a deduped set of interesting (!) patterns in our data:

```
"http://next.gazeta.pl/next/7,"
about:reader?url=http://blogs
blob:https://mozilla.github.i
chrome-extension://bjfhmglcie
content://com.android.provide
example.com
file://///Virt003/austausch_d
file:///C:/D2L/learning/hypot
file:///home/darko/Zotero/sto
file://localhost/Users/Adam/Z
ftp://ftp.gnu.org/old-gnu/Man
http://0-content.ebscohost.co
https://*/*
https://.gitbook.io/advanced
https://0-academic-oup-com.ar
urn:x-pdf:00010750c94d8e478a4
[object Object]
```

**Comment by hmstepanek** [comment]
You have to test w/o the protocol since if it had the protocol that would defeat the purpose of trying to automatically add it. 
```
>>> urlparse.urlparse("server.com/path")
ParseResult(scheme='', netloc='', path='server.com/path', params='', query='', fragment='')
>>> urlparse.urlparse("server:3000/path")
ParseResult(scheme='server', netloc='', path='3000/path', params='', query='', fragment='')
```

**Comment by judell** [comment]
Duh. Of course, sorry!

**Comment by dwhly** [comment]
>  It's easily done for urls like http://example.com/foo. It's not easily done for urls like server:port/foo

Since presumably we'll still support specifying the http:// or https:// formats, i personally don't see an issue if http:// is required for any URL that specifies a port.  We can probably put that into a kb file somewhere.  I bet that H devs testing against localhost:3000 probably represent 99.9999% of our :port queries. :)

**Comment by robertknight** [comment]
This was implemented in h by https://github.com/hypothesis/h/pull/5443
