### ISSUE TITLE
Allow "?" inside the domain of uri's for activity pages

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#810]
To complete the [uri wildcard work](https://github.com/hypothesis/product-backlog/issues/30), we need to enable the ability to have `?` inside the domain of uri's for this query. 

This is so urls that worked previously like https://example.com?foo=bar still work rather than the user having to move the query after the domain like https://example.com/?foo=bar.

Since supporting `*` in the domain is a more complicated problem to solve (because it requires identifying a TLD and urlparse has no support for this) this will not be covered.

**Comment by robertknight** [comment]
Hi Arti,

We've solved the main problem outlined in the linked issue (return all the annotations on my website). It was an explicit decision not to support wildcards in the domain due to concerns about performance [1].

Depending on the reason _why_ someone might want to do wildcard searches in the domain we might prefer to suggest other options.

For example, if the use case is a publisher wanting to fetch annotations from a number of different-region sites they maintain with different TLDs or subdomains (`https://en.wikipedia.org`, `https://fr.wikipedia.org`) they can simply combine multiple `wildcard_uri` queries in their search. For example: [annotations from French _or_ Spanish-language wikipedia](https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Ffr.wikipedia.org%2F*+url%3Ahttps%3A%2F%2Fes.wikipedia.org%2F*).

[1] In absolute terms, a query like `https://*.wikipedia.org` doesn't currently take long (a few hundred ms) because the cluster has a lot of CPU and memory relative to the current size of the search index, but it uses the index very inefficiently and we would have problems if such queries were frequently executed.

**Comment by hmstepanek** [comment]
@robertknight I asked @ajpeddakotla to add this because without this, it breaks urls that worked before which I think is a problem and as some other people on the team pointed out it's not intuitive without this support. I'm thinking tentatively what I'm going to do is route any queries with ? in the domain to the non-wildcard filter and allow a * in the domain but only at the end.

**Comment by robertknight** [comment]
Hi Hannah - I think my understanding of what is meant by this issue is different than yours. Can you clarify with some examples? In particular what did you mean by "breaks URLs that worked before"?

**Comment by hmstepanek** [comment]
I've provided an example in the description-let me know if that's not clear or it needs more explanation.

**Comment by robertknight** [comment]
Right, that's definitely not what I understood from the initial description. So my understanding is there are two issues:

- URLs containing "?" wildcards are now ambiguous (Does the "?" mean a wildcard or a query string?) and thus interpreted differently than before. _However_ a "?" _will_ match a literal "?", so actually is this a problem? For example, here is a URL that was recently annotated in Public containing a query string: https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fwww.dropbox.com%2Fs%2Fjznf89m2yndvecu%2FFuentes%2520%255BDisposessed%2520Lives%255D.pdf%3Fdl%3D0
- You think it might not be obvious how to search for all annotations on a given domain?

Do I understand correctly?

**Comment by hmstepanek** [comment]
> However a "?" will match a literal "?", so actually is this a problem?

This isn't specifically the problem here. It is a problem because all ? are currently treated as wildcards and since wildcards are not allowed in the domain those urls are invalid urls. It's not that the ? will not match correctly, it's that it is not allowed inside the domain and so all urls with queries as part of the domain will be ignored/stripped from the search query. 

Yes to the second bullet point.

**Comment by judell** [comment]
I think @hmstepanek reported elsewhere, and I just verified for myself, that there are (and will continue to be) a _lot_ more `target_uri` with `?` (300k) than with `*` (7k). That's one reason why I've proposed dropping the single-character wildcard.  `*` is an essential feature. `?` is a nice-to-have that arguably doesn't justify its cognitive overhead relative to a namespace in which `?' is common.

**Comment by robertknight** [comment]
Can this issue be closed now @hmstepanek?
