### ISSUE TITLE
Investigate why fetch_annotations is so slow

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#811]
Part of the research is documented here: https://docs.google.com/document/d/1gwcLAUbogRJ95tTW0tbxSonDim7itolqUVnLow-USyw/edit#heading=h.3de8xgxrwmfo

fetch_annotations appeared to be slow but not due to the postgres calls and this requires further investigation into it's implementation.

**Comment by hmstepanek** [comment]
It looks like sqlalchemy is taking a long time to generate the query. 
![image](https://user-images.githubusercontent.com/30059933/46701882-1163e780-cbd6-11e8-85ca-2a77005d6ab5.png)

The query itself is very fast but it's spending a lot of time in python generating it. One note here is that we are passing a subquery for the purpose of pre-fetching the document info for each annotation. This blog post seems like it might have some relevant info about how to speed this up; https://engineering.shopspring.com/speed-up-with-eager-loading-in-sqlalchemy-87a176cfd7ad. 

Another note here: it may be more ideal to sort the annotations inside the db instead of python. A quick test locally reveals that the sorting in python for 200 annotations takes ~52ms to run. Perhaps something like: SELECT * FROM foo WHERE id IN (3, 1, 2) ORDER BY array_position(ARRAY[3, 1, 2], id);

**Comment by robertknight** [comment]
Hi @hmstepanek - I'm finding that screenshot you posted above very difficult to read. Can you explain what I should be looking at?

> A quick test locally reveals that the sorting in python for 200 annotations takes ~52ms to run.

Which code are you referring to and how did you measure it?

**Comment by hmstepanek** [comment]
The h/storage.py:fetch_annotations (specifically these two lines):
```
    ordering = {x: i for i, x in enumerate(ids)}
    ...
    anns = sorted(query, key=lambda a: ordering.get(a.id))
```
This was timed by creating 200 annotations and calling this function with the load documents query_processor (just as we do in activity pages) 1000 times with those lines vs 1000 times w/o those lines and taking the average. Note if we didn't have to sort the results we wouldn't need those lines. This isn't exactly what timeit uses. Timeit recommends using the min number but when it's consistently that much off I think it's a reasonable estimation regardless. I also ran these comparisons several times just to be sure I wasn't running something that locally impacted the timing. 

The screenshot above it is the output from cProfile sorted by cumulative time. You'll notice sqlalchemy consistently shows up in the top 10. The function took a total of .121 s to run but .099 s of that was spent in the sqlalchemy query. This is also what NR was indicating. The query sqlalchemy actually ended up running was very fast but the time spent in python generating that query took a long time.
