### ISSUE TITLE
Spike: Technical implementation plan for work to share and unscope groups

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#844]
### Problem
Publishers, communities, and other users want to be able to share annotations in restricted groups with others, so that users who are not members of those groups can see the annotations that have been made in those groups.

Currently there is no way to share a direct link to a group's annotations in the client, and open and restricted groups have a restriction that they must be scoped to sites in order to appear in the client. 

### User Stories

1. As a member of a group, I want to see that group available to me on all web pages—not just those that match my group’s scope—so that I am able to annotate within that group anywhere on the web.

2. As a user, I’d like to be able to create a link to view annotations for a document made by a specific, group, even if I am not a member of that group.

3. As a member of a group, I’d like to be able to share a link to a document with non-members, so that those users may view the annotations made for that document within my group.

4. As a user, I'd like to be able to follow a link to a group and view annotations made in that group, on a specific document, and see the group appear in my group scope dropdown on the sidebar. If I am a member of that group, I expect that group to appear on my groups list. If I am not a member of that group, I expect that group to appear as part of a seperate "featured" list (terminology TBD). 

### Current Issues
https://github.com/hypothesis/product-backlog/issues/635 - user story 1
https://github.com/hypothesis/product-backlog/issues/855 - user story 2
https://github.com/hypothesis/product-backlog/issues/748 - user story 3
https://github.com/hypothesis/product-backlog/issues/848 - user story 4

### Spike: 
This ticket outlines the technical implementation plan for the two user stories defined above. The goal is to have a clear, defined, and ready-to-implement plan by the end of this sprint. 
Documentation from QDR is here: https://docs.google.com/document/d/19Ev7TPWOhfYh2ePC9utejXxWwpY4P7vwemybqJB_D6Y/edit
https://docs.google.com/document/d/11vR18B_XMa0LB2d6vXSm1JXjA-iAYqEf_nI1FoHY5nc/edit

**Comment by ajpeddakotla** [comment]
Questions/thoughts to clarify (from our discussion): 

1. Should the group still be scoped to always appear on specific sites in addition to being unscoped, so that it can appear on any site? The long term direction is to ease the requirement on scopes, but perhaps an intermediate step is to allow both. 

2. Perhaps move from a scope -> privilege nomenclature to describe the changes we're likely to make? 

3. Should we implement this on a group by group basis, or for all groups writ large? Should the changes we're making to scoping requirements impact all restricted and open group that have been created in the database? 
Dan suggested a potential setting on the group: "restrict to scope(s)" or something like that

**Comment by lyzadanger** [comment]
Apologies that I didn't notice this sooner, but I'm trying to assess whether the short-term requirements really do encompass open and private groups. The core thrust of what they need seems to be related to restricted groups, and I'm having trouble envisioning how the flow would work for open groups. And private groups are a whole 'nother ball of wax. 

Open groups, maybe doable with more definition? Private groups are a big undertaking, so I'd suggest we'd need to regroup if those are in the mix.

cc @dwhly @ajpeddakotla @robertknight

**Comment by lyzadanger** [comment]
I'd like to propose that we continue using this issue as the spike-tracking issue but when we've got a development and user-experience plan, we open a new ticket to serve as an epic for the development phase, with the appropriate user stories, e.g., copied over.

**Comment by robertknight** [comment]
Some initial thoughts from me about the implementation: https://gist.github.com/robertknight/d393654da17ea3e5f23a0cfb7d5fa860

**Comment by dwhly** [comment]
A note:

Presumably as part of this work the share link in the sidebar, which was upgraded a while back to a bouncer link, would be further modified to include whichever group the sidebar is currently scoped to.  Also, presently, the "Visit annotations in context" link in activity pages links to the first annotation displayed in the returned list--specifically because previously we had no way to pass group terms through to the client, but we realized that specifying a specific annotation that was in a group had the happy side effect of properly changing the group control.  Using a link to the first annotation was thus a hack we used until the feature we're envisioning here was developed.  The downside of using a link to an annotation is that only that single annotation is selected in the sidebar, even though the wording says "Visit annotations *(plural)* in context".  This was an inconsistency we decided to tolerate until a more effective implementation was possible.

Using one of these two links-- and most likely the one in the sidebar, with it's handy UI-- will be the only handy way an average user will have of obtaining the proper bouncer syntax to share a link to a page w/ the appropriate group focused.  (Possibly we might want some small text under that share link to say something like "This link will bring users to this page with [group name] focused" or something so that it's clear to them.)

I *think* the workflow here for sharing should be identical across group types-- open, restricted, private-- unless I'm missing something.  In other words, you discover a page with compelling annotations within, say, an open group.  You want to share all these annotations with someone else (rather than a specific link to a particular annotation), and therefore you grab the page share link (vs an individual annotation direct link) and paste it into an email, twitter, etc. The receiving party clicks on it, is taken to the page and has the client scoped to the appropriate group. (Yes, for private groups you'll need to be a member, and if a private group term was passed into the client for a user who did not have permission / was not logged in, then we'd want to show a message of some sort saying that there was a permission error, and if they were not logged in to perhaps suggest that they do.)

**Comment by lyzadanger** [comment]
@dwhly I think the things you are mentioning are valid and reasonable ideas, but that some (e.g. shareable links into private groups) fall outside of the scope of this feature (that we need to ship quickly for QDR). The scope of the QDR work is encompassed in the three user stories currently in this issue's description. If we've got the user stories wrong for this feature, let's discuss!

**Comment by robertknight** [comment]
Lyza, Dave and myself had a meeting today to discuss an implementation plan. The summary is contained in this Gist: https://gist.github.com/robertknight/d393654da17ea3e5f23a0cfb7d5fa860

The rough breakdown of work involves:

- A change to bouncer to support specifying a group to go to as well as a URL
- Reading that group in the client and using it a) request that group from the API explicitly and b) focus that group instead of whatever other group would have been focused
- An API change to expose to clients whether the user is a member of the group or not
- A new API to fetch details of a group given its ID
- Changes to the groups menu in the client to indicate which groups the user is a member of and which are "featured" (associated with the page or were direct-linked)
- Reasonable failure behaviour in the client if the group cannot be fetched for any reason

Dave has already made a start on designs for changes to the groups menu in the client and will write those up separately.

We will flesh this out in finer detail as we make a start on these in a future sprint.

@dwhly the work we are doing here will go some way towards the work that we need to do for the two issues you mentioned, but there is some additional work needed for those specific items beyond just changing a link in a template. As a small example, it is possible for a bucket of annotations on activity pages to contain annotations in multiple groups, so we need to do something reasonable in that case.

**Comment by dwhly** [comment]
> @dwhly the work we are doing here will go some way towards the work that we need to do for the two issues you mentioned, but there is some additional work needed for those specific items beyond just changing a link in a template. 

@robertknight Is it appropriate to add two issues focused on those particular (separate) requirements?  i.e. one for the share link in the client, and one for the link in activity pages?  If so, I can create.

> As a small example, it is possible for a bucket of annotations on activity pages to contain annotations in multiple groups, so we need to do something reasonable in that case.

Excellent point, thank you.  A good reminder that we need that "All scope" at some point, i.e. "Everything I have permission to see".  https://github.com/hypothesis/product-backlog/issues/167

**Comment by klemay** [comment]
I'm adding this comment but not re-opening the issue only to capture a question/concern I brought up in Slack. **I don't expect devs to respond or even change the course of their work as the result of this comment**, just capturing it here in case it is useful later.

This QDR user story for restricted groups seems to conflict with the existing restricted groups user story for publishers/website owners.

As a publisher/website owner: 

- I want branded layers which show up by default on my site
- I want control over what sets of documents (scopes) group members may annotate

It looks like that second item will be taken away by this QDR work. This is in contrast to how we've explained restricted groups to some of our partners who already have them, so we might need to rethink how we advertise/explain these (and perhaps follow up with some partners with existing integrations).

**Comment by ajpeddakotla** [comment]
Reopening this issue as @dwolfe @dwhly and I have been having further discussions around it to refine the user stories and requirements.

**Comment by ajpeddakotla** [comment]
Closing this as work has been broken down
