### ISSUE TITLE
Move /assets to nginx

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#879]
/assets are static and they are best served from nginx directly as opposed to python. This will do 2 things: 
1. The /assets endpoint will be faster.
2. The load on the server will be decreased and it will free up gunicorn to be used for other requests.

in h/conf/nginx.conf add something like:
```
    location /assets {
      add_header 'Access-Control-Allow-Origin' '*';
      root /build;
    }
```

**Comment by hmstepanek** [comment]
As part of this work the rate limiting needs to be removed for this particular endpoint.

**Comment by robertknight** [comment]
The [transactions table in New Relic](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions/table?type=app#sort=8%2C1) suggests that the number of asset requests that actually reach the server is pretty small (see `h.assets:wrapper` in that table), because the assets get cached for several hours by Cloudflare. If a change is proposed to make something faster, its always useful to see some relevant numbers if possible.

If it turns out to be as simple to serve static assets from nginx as the issue description suggests then we might as well. However this does introduce a small dev <-> QA/production difference.

**Comment by seanh** [comment]
Does nginx run in dev environments at all? I think the dev envs just run gunicorn directly, so moving assets into nginx might break dev envs?

**Comment by hmstepanek** [comment]
It runs in docker in the dev env. That's a good point, no we don't run nginx when running make dev. We could move it into nginx without really touching the python code-maybe that's gonna leave us in a duplicative state with python and nginx serving files so that doesn't make sense until we are running nginx via docker-compose? Right now we are rate limiting assets and I'd like to get rid of that by serving the files statically which is the industry standard for this sort of thing but perhaps we need to fix the way we run our local env before we take this on.

**Comment by robertknight** [comment]
We could continue to serve assets from gunicorn as a fallback. We just need to make sure that we're not relying on any middleware/tweens in the Pyramid app modifying static asset requests.

I have to re-iterate my point above though, that the amount of traffic to the assets endpoints appears to be very low in production due to caching in front of the app, so if it looks like this is going to be complicated it might not be worthwhile making this change.
