### ISSUE TITLE
Add New Relic metrics to activity pages

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#880]
Add metrics to record activity page usage (we need metrics on how users are using search and also a userid to attach to the request in NR just like we have for the api requests which will help us track request rate info).

**Comment by seanh** [comment]
I'm wondering _why_ we need metrics on how users are using search and also a userid? What problem(s) do we have that we're trying to solve here? And then why are New Relic metrics the right solution to this problem/these problems?

Not saying NR metrics aren't the right thing to do here, just that describing the problem we're solving would help me and other developers (who lack the context of whatever project this issue is part of) to understand things

**Comment by dmfine** [comment]
Hannah demo'd it this morning!
