### ISSUE TITLE
Groups control no longer functional w/ FF bookmarklet

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#881]
### Steps to reproduce
1. Go to a PDF using Firefox 63.0.3 or later (https://arxiv.org/pdf/1606.07192v1.pdf)
2. Activate the H bookmarklet

### Expected behaviour
Annotations should show up in the Public group, you should be able to see groups in the dropdown.

### Actual behaviour
Group control is non-functional

### Browser/system information
FF bookmarklet.

### Additional details
![screen shot 2018-11-16 at 3 10 34 pm](https://user-images.githubusercontent.com/1413074/48651900-c9449b80-e9b1-11e8-8cd1-a41c32351044.png)

**Comment by dwhly** [comment]
![screen shot 2018-11-16 at 3 52 24 pm](https://user-images.githubusercontent.com/1413074/48653112-cf3d7b00-e9b7-11e8-8e84-2452832cf4a7.png)

As reported on our open slack channel today... ^

**Comment by dwhly** [comment]
Additional note, make sure you're on most recent FF 63.0.3 or later.  That's where this started showing up per @hmstepanek

**Comment by robertknight** [comment]
I was not able to reproduce the issue this morning in Firefox 63.0.3 when using Via (https://via.hypothes.is/https://arxiv.org/pdf/1606.07192v1.pdf) but I was able to reproduce it by loading the production bookmarklet into a tab showing the PDF directly using PDF.js' internal viewer https://arxiv.org/pdf/1606.07192v1.pdf.

The difference here is that different versions of  PDF.js are being used. My guess is that Firefox 63 contains a newer release of PDF.js with an API change and our PDF integration will need to be updated.

In the meantime, the following workarounds are possible:

1. Visit the PDF using Via
2. For publishers embedding the client, continue to use a version of PDF.js that is supported.

**Comment by robertknight** [comment]
Stepping through a load right now I found a different issue which looks like an unrelated (and non-fatal) bug. The polyfill added in https://github.com/hypothesis/client/pull/794 fails to detect that the native `NodeIterator` can be used. In this code in the `dom-node-iterator` package:

```js
function createNodeIterator(root, whatToShow = 0xFFFFFFFF, filter = null) {
  const doc = root.ownerDocument
  return doc.createNodeIterator.call(doc, root, whatToShow, filter)
}
```

This function is called with `root` being an `HTMLDocument` and [`ownerDocument` is null](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument) when called on a document, rather than an element.

**Comment by robertknight** [comment]
Found the problem. [This commit](https://github.com/mozilla/pdf.js/commit/e522b2d87e8eb3d4eb8a391a098a0f6f157e8c12) removed the `window.PDFViewerApplication.documentFingerprint` property, which the client [uses](https://github.com/hypothesis/client/blob/c5f85bdbf4e7adb262c13e978b8b676f374941e0/src/annotator/plugin/pdf-metadata.js#L44) to detect when the PDF has loaded and the necessary metadata can be read from the PDF in order to search for annotations.

In both the version of PDF.js that we use in Via and the current version in Firefox, this data is available via `window.PDFViewerApplication.pdfDocument.fingerprint` instead. Note that `PDFViewerApplication.pdfDocument` is null while the document is loading. Looking at PDF.js' tests and the commit message, this looks like more publicly supported API which we should be depending on instead.

**Comment by robertknight** [comment]
The reason this issue "breaks the groups control" is because the client delays fetching groups and annotations from the API until the document is loaded and so the necessary metadata for searching is known. Due to this API change in PDF.js, the client thinks that the PDF hasn't finished loading yet, so it gets stuck forever in a waiting state.

**Comment by SteelWagstaff** [comment]
@robertknight -- thanks for your sleuthing on this! Quick question for you. Naomi and I have been experiencing this issue on our Wisconsin Pressbooks network, which is running your fork of the H client that supports H5P embedding. Will this fix, once shipped, work there, or will we need to have you update that fork/branch so that it's up to date with the main client again?

**Comment by robertknight** [comment]
Hi Steel,

Since the H5P support is [still in a fork](https://github.com/robertknight/client/tree/h5p) it did need updating separately, I've done this locally and updated the deployed H5P version. This served as a reminder that I need to talk to the rest of the team again about upstreaming this!
