### ISSUE TITLE
Spike: decide how to roll back a bad prod release

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#886]
Our current roll back methodology of creating a revert commit, releasing it to qa, and then prod means production may be down for ~40 min which is not acceptable.

Scope: This is limited to releases that can be rolled back simply by re-deploying the previous version. (Aka: no dependencies.)

Deliverable: Decide how the team would like to handle this keeping in mind the goal is as little down time as possible when an incident like this occurs.

**Comment by seanh** [comment]
I don't think we should do this.

We already have a way of deploying an older version of an app:

![Screenshot from 2019-04-24 12-29-41](https://user-images.githubusercontent.com/22498/56656161-a7e88980-668c-11e9-9a6a-a24971d6d3c1.png)

1. Go to the ["deployment" Jenkins project](https://jenkins.hypothes.is/job/deployment/) and manually invoke a new build ("Build with Parameters" in the sidebar).
2. Fill out the parameters:
   1. `APP` - the application you want to re-deploy (e.g. "h", "bouncer", etc.)
   2. `TYPE` - choose "deploy"
   3. `APP_DOCKER_VERSION` - enter the version number string from the app's repo on [Docker Hub](https://hub.docker.com/u/hypothesis/) (they're under the **Tags** tab on each app's Docker Hub page)
   4. `ENV` - choose the environment, either "prod" or "qa".
3. Start the build.

However I would **strongly recommend against doing this** as a way of attempting to roll-back a problematic release because the consequences of doing this would be unpredictable. I think the assumption that we always roll forwards and always deploy newer releases is likely implicitly baked into our deployment scripts and set up, and maybe also into Elastic Beanstalk itself, and I don't know what would happen, but for example I think the release that you have rolled back is likely to get automatically deployed again in the near future.

It's definitely the case that if production is broken there are all kinds of difficult-to-see ways that rolling back a release could break it even more.

This isn't a problem that can be fixed by redesigning our deployment scripts either. It's just reality that you can't in general safely roll back a release. Please read [You Can’t Have a Rollback Button](https://blog.skyliner.io/you-cant-have-a-rollback-button-83e914f420d9) and think about it carefully.

Instead, if a bug has been deployed to QA or production, **the recommended procedure is to roll forward:** Make a new commit that fixes the bug, maybe even reverting the previous commit if that works, push that commit to GitHub creating a new version, deploy the new version to QA, test, deploy to production.

I'm aware of the objection that the above roll forward procedure takes longer and people want an immediate rollback button in case production is broken but please read [You Can’t Have a Rollback Button](https://blog.skyliner.io/you-cant-have-a-rollback-button-83e914f420d9), and I recommend employing other techniques including:

* Unit tests, functional tests, linting and CI
* Careful local testing and code review
* Small commits and PRs, which improve the effectiveness of local testing and code review, and can also be deployed one-at-a-time in small, low risk deploys
* **Use feature flags**, which can be toggled on and off instantly without any roll back or roll forwards deployment, and the effects of toggling a feature flag are _much_ easier to reason about than the effects of rolling back the diff of one or more commits. This is much less likely to go badly wrong

**Comment by hmstepanek** [comment]
What I am proposing here is a quick way to rollback production to a previous release if it's broken and can be rolled back. I'm not proposing a button, nor am I saying that it has to work in all cases, nor should it be our always use this solution when something breaks, nor should it be a substitute for rolling forward. It is simply a quick way to bring back production when it is down by releasing the previous version. Since we use docker this is very easy to do. Roll forwards has the disadvantage that the developer must come up with a quick fix ASAP and deploy it all the way to production. This is when mistakes are made and often when minor incidents can turn into major ones. Imagine for example that during such an incident github went down, Jenkins went down, or during a simple git-revert some flakey tests started failing and the roll forward procedure was unable to continue (btw that flakey test issue actually happened). The article you've linked to does not take into account SLAs. It doesn't prioritize downtime to customers, as I think it should; first. When the application is down, you need to move fast to get it back up. The rolling forward process puts developers under immense pressure to fix the issue by releasing new code, meanwhile the application is still down for customers. Nothing says devs will make better decisions under pressure and in fact I would assert the opposite it true. During an incident such as production being down the first priority is to get production back up, it's not to make sure master is clean, standard deploy procedures are followed etc. For example in an incident a while back I ran a query that killed queries on our production database. This is a dangerous thing to do and is not at all part of our deployment process. I think we do employ all of those strategies you mention and yet we still have had production outages that could have been fixed in a minute by rolling back to the older versions. Rolling back should be treated as an incident, not a regular deployment procedure IMO: fix the incident (this often entails some initial root cause/investigation to identify how it can be fixed), then cleanup and fully root cause/fix the underlying problem. This is a really great paper I highly recommend reading: https://mvdirona.com/jrh/talksAndPapers/JamesRH_Lisa.pdf Basically assume things will fail against all odds and plan for how you will handle those failures (assuming that multiple things will fail at once).

I think what you've capture above would be a fine solution for a quick re-deploy of the old prod version to fix the outage (assuming of course that it would fix the outage under the circumstances).

**Comment by hmstepanek** [comment]
I'd also add here that if the health check fails on AWS during the deploy of the new version, AWS automatically kills the newly deployed instances and keeps the instances running the previous version up. So we already have an automated roll back built into our deployment process. What I'm suggesting here is simply have a forced rollback in cases where the built in health check/auto rollback on AWS fails to catch the issue.
