### ISSUE TITLE
h Dockerfile build times are too long

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#889]
H's Dockerfile is all out of order with multiple `COPY ..`'s throughout including one right at the beginning. This results in long build times which does affect our release time since docker is not able to take advantage of incremental compile.

I have a branch for this [here](https://github.com/hypothesis/h/tree/fix-incremental-build-of-dockerfile). It's almost complete but there are a lot of changes so we prob will want to make these changes incrementally if we can to avoid confusion.

**Comment by seanh** [comment]
I updated the issue title to describe what I think is the problem this issue is meant to address.

@hmstepanek I guess that long `Dockerfile` build times are one part of the larger problem that is that deploying new code to QA and production takes too long? Since building the Docker image is one of the things that Jenkins does when you merge new code. I wonder if we should have a "Deploys take too long" epic card on which this particular card would be a task list item?

**Comment by hmstepanek** [comment]
Yes they are. We certainly can.

**Comment by robertknight** [comment]
Whoever works on this, can you please add some numbers to this issue to show what the potential improvement is and how that relates to the overall deployment process?

**Comment by robertknight** [comment]
To reiterate my comment above, it's great to see people working on optimizing the CI/CD process as that makes us all more productive. However I would really like to see relevant metrics and perspective to make sure we're spending our time on the right things.

This morning I had a look at [Docker build times](https://jenkins.hypothes.is/job/h/job/master/) on CI and it looks like the Docker image build step typically only takes a few seconds for the majority of builds. Following Dave's recent changes the actual deployment step is much faster so the whole cycle is now pretty decently quick (~10 minutes from merge to QA deploy completed, a further 5-10 to production).

At this stage I would suggest the most impactful thing we could do is to finish migrating to Python 3 so that we're only running test suites once during branch + master builds and only installing one set of Python packages. @seanh you wrote a list of things you wanted to consider before that happened. Perhaps now is a good time to revisit and see what's left and where people can help out? 

Is there anything else left to do here or can we close this issue?
