### ISSUE TITLE
Move our development environments (h, bouncer, via, lms, maybe also client and browser-extension?) into Docker Compose

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#890]
Currently h is not in the docker compose and run separately. This makes the setup more complicated than it needs to be. H should be moved into the docker compose and docker should be used for dev just as it's used in prod. This will also prepare us for moving nginx out of the h docker container and into it's own container which means adding it to docker compose and "depending" on the h container (see https://github.com/hypothesis/product-backlog/issues/884 for details). 

Note the following config needs to be added to the h docker container in order to set pdb break points/etc.
```
        stdin_open: true
        tty: true

```

The second part of this is adding this script/command into the h makefile which will allow us to easily rebuild the container when we make code changes for development and debug.
```
docker-compose -f ./docker-compose.yml build --pull hypothesis-dev
docker-compose -f ./docker-compose.yml -f ./docker-compose.yml up -d --no-deps hypothesis-dev

```

**Comment by seanh** [comment]
Removed the `Operations` label -- since this refers to a change to the development environment I think it's a developer thing not an `Operations` thing.

Also re-titled the card -- We have four Python apps (h, bouncer, via and lms), much work has gone into making the development setup of these four apps the same (and as far as possible making client and browser-extension consistent as well), so any major new development environment changes would have to be done to all of the apps. We wouldn't want h to be different than the others.

**Comment by seanh** [comment]
I don't think we should do this.

If we do decide to do it I think we'd have to explain in more detail what the problems and limitations with our current development environment set up is that this card aims to solve, and list what the requirements for a Docker-based dev env would be.

We currently get a lot of features and functionality from Make and tox-managed development environments (and they also integrate easily with pyenv which is very handy) and we'd want to maintain all of that when moving the dev env over to Docker. That may or may not be possible. It's likely to be a lot of work.

I'm not aware of any big problems with our dev env setup as it is -- It works really well and a lot of work has gone in to getting it to work as well as it does, making it consistent across all our apps,  and documenting it.
