### ISSUE TITLE
Anchoring failure in Elsevier's new reader.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#916]
## Bug report form

Elsevier has rolled out their New Reader to most of their scholarly content.  This takes PDFs and brings them into a page reader in the browser.  It's based on some home grown tech of theirs that does a server side rendering of the PDF document into the DOM.

Using our Chrome extension, the adder is activated when text is selected on the new reader, and indeed when an annotation is made close to the top of the document, the anchoring appears to work.  However, if you scroll down a few pages and make an annotation, it will orphan when you later revisit the reader view of the article.

There's a wrinkle in their current implementation.  After 5 minutes, their gateway will not honor a link to the reader, and will instead redirects back to the HTML view-- where ironically, our direct links will anchor just fine, since citation_doi is used appropriately in both versions.

This means that the links below link to the regular HTML view / abstract page, not the reader view of the article, since they won't persist > 5 minutes.

Elsevier represents a very large percentage of the scholarly content out there.  We need to see if we can address this issue.

### Steps to reproduce
1. To go an article, like this one: https://www.sciencedirect.com/science/article/pii/S2001037014000464#annotations:OdKKDhZ9EemTmmdXeZRJQQ
2. Click "Download PDF"
3. Launch chrome extension
4. (You'll see that there are a few annotations there already, and that 2 out of 4 are orphans)
5. Scroll down a few pages, make a new annotation.
6. Go back to abstract page.
7. Click Download PDF
8. Reload chrome extension.
9. Verify that your annotation has failed to anchor.

### Expected behaviour
Annotations should anchor.

### Actual behaviour
They don't

### Browser/system information
Chrome.

**Comment by robertknight** [comment]
From a little bit of poking around, the PDF viewer appears to be a custom React app which uses a recent version of the PDF.js library to render the content.

Since this is a custom app, it doesn't expose the same globals (`PDFViewerApplication`) that the default PDF.js viewer app does, so the client doesn't detect the viewer as a PDF and loads the standard web page integration. This particular viewer _happens_ to expose certain PDF.js objects which our PDF.js integration code could use, but in general there is no guarantee our PDF.js integration can work with an arbitrary viewer application that uses PDF.js as a rendering library. This means that in order to support custom PDF viewer apps, some viewer-specific logic will likely be needed, even if that logic ends up re-using parts (or most) of the existing code in many cases.

At the moment we don't have a clear separation in the client between the generic parts of Hypothesis and the document format/viewer-specific parts. I would suggest that it would make sense to create that separation with a well-defined interface for their interaction before attempting to add support for additional viewers. Potentially in future it might be useful if the publishers themselves can provide the. logic to enable annotation of content in custom viewers.

**Comment by robertknight** [comment]
It looks like Elsevier might have retired their "new reader". When I go to https://www.sciencedirect.com/science/article/pii/S2001037014000464 I see a "View PDF" link at the top which just links directly to the original PDF. Hence the problem no longer exists.

To be absolutely clear - it is entirely expected that Hypothesis does not automatically work if a site creates a completely custom PDF viewer. That's not a bug, but rather a potentially significant new feature requirement to support such a reader.
