### ISSUE TITLE
Reimplement Via proxy

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#927]
Everyone agrees that VIA needs a rewrite. Research if an off-the-shelf server like HAproxy or Nginx or Apache can be configured to do everything we need. Otherwise, rewrite VIA to be much lighter than it is now.

**Comment by seanh** [comment]
Via actually has quite a few little features hidden in there. I think it might be a good idea to write a list of exactly what requirements **the LMS app needs** for an HTML and PDF proxy. (And I can provide a starting point for that list as I think I have a pretty good idea...) We could then write a new Via to those requirements and begin using it for the LMS app only, leaving public <https://via.hypothes.is/> alone for now. If it works out well for the LMS app, then we can consider whether the new proxy can fully replace Via and what additional requirements (if any) it would need to meet to replace Via.

**Comment by seanh** [comment]
Example of a previously-stated Via requirement that I don't think applies to a Via replacement for the LMS app:

> Pages need to render accurately, we should make sure that ads etc. will still show up like without Via (no cross-domain issues when the HTML and assets load from different domains, etc.)

That's [from Slack](https://hypothes-is.slack.com/archives/C6RS34A3E/p1503387636000063)

(Various other Via requirements and issues discussed in that channel too)

**Comment by seanh** [comment]
See also [SPIKE [4 days]: Research rewrite of Via](https://github.com/hypothesis/product-backlog/issues/307) (Sep 2017) (More Via requirements that we'll be needing are listed in there too)

**Comment by seanh** [comment]
Another [previous Slack discussion about Via and ads](https://hypothes-is.slack.com/archives/C643EDCP2/p1505852358000205):

> ... once we strip Via down to the core -- an H-embedding proxy -- we'll have to wrestle with whether/how to add back the JS monkeypatching without which a minimal Via won't display certain kinds of dynamic content, notably ads. Some of us would argue that can be construed as a benefit, but ClimateFeedback, for example, won't make friends among publishers if their analysis overlays pages from which ads have been stripped.

I think that requirement had also come up earlier (before that Slack discussion). I don't think ad-preserving is needed for the LMS app

**Comment by seanh** [comment]
Probably worth linking to <https://github.com/hypothesis/injecture>, an existing Via replacement written in Go that we already have deployed to Elastic Beanstalk (though it doesn't appear to be working). It'd be cool if we can do a no-app solution (e.g. just an nginx config file) but if we decide we actually need to write an app then Injecture might be worth looking into again. Being written in Go is probably kind of a big maintainability issue for our team though.

**Comment by seanh** [comment]
Thoughts on what to do with this card:

1. We should create a new to **Replace Via for the LMS app** card (but leave via.hypothes.is as-is for the public) and do that first. Because that's gonna be much easier than wholesale replacement of Via. The LMS app's new proxy could then expand to replace via.hypothes.is as well, later.

1. We first need to do a spike to figure out exactly what the requirements for a new Via for the LMS app would be. We should create a separate card for that spike. We can't start a project to replace Via, even just for the LMS app, without nailing down the requirements first.

1. Although we do want to keep it as simple as possible I do think that a new Via is going to be a major piece of new application design and development and is a task for the dev team and David, not just an operations task. I don't think it's going to be doable with an off-the-shelf solution like HAproxy or Nginx or Apache. I would love to be proven wrong! We won't be able to answer this question until we have nailed down requirements.

**Comment by seanh** [comment]
I'm gonna remove the **Operations** label from this because I don't think this is just an ops task (though I'd love to be proven wrong)
