### ISSUE TITLE
EPIC: Define UX for LMS Views

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#934]
Part of #932 
Depends on #933 

This is a biggie: we need to define the UX and flow of the LMS student/teacher activity views. Presumably this will involve rounds of sketching, discussions and workshopping. The outcome will inform the technical plan (what API services need adjustment, what client components can be reused, what new pieces of logic we need, etc.).

- [x] Determine entry points (#933)
- [x] Initial mockups reflecting user stories ([See demo in Slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1553200528000100))
- [x] Onboarding designer
- [x] Initial prototype

**Comment by klemay** [comment]
Before deciding on the UX of the activity view, we should to determine how users will get to that view. We have a few options to consider:

## Option 1: Access from Course Navigation Menu (within LMS iframe)

Some LTI apps (like Google Apps for Canvas) add a menu item to the course navigation menu which leads to the dashboard:

![screenshot-community canvaslms com-2019 02 07-14-46-58](https://user-images.githubusercontent.com/12087705/52438502-6877bb80-2ae7-11e9-96e5-7884c65c5a54.png)

Things to consider
- Might require additional setup steps after Hypothesis has been added to a course site (unless the LTI spec allows for making this happen automatically? Would need to research)

## Option 2: Access from Any Assignment (within LMS iframe)

Flipgrid requires users to open a Flipgrid assignment in order to get to their dashboard. Here's an example where an instructor has created a Flipgrid-enabled assignment, and launched the assignment:

![screenshot-lh4 googleusercontent com-2019 02 07-15-04-57](https://user-images.githubusercontent.com/12087705/52439887-a62a1380-2aea-11e9-9fa7-9740a9fc5591.png)

The dashboard will load within the LMS iframe. 

Things to consider
- Flipgrid only makes the "My Grids" activity view available to instructors, but we don't need to limit ourselves in this way if we don't want to
- Requiring a user to open an individual assignment in order to see course-wide activity could make for a confusing UX

## Option 3: Access from Gradebook (within LMS iFrame)

For each Assignment created with Flipgrid, a Canvas Gradebook item is created. You can see a student's work on that assignment by clicking on a link from within the Gradebook:

![screenshot-hypothesis instructure com-2019 02 11-14-48-04](https://user-images.githubusercontent.com/12087705/52589261-66c23680-2e0c-11e9-9d40-31adef92de59.png)

## [Removed] Option 4: Access from Any Assignment (in new tab/window)
Similar to option 2, but opens a new tab/window instead of loading in the LMS iframe. Was eliminated as a possibility because it's a clunky UX. 

## General notes
- None of these are mutually exclusive— but Option 3 by itself is not ideal (Gradebook doesn't work the same way across LMSes; not all teachers _use_ the LMS-provided Gradebook)
- In an initial conversation with Arti & Jeremy we talked about _combining_ 1 & 2, since both are useful as part of different user flows.
- Next step: sketch out user flows for options 1, 2, and 3

**Comment by klemay** [comment]
We've mapped out [user flows for entry points to the activity view](https://docs.google.com/presentation/d/1QYM7InlOE-ZDOhK5Mvr1TfM3RTCqLP1dK1wy-eP9zB0/edit#slide=id.g4efb06f9ad_0_70). **Note that this only shows how users will _get_ to the activity view, not what will be included in the view or how it will look.** 

Next steps are for Katelyn, Arti, & Jeremy to meet with developers to discuss and confirm that these make sense. (Arti will be scheduling this meeting soon)

**Comment by seanh** [comment]
**In option 1** what happens when the user clicks on Google Drive in the course navigation menu? Does it open the Google Drive dashboard in an iframe inside Canvas?

**For option 1** it looks like the Google Drive app has been installed _in the course_ in order to enable it to appear in the course navigation menu. I wonder how that works if someone installs our app institution-wide rather than into a particular course? Can we still get our app to appear in the course navigation menu in that case?

**For option 2**, if our app is showing an assignment and then there are links that the user can click on to open various activity views, I think it's important when the user does this that the app makes it clear that the user is still "in the assignment" and gives the user a way to make the activity view go away and get back to the assignment.

**The user has no back button** because our app is in an iframe.

One way we could do this is the activity view could open in a dialog that occupies most but not quite all of the iframe and that has a big "X" in the corner to close the activity view and return to the assignment. See what happens when you click in the search bar in Slack, for an example of the kind of thing I'm talking about:

![screenshot from 2019-02-20 12-23-18](https://user-images.githubusercontent.com/22498/53091656-6ad80d80-350a-11e9-8dc2-794ddde1b032.png)

**For option 2** one thing I am asking myself is whether we would enable the following flow and if so how we would prevent this from being really confusing:

1. User browses to Assignment 2 in the LMS, and launches the assignment.
2. The LMS is now on the page for Assignment 2 and has the title **Assignment 2** in big letters above our iframe and in the URL and the breadcrumbs etc. And our app  is showing Assignment 2 in the iframe.
3. The user launches the activity view from the client, looks at their activity, including their annotations from Assignment 1.
4. User clicks on one of their annotations from Assignment 1 and is taken to Assignment 1 (the view showing Assignment 1's document, with the client sidebar embedded in that document)
5. At this point Canvas is in Assignment 2 (page title, URL, breadcrumbs) but our app is showing Assignment 1 in its iframe where Assignment 2 should be. This iframe that contains Assignment 1 is clearly labelled by the LMS's UI as being Assignment 2. This seems really bad.

Would we enable this? Or would annotations in the activity views simply not be clickable, so it's not possible to browse away from the current assignment?

**Comment by jeremydean** [comment]
@seanh: a few answers started to your questions and more questions below:

don't know about google docs, but with flipgrid, it looks like the left nav does take you to an iframed "home page" for the app, where one can in turn navigate to various parts of their flipgrid account and content. 

![image](https://user-images.githubusercontent.com/3261902/53102427-3ad04080-34f1-11e9-9423-6c409654b2a5.png)

you can play with flipgrid and a couple of other apps we've installed in this course if you want to:

https://hypothesis.instructure.com/courses/39/assignments

remember that most LTI apps are simply iframes of that platform. so pretty much any iframed view of the platform, even when scoped to a particular piece of content at first, allows the user to navigate to other content that they have access to in that platform. we're different because you are looking at content not hosted by us with our app on top. 

in terms of would this left nav option appear for course/root installs: i'd assume that it would only show up if the instructor has launched the external tool as part of an assignment, but it's a good question.    

your confusing workflow described at the end above:

it does look like with flipgrid that navigating from within an assignment iframe, does take the user places that aren't related to the assignment. here you see i've navigated in the iframe for assignment "filpgrid 101" but made it all the way to the integrations for my flipgrid account:

![image](https://user-images.githubusercontent.com/3261902/53102012-7cacb700-34f0-11e9-9ca2-0e7024a388d9.png) 

so, i guess that is part of how LTI apps work. but i agree that's it's not a great look, so some questions about the scenario your describe:

why can't the "activity view" navigation (step 2) take them to an "Hypothesis activity viewing page" separate from assignment 2?

and/or why can't navigating to assignment 1 (step 4) actually take them to assignment 1 (rather than assignment 1 in assignment 2's frame)?

is the problem that they have then navigated away from their likely goal, completing assignment 1, and would need to relaunch it to work on it? 

to me it makes sense to have a page navigable in the LMS that allows the viewer to see their out-of-context activity: annotations across a course, annotations across courses. the left nav seems a logical home for such a place. that view of out-of-context activity should be slice and diceable (by group, user, tags, etc.). 

whether users can link to such a page from within an assignment/from the h sidebar and how things are set up for them when they do

**Comment by seanh** [comment]
I actually think it's okay for our app to let users navigate from within an assignment to other parts of our app (for example to various activity pages, or to a user settings page, etc.) I think we should do it in a modal dialog like in the Slack screenshot I showed, or provide some other obvious way for the user to get back to the original assignment, because the user has no back button in the iframe. Even though it appears Flipgrid doesn't do this, I still think it would be good for us to do it. I don't see a problem with this.

But I think the confusion comes in specifically when you can navigate __to another assignment__ from within an assignment. That seems pretty weird. Opening activity pages or settings page etc within an assignment seems fine. Navigating to other assignments and to other annotate-able documents with the client on them, seems bad to me.

**Comment by seanh** [comment]
> why can't the "activity view" navigation (step 2) take them to an "Hypothesis activity viewing page" separate from assignment 2?
> ...
> and/or why can't navigating to assignment 1 (step 4) actually take them to assignment 1 (rather than assignment 1 in assignment 2's frame)?

Unfortunately our app just can't do either of these because it's in an iframe. We can't change what Canvas page the user is on

**Comment by seanh** [comment]
> is the problem that they have then navigated away from their likely goal, completing assignment 1, and would need to relaunch it to work on it?

I think that is a problem but I think the modal-dialog-with-a-close-button (see Slack screenshot) or some other kind of "way back to the original assignment" that our app provides them can solve that

**Comment by klemay** [comment]
> **For option 1** it looks like the Google Drive app has been installed _in the course_ in order to enable it to appear in the course navigation menu.

Not necessarily! LMSes (and I believe the LTI spec) allow for "placements" to be set. LMSes allow a single app to have multiple "placements" - for example, Flipgrid in our Canvas instance is allowed in the left nav menu and within Assignments. Currently Hypothesis' placements are Assignment Selection and Link Selection for Canvas— we'd need to enable "Course Navigation" as a possible placement.

> I wonder how that works if someone installs our app institution-wide rather than into a particular course? Can we still get our app to appear in the course navigation menu in that case?

This shouldn't be a problem. We might look into whether institution-wide installs can _prevent_ our app from automatically appearing in the course nav menu, though.

**Comment by seanh** [comment]
This research is really useful. I had assumed that a Canvas admin or instructor would have to create the placement of our app in the navigation menu. But it sounds like our app can create the placement itself, which is great. We need to find out exactly how an app creates a placement though.

I'm concerned that it _may_ be that, while we can make new installs of the app create the placement, existing users of the app will not get the placement unless they reinstall it, which would be a pain but not a showstopper problem.

Whether or not this is a problem depends on how an app has to create a placement for itself in LTI. But I think it _might_ be an issue.

**Comment by klemay** [comment]
Initial mockups are explained in context here: https://docs.google.com/presentation/d/1uPyf60yf-8R-qrJ9y1lWoxEEEM_jcJGeVExtNO16MTg/edit#slide=id.g54fb1c147e_0_0

(Requires Hypothesis sign-in)

I'm going to do an asynch demo in Slack explaining what we've come up with so far.

**Comment by klemay** [comment]
We've been treating this as an epic so it's been renamed as such. A demo of our final low-fi mockup was completed last sprint, and now we have a designer on board to start prototyping.

**Comment by klemay** [comment]
Clickable prototype was shared in Slack here: https://hypothes-is.slack.com/archives/C07NXBDNW/p1556835710005400

**Comment by klemay** [comment]
^ Given we have our initial prototype, linked above, closing this issue. Further work on activity views will be tracked in or as part of #932.
