### ISSUE TITLE
Prepare client for development of LMS views

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#936]
Part of #932 

We have a consensus that LMS views will be built client-side, and, at the outset at least, will exist in the main client codebase.

We need to prep for development in the client, whatever that might entail, keeping in mind the other client stuff going on (migration, etc.).

**Comment by robertknight** [comment]
The scope of this task was intentionally vague, because the details of what exactly we are going to build for the LMS activity view are not completely clear.

The rough idea is that we will probably build a new SPA which communicates with h via the API, and provides an activity view oriented towards the needs of the LMS app. Initially we think we'll be building a prototype app in the client repo which re-uses components of the client such as the API client and components such as the annotation card.

With that in mind, there is general work we discussed in Brighton to make components of the client easier for us or third-party developers to use in new contexts. One of the larger parts of that is replacing AngularJS with a mix of a more modern UI library and web platform / JS standard library APIs. This work is being broken down in https://github.com/hypothesis/client/issues/972.

**Comment by robertknight** [comment]
I'm going to close this issue for now and say that https://github.com/hypothesis/client/issues/972 is the initial outcome. As we learn more about what the LMS app is likely to need, we'll file new issues.
