### ISSUE TITLE
Community Groups: Add client logic for retrieving specific group(s) from API

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#975]
Part of https://github.com/hypothesis/product-backlog/issues/866

To be able to display annotations in a specific-group context, the client needs to be able to respond to the presence of a query string parameter (presumably) and retrieve that group. It also needs to retrieve the specified group from the API, focus it and display it in the appropriate place in the group-select menu.

This work includes:

* [x] Specification of the query parameter (or whatever mechanism) to be used. One straightforward notion is that a `group` parameter could take a single group `pubid`. Some things to reflect upon include: is there any use for making a `group` or `groups` parameter take a list of groups for future flexibility? This may be distracting at this point, though, because presumably we need to know a single group to focus.
* [x] Client logic to retrieve this group and parse it into the groups list
* [x] Client logic to focus this group
* [x] UI representation of this group in "Currently Viewing"

Not in this work:

* User-friendly flow for constructing links with a focused group

**Comment by hmstepanek** [comment]
So based on our discussion earlier today,
When a group in Currently Viewing is no longer the selected group, it should remain in the Currently Viewing section. My concern is the name Currently Viewing sounds like the user has that group currently selected which is not the case in this scenario. 

We also said that the group should remain as the focused group the next time the user visits the page even though it's not a group that would normally show up in their list of groups. In order for this to happen, there would have to be a special api request made for that particular group as this will not work out of the box. Currently, if the focused group id is not in the list of fetched groups, it defaults to the first group in the list. This could also get tricky from the perspective of determining when to issue an api request to get the focused group and when we should not. Also note the focus caching is not page specific so this behavior of caching the focused id and grabbing its associated group is prob not ideal. For this reason I do not think we should strive to grab the focused group unless the user directly links to that group on that page.

**Comment by hmstepanek** [comment]
The settings live in src/annotator/config/index.js. A new url fragment parser would be introduced into src/annotator/config/settings.js. Note the settings that are available to the sidebar part of the client are filtered with a whitelist in src/sidebar/host-config.js so the new setting must be added to the whitelist. The groups are loaded in src/sidebar/services/groups.js. This is currently where the api requests happen to get the list of groups. It's possible the user has a link to a group that is already in the list of groups. It's also possible the user has a link to a group that won't be returned from those api calls and a separate api call needs to be made. In order to avoid time waiting for the existing api calls to complete and then determining whether a separate api call needs to be made we could simply make a special api call for that group at the same time. Then if the groups are duplicates, one of them will be filtered out in the combine groups method in the utils dir.

**Comment by hmstepanek** [comment]
Note if we enable linking to a particular group it follows that we would be able to link to particular annotations in that group. This of course would require fetching groups for the annotations as well. The alternative would be to disable sharing of annotations via the #annotations url in a group that is out of scope.  To simplify things at the moment it would probably be easier to disable sharing for now. @lyzadanger do you think we should aim to handle both of these long term/thoughts on this?

**Comment by lyzadanger** [comment]
> Note if we enable linking to a particular group it follows that we would be able to link to particular annotations in that group. This of course would require fetching groups for the annotations as well. The alternative would be to disable sharing of annotations via the #annotations url in a group that is out of scope. To simplify things at the moment it would probably be easier to disable sharing for now. @lyzadanger do you think we should aim to handle both of these long term/thoughts on this?

I don't entirely understand this...but it sounds related to something that Rob was talking about regarding the URL query syntax. Can you check in with @robertknight ?

**Comment by hmstepanek** [comment]
Possible error states: It's possible that the requested group was deleted (aka: the link is outdated) or the user doesn't have permission to view it (since nothing is stoping a user from constructing their own url of a private group that they aren't a member of)-prob want to show a 404 here?

**Comment by lyzadanger** [comment]
> Possible error states: It's possible that the requested group was deleted (aka: the link is outdated) or the user doesn't have permission to view it (since nothing is stoping a user from constructing their own url of a private group that they aren't a member of)-prob want to show a 404 here

All of these cases would result in a 404 from the API. I don't know the best way, if any, to present this to the user, as a literal 404 could indicate any number of actual problems. @robertknight any UI-level thoughts on this?

**Comment by hmstepanek** [comment]
Possible legal/illegal states of requesting a group:

Restricted Groups:
1. The group is a restricted group, the user is not a member, the group is not scoped to the page, the group scope is enforced. The api request gives us back the group and the client would have to be responsible for filtering out the group since it should not be visible to the user.

1. The group is a restricted group, the user is not a member, the group is not scoped to the page, the group scope is not enforced. The group should be visible to the user.

1. The group is a restricted group, the user is not a member, the group is scoped to the page, the group scope is enforced or not enforced. The group should be visible to the user.

1. The group is a restricted group, the user is a member, the group is scoped or out of scope, the group scope is enforced or not enforced. The group should be visible to the user.

Private groups:
1. The group is a private group, the user is not a member. The api returns a 404 in this case and the group should not be visible to the user. 

1. The group is a private group, the user is a member. The group should be visible to the user.

Open Groups:
1. The group is an open group, the group is not scoped to the page, the group scope is enforced. The api request gives us back the group and the client would have to be responsible for filtering out the group since it should not be visible to the user. 

1. The group is an open group, the group is not scoped to the page, the group scope is not enforced. The group should be visible to the user.

1. The group is an open group, the group is scoped to the page, the group scope is enforced or unenforced. The group should be visible to the user.

**Comment by hmstepanek** [comment]
We need to agree on an "api" for this new group url. The api we currently have is:
`#annotations:ANNOTATION_ID` 
`#annotations:query:QUERY`

@robertknight suggested adding:
`#annotations:group:GROUP_ID`

Note the `#annotations` is a trigger name for the browser-extension to open. There is a possible refactor to make here in that, since we are expanding this api and anticipating that it may be expanded again in the short term future to enable specifying a query in a group such as `#annotations:group:GROUP_ID:query:QUERY`. We may want to move to a more generic trigger string such as `#hypothesis`. This might intuitively make more sense as then we would have:
`#hypothesis:annotation:ANNOTATION_ID`
`#hypothesis:query:QUERY`
`#hypothesis:group:GROUP_ID`
In the future:
`#hypothesis:group:GROUP_ID:query:QUERY` or maybe this would just be a variation of `#hypothesis:query:QUERY`

**Comment by hmstepanek** [comment]
Annotations are requested here: https://github.com/hypothesis/client/blob/a3c6dd465b7cc5fbf749d9fbf74b962f972468f8/src/sidebar/components/sidebar-content.js#L114. It grabs anns from all the groups if a specific ann is requested or anns for a the focused group if there isn't a specific ann requested.

**Comment by hmstepanek** [comment]
The selected annotation is filtered here: https://github.com/hypothesis/client/blob/2b4ded56c181e32a9f859006c3254864e581acce/src/sidebar/components/sidebar-content.js#L234

**Comment by dwhly** [comment]
> We may want to move to a more generic trigger string such as #hypothesis

I get the reasoning behind why we might want a trigger that is more specific to H than "annotations", (Genius used the same #annotations fragment, and both their sidebar and ours would trigger if both our chrome extensions were present).  But there's also an argument to standards here that we should consider.  If we're going to potentially have these links embedded at scale around the web, what is the ideal design?

Please review these two notes by the W3 Web Annotation WG.

Selectors and States:
https://www.w3.org/TR/2017/NOTE-selectors-states-20170223/

And Embedding Web Annotations in HTML
https://www.w3.org/TR/2017/NOTE-annotation-html-20170223/

With #annotations what we're saying is "Please go to service X and fetch Y annotation(s) and then anchor it/them to the current page".  We're assuming that service is Hypothesis, even though when Genius uses #annotations that's not the case (what happens is it just pops our sidebar and ... nothing).  Presumably the rationale behind shifting to #hypothesis is to make it clear that we're talking about the Hypothesis service.  But perhaps a different solution is instead to imagine a fragment syntax aligned with the work done in these W3C notes that encodes both annotation as a type and service as a parameter that might be universal.  This way we continue to pave the way towards an interoperable ecosystem of clients and services.

For instance, we might link to a specific annotation:
`https://example.org/#annotation(service="https://api.hypothes.is",id=ANNOTATION_ID)`

or all annotations within a group (for the current page):
`https://example.org/#annotation(service="https://api.hypothes.is",group=GROUP_ID)`

or multiple facets, like annotations with a certain tag made by a specific user (for the current page):
`https://example.org/#annotation(service="https://api.hypothes.is",user=USER_ID,tag=TAG)`

For now, we whitelist the services for which we respond: api.hypothes.is, lms.hypothes.is, etc and ignore others.  When our client becomes multi-service capable and we see a new service encoded in a URL like this then we know how to process it, where the service is to query, and we can attempt to fetch and anchor any annotations that are returned.

Just to be clear, these W3C notes do not yet propose an "#annotation" syntax along these lines, but perhaps they should-- and perhaps H should lead in that regard.
 
For further reading: what @bokand is considering wrt deep linking native to the browser:
https://github.com/bokand/ScrollToTextFragment/issues/4

cc @azaroth42 and @bigbluehat

**Comment by robertknight** [comment]
I'm happy for us to explore ideas around a documented syntax which can be used by multiple clients but I don't want to let those discussions delay us from delivering Community Groups to users. We can always implement support for alternative syntaxes in future. My understanding is that we do not expect users to generate these `#annotations:group:...` links themselves, but they will use the bouncer service to do that. In that sense, the `https://hyp.is/...` URLs are the current "public API" of this feature. This enables us to transition existing links to alternate syntaxes in future, or alternate modes of delivering the annotation functionality.

**Comment by robertknight** [comment]
> If we're going to potentially have these links embedded at scale around the web, what is the ideal design?

I have a bunch of thoughts around potential interoperability / standardisation of `#annotations` fragments, but I'd like to propose that we continue that discussion in a separate issue.

**Comment by dwhly** [comment]
> I'm happy for us to explore ideas around a documented syntax which can be used by multiple clients but I don't want to let those discussions delay us from delivering Community Groups to users.

Yep. Apologies if my comment came off as suggesting that. :)

> My understanding is that we do not expect users to generate these #annotations:group:... links themselves, but they will use the bouncer service to do that. In that sense, the https://hyp.is/... URLs are the current "public API" of this feature.

Yes-- though unfortunately, the flow is such that what ends up visible in user's address bars, and thus most liable to be copied and pasted after the fact, is the resulting fragment.  We see quite a few of these in the wild, and I imagine that trend will only continue.

> I have a bunch of thoughts around potential interoperability / standardisation of #annotations fragments, but I'd like to propose that we continue that discussion in a separate issue.

Yep.

**Comment by hmstepanek** [comment]
TODO's: 

- [ ] add documentation for new group setting/fragment.

**Comment by hmstepanek** [comment]
How to filter out groups in cases where both a linked to annotation and a linked to group are provided and the linked to group is not normally in the list of groups: https://hypothes-is.slack.com/archives/C1M8NH76X/p1554397519016100
