### ISSUE TITLE
Linking to #annotations in groups that don't normally show up on the page

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#986]
With the introduction of community groups or the ability to link to a group that wouldn't normally show up on a page, there is the possibility that a user may also link to an annotation made in a group that wouldn't normally show up on the page.

The current assumption in the client implementation is that a user would never link to an annotation outside of the usual groups list so this case is not currently covered in the existing implementation. This requires some thinking about the order in which we would make the api requests and where we would make the api requests for this group and annotation that wouldn't normally show up.

This is part of https://github.com/hypothesis/product-backlog/issues/975.

**Comment by dwhly** [comment]
> there is the possibility that a user may also link to an annotation made in a group that wouldn't normally show up on the page

Can you explain this?  Don't understand.

**Comment by hmstepanek** [comment]
We currently allow a user to link to a particular annotation (for example: https://www.griffinbenefits.com/employeebenefitsblog/history_of_healthcare#annotations:MnV6mlEbEemiPsPkhIokMw). In the case of community groups this means a member of a restricted group not scoped to the page may chose to share the annotation with a non member user by clicking the share link on that annotation. In this scenario the user who receives the link would be requesting to view an annotation made in a group that is not normally visible to them. Thus the client must look up the annotation, and specially request the group it belongs to. This kind of special request is not handled by the current implementation. Currently we assume all annotations on the page have been made in the normally visible list of groups (normally visible groups being: groups scoped to the page or restricted unenforced out of scope groups that the user is a member of). In this case the out of scope unenforced group that the user is not a member of is not a group that would normally show up and thus requires special handling.

**Comment by lyzadanger** [comment]
Put another way: the Community Groups project has an explicit requirement that we be able to generate and handle share links for a given URL (i.e. document_uri), in the context of a specific group. So, multiple annotations, but viewed through the lens of a particular group. And that group may not be one that would normally "show up" on that page for the given user, due to scoping.

Now, consider an individual annotation that exists within one of these groups—an open or restricted group that "would not normally show up" for a given user on the annotation’s URL. A single annotation. Before this work, the client had never encountered a situation where it needed to display a single annotation within a group _that wasn't already in the user's groups list_. Thus, the client doesn't "have" the (needed) group information for the annotation's group because it's not one that would normally show up for this user.

That means there's extra work to do in the client to account for this case—an annotation that the user has access to, inside of a group that the user has access to, technically, but wouldn't normally "show up here." Specifically, as Hannah alludes to, the client will need to somehow retrieve the metadata for the annotation's group, as it won't have access to that in the user's groups list.
